; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py tests/pass/061-operators-logical/061-operators-logical.zap -o tests/pass/061-operators-logical/061-operators-logical_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/061-operators-logical/061-operators-logical.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/061-operators-logical/061-operators-logical.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$R                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/061-operators-logical/061-operators-logical.zap 4:     byte r = 0
	STZ _MAIN$R
; /home/dusan/src/ZAP-compiler/tests/pass/061-operators-logical/061-operators-logical.zap 6:     if (!0) && (0 || 1) 
; /home/dusan/src/ZAP-compiler/tests/pass/061-operators-logical/061-operators-logical.zap 7:         r = 1
	LDA #$01
	STA _MAIN$R
; /home/dusan/src/ZAP-compiler/tests/pass/061-operators-logical/061-operators-logical.zap 12:     result = r
	LDA _MAIN$R
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file