; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap -o tests/pass/219-long-target-byte-add/219-long-target-byte-add_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_5
__MATH1                 = __LVSLOT_6
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 4
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 4
; Byte variables
; Long variables
; ZP usage: 14 of 256 bytes ($00-$0D), 242 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 7: byte result @$0200 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 9: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$L                 = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 15:     a = 200
	LDA #$C8
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 16:     b = 200
	LDA #$C8
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 17:     l = a + b
	LDA _MAIN$B
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	JSR ADD32
	LDA __MATH0
	STA _MAIN$L
	LDA __MATH0+1
	STA _MAIN$L+1
	LDA __MATH0+2
	STA _MAIN$L+2
	LDA __MATH0+3
	STA _MAIN$L+3
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 18:     if l == 400
	LDA _MAIN$L+3
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_4
	LDA _MAIN$L+2
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_4
	LDA _MAIN$L+1
	CMP #$01
	BNE __ZAP_REL_ELSE_TMP_4
	LDA _MAIN$L
	CMP #$90
	BEQ __ZAP_then_3
__ZAP_REL_ELSE_TMP_4:
	JMP __ZAP_else_1
__ZAP_then_3:
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 19:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
__ZAP_endif_2:
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 23:     a = 1
	LDA #$01
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 24:     b = 255
	LDA #$FF
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 25:     l = a + b
	LDA _MAIN$B
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	JSR ADD32
	LDA __MATH0
	STA _MAIN$L
	LDA __MATH0+1
	STA _MAIN$L+1
	LDA __MATH0+2
	STA _MAIN$L+2
	LDA __MATH0+3
	STA _MAIN$L+3
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 26:     if l == 256
	LDA _MAIN$L+3
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_8
	LDA _MAIN$L+2
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_8
	LDA _MAIN$L+1
	CMP #$01
	BNE __ZAP_REL_ELSE_TMP_8
	LDA _MAIN$L
	CMP #$00
	BEQ __ZAP_then_7
__ZAP_REL_ELSE_TMP_8:
	JMP __ZAP_else_5
__ZAP_then_7:
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 27:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_6
__ZAP_else_5:
__ZAP_endif_6:
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 31:     a = 201
	LDA #$C9
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 32:     b = 200
	LDA #$C8
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 33:     l = a - b
	LDA _MAIN$B
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	JSR SUB32
	LDA __MATH0
	STA _MAIN$L
	LDA __MATH0+1
	STA _MAIN$L+1
	LDA __MATH0+2
	STA _MAIN$L+2
	LDA __MATH0+3
	STA _MAIN$L+3
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 34:     if l == 1
	LDA _MAIN$L+3
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_12
	LDA _MAIN$L+2
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_12
	LDA _MAIN$L+1
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_12
	LDA _MAIN$L
	CMP #$01
	BEQ __ZAP_then_11
__ZAP_REL_ELSE_TMP_12:
	JMP __ZAP_else_9
__ZAP_then_11:
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 35:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_10
__ZAP_else_9:
__ZAP_endif_10:
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 39:     a = 100
	LDA #$64
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 40:     b = 100
	LDA #$64
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 41:     l = a + b + 100
	LDA _MAIN$B
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	JSR ADD32
	LDA #$64
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	JSR ADD32
	LDA __MATH0
	STA _MAIN$L
	LDA __MATH0+1
	STA _MAIN$L+1
	LDA __MATH0+2
	STA _MAIN$L+2
	LDA __MATH0+3
	STA _MAIN$L+3
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 42:     if l == 300
	LDA _MAIN$L+3
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_16
	LDA _MAIN$L+2
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_16
	LDA _MAIN$L+1
	CMP #$01
	BNE __ZAP_REL_ELSE_TMP_16
	LDA _MAIN$L
	CMP #$2C
	BEQ __ZAP_then_15
__ZAP_REL_ELSE_TMP_16:
	JMP __ZAP_else_13
__ZAP_then_15:
; /home/dusan/src/ZAP-compiler/tests/pass/219-long-target-byte-add/219-long-target-byte-add.zap 43:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_14
__ZAP_else_13:
__ZAP_endif_14:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; ADD32: __MATH0 = __MATH0 + __MATH1
ADD32:
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	LDA __MATH0+2
	ADC __MATH1+2
	STA __MATH0+2
	LDA __MATH0+3
	ADC __MATH1+3
	STA __MATH0+3
	RTS
; SUB32: __MATH0 = __MATH0 - __MATH1
SUB32:
	LDA __MATH0
	SEC
	SBC __MATH1
	STA __MATH0
	LDA __MATH0+1
	SBC __MATH1+1
	STA __MATH0+1
	LDA __MATH0+2
	SBC __MATH1+2
	STA __MATH0+2
	LDA __MATH0+3
	SBC __MATH1+3
	STA __MATH0+3
	RTS
; End of file