; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -6502 -O1 tests/pass/042-array-loop/042-array-loop.zap -o tests/pass/042-array-loop/042-array-loop_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP0                  = __LVSLOT_6
__TMP2                  = __LVSLOT_7
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_2:	.res 1
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
; Byte variables
; ZP usage: 5 of 256 bytes ($00-$04), 251 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 10
; Arrays (BSS)


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/042-array-loop/042-array-loop.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$ARR               = __LVSLOT_1
_MAIN$I                 = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/042-array-loop/042-array-loop.zap 6:     i = 0
	LDA #$00
	STA _MAIN$I
; /home/dusan/src/ZAP-compiler/tests/pass/042-array-loop/042-array-loop.zap 8:     while i < 10
__ZAP_while_1:
	LDA _MAIN$I
	CMP #$0A
	BCS __ZAP_endwhile_2
; /home/dusan/src/ZAP-compiler/tests/pass/042-array-loop/042-array-loop.zap 9:         arr[i] = i
	LDA _MAIN$I
	LDX #$00
	STA __TMP2
	STX __TMP2+1
	LDA _MAIN$I
	CLC
	ADC #<_MAIN$ARR
	STA __TMP0
	TXA
	ADC #>_MAIN$ARR
	STA __TMP0+1
	LDA __TMP2
	LDY #$00
	STA (__TMP0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/042-array-loop/042-array-loop.zap 10:         i = i + 1
	INC _MAIN$I
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; /home/dusan/src/ZAP-compiler/tests/pass/042-array-loop/042-array-loop.zap 13:     result = arr[9]
	LDA _MAIN$ARR+9
	STA _RESULT
	RTS


.segment "CODE"
; End of file