; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/086-variables//086-variables.zap -o tests/pass/086-variables//086-variables_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 2
; Byte variables
; Word variables
; ZP usage: 3 of 256 bytes ($00-$02), 253 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\086-variables\086-variables.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_X = __LVSLOT_1
_MAIN_Y = __LVSLOT_2
_MAIN_Z = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\086-variables\086-variables.zap 4:     byte x = 100
	LDA #$64
	STA _MAIN_X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\086-variables\086-variables.zap 5:     word y = 200
	LDA #$C8
	STA _MAIN_Y
	STZ _MAIN_Y+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\086-variables\086-variables.zap 6:     word z = x + y
	LDA _MAIN_X
	CLC
	ADC _MAIN_Y
	STA _MAIN_Z
	LDA #$00
	ADC _MAIN_Y+1
	STA _MAIN_Z+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\086-variables\086-variables.zap 7:     result = z ; implicit truncation if required
	LDA _MAIN_Z
	LDX _MAIN_Z+1
	STA _RESULT
	RTS


.segment "CODE"
; End of file