; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap -o tests/pass/007-arrays-1d-byte/007-arrays-1d-byte_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 5
; Arrays (BSS)


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$ARR               = __LVSLOT_1
_MAIN$SUM               = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 4:     byte arr[5] = { 1, 2, 3, 4, 5}
	; Copy array [1, 2, 3, 4, 5] (5 elements)
	LDX #$00
__ZAP_ARR_COPY_1:
	LDA __ARRAY_DATA_1,X
	STA _MAIN$ARR,X
	INX
	CPX #5
	BNE __ZAP_ARR_COPY_1
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 6:     arr[0] = 10
	LDA #$0A
	STA _MAIN$ARR+0
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 7:     arr[1] = 20
	LDA #$14
	STA _MAIN$ARR+1
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 8:     arr[2] = 30
	LDA #$1E
	STA _MAIN$ARR+2
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 9:     arr[3] = 40
	LDA #$28
	STA _MAIN$ARR+3
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 10:     arr[4] = 50
	LDA #$32
	STA _MAIN$ARR+4
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 11:     sum = arr[0] + arr[1] + arr[2] + arr[3] + arr[4]
	LDA _MAIN$ARR+0
	CLC
	ADC _MAIN$ARR+1
	CLC
	ADC _MAIN$ARR+2
	CLC
	ADC _MAIN$ARR+3
	CLC
	ADC _MAIN$ARR+4
	STA _MAIN$SUM
; /home/dusan/src/ZAP-compiler/tests/pass/007-arrays-1d-byte/007-arrays-1d-byte.zap 12:     result = sum
	LDA _MAIN$SUM
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; ---------------------------------------------------------------------------
; Constant Data
__ARRAY_DATA_1:
	.byte $01, $02, $03, $04, $05
; End of file