; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/031-structs-simple/031-structs-simple.zap -o tests/pass/031-structs-simple/031-structs-simple_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 1
; Struct variables (BSS)


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/031-structs-simple/031-structs-simple.zap 5: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/031-structs-simple/031-structs-simple.zap 7: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$P                 = __LVSLOT_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/031-structs-simple/031-structs-simple.zap 9:     p.age = 42
	LDA #$2A
	STA _MAIN$P
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/031-structs-simple/031-structs-simple.zap 10:     result = p.age
	LDA _MAIN$P
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file