; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/078-port/078-port.zap -o tests/pass/078-port/078-port_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_VIA1                   = $9C40
_VIA2                   = $9C50
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure HELPER --
_HELPER:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/078-port/078-port.zap 26:     VIA1.ORB = $01      ; #wr
	LDA #$01
	STA _VIA1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/078-port/078-port.zap 27:     VIA1.DDRB = $FF     ; #rd #wr
	LDA #$FF
	STA _VIA1+2
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/078-port/078-port.zap 28:     VIA2.ORB = $02      ; #wr
	LDA #$02
	STA _VIA2
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/078-port/078-port.zap 29:     VIA2.DDRB = $FF     ; #rd #wr
	LDA #$FF
	STA _VIA2+2
	RTS


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/078-port/078-port.zap 34:     helper()
	JMP _HELPER


.segment "CODE"
; End of file