; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -6502 -O1 tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap -o tests/pass/162-pointer-deref-types/162-pointer-deref-types_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP2                  = __LVSLOT_6
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_6:	.res 2
; Pointer variables
; Byte variables
_BVAL:	.res 1
; Word variables
_WVAL:	.res 2
; ZP usage: 7 of 256 bytes ($00-$06), 249 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Arrays (BSS)
_BARR:	.res 3
_WARR:	.res 6


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 21: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 23: byte  bval = 0
	STA _BVAL
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 24: word  wval = 0
	STA _WVAL
	STA _WVAL+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 26: byte  barr[3] = {$AA, $BB, $CC}
	; Copy array [170, 187, 204] (3 elements)
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 26: byte  barr[3] = {$AA, $BB, $CC}
	; Copy array [170, 187, 204] (3 elements)
	TAX
__ZAP_ARR_COPY_1:
	LDA __ARRAY_DATA_1,X
	STA _BARR,X
	INX
	CPX #3
	BNE __ZAP_ARR_COPY_1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 27: word  warr[3] = {$1234, $2345, $3456}
	; Copy array [4660, 9029, 13398] (3 elements)
	LDX #$00
__ZAP_ARR_COPY_2:
	LDA __ARRAY_DATA_2,X
	STA _WARR,X
	LDA __ARRAY_DATA_2+1,X
	STA _WARR+1,X
	INX
	INX
	CPX #6
	BNE __ZAP_ARR_COPY_2
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$BPTR              = __LVSLOT_1
_MAIN$WPTR              = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 34:     bptr = @bval
	LDA #<_BVAL
	LDX #>_BVAL
	STA _MAIN$BPTR
	STX _MAIN$BPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 35:     bptr^ = $AB
	LDA #$AB
	LDY #$00
	STA (_MAIN$BPTR),Y
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 36:     if bval == $AB
	LDA _BVAL
	CMP #$AB
	BNE __ZAP_else_3
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 37:         result = result + 1
	INC _RESULT
__ZAP_else_3:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 41:     wptr = @wval
	LDA #<_WVAL
	LDX #>_WVAL
	STA _MAIN$WPTR
	STX _MAIN$WPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 42:     wptr^ = $1234
	LDA #$34
	LDX #$12
	STX __TMP2+1
	LDY #$00
	STA (_MAIN$WPTR),Y
	INY
	LDA __TMP2+1
	STA (_MAIN$WPTR),Y
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 43:     if wval == $1234
	LDA _WVAL
	CMP #$34
	BNE __ZAP_else_6
	LDX _WVAL+1
	CPX #$12
	BNE __ZAP_else_6
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 44:         result = result + 1
	INC _RESULT
__ZAP_else_6:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 48:     bptr = @barr
	LDA #<_BARR
	LDX #>_BARR
	STA _MAIN$BPTR
	STX _MAIN$BPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 49:     bptr = bptr + 1
	INC _MAIN$BPTR
	BNE __ZAP_INC_WORD_10
	INC _MAIN$BPTR+1
__ZAP_INC_WORD_10:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 50:     if bptr^ == $BB
	LDY #$00
	LDA (_MAIN$BPTR),Y
	CMP #$BB
	BNE __ZAP_else_11
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 51:         result = result + 1
	INC _RESULT
__ZAP_else_11:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 55:     wptr = @warr
	LDA #<_WARR
	LDX #>_WARR
	STA _MAIN$WPTR
	STX _MAIN$WPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 56:     wptr = wptr + 1
	CLC
	ADC #$02
	STA _MAIN$WPTR
	BCC __ZAP_CARRY_ADD_PTR_14
	INC _MAIN$WPTR+1
__ZAP_CARRY_ADD_PTR_14:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 57:     if wptr^ == $2345
	LDY #1
	LDA (_MAIN$WPTR),Y
	TAX
	DEY
	LDA (_MAIN$WPTR),Y
	CMP #$45
	BNE __ZAP_else_15
	CPX #$23
	BNE __ZAP_else_15
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 58:         result = result + 1
	INC _RESULT
__ZAP_else_15:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 62:     wptr = @warr
	LDA #<_WARR
	LDX #>_WARR
	STA _MAIN$WPTR
	STX _MAIN$WPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 63:     wptr = wptr + 2
	CLC
	ADC #$04
	STA _MAIN$WPTR
	BCC __ZAP_CARRY_ADD_PTR_19
	INC _MAIN$WPTR+1
__ZAP_CARRY_ADD_PTR_19:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 64:     if wptr^ == $3456
	LDY #1
	LDA (_MAIN$WPTR),Y
	TAX
	DEY
	LDA (_MAIN$WPTR),Y
	CMP #$56
	BNE __ZAP_else_20
	CPX #$34
	BNE __ZAP_else_20
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 65:         result = result + 1
	INC _RESULT
__ZAP_else_20:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 69:     bptr = @barr
	LDA #<_BARR
	LDX #>_BARR
	STA _MAIN$BPTR
	STX _MAIN$BPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 70:     bptr = bptr + 2
	CLC
	ADC #$02
	STA _MAIN$BPTR
	BCC __ZAP_CARRY_ADD_PTR_24
	INC _MAIN$BPTR+1
__ZAP_CARRY_ADD_PTR_24:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 71:     if bptr^ == $CC
	LDY #$00
	LDA (_MAIN$BPTR),Y
	CMP #$CC
	BNE __ZAP_else_25
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 72:         result = result + 1
	INC _RESULT
__ZAP_else_25:
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 76:     wptr = @wval
	LDA #<_WVAL
	LDX #>_WVAL
	STA _MAIN$WPTR
	STX _MAIN$WPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 77:     wptr^ = $AABB
	LDA #$BB
	LDX #$AA
	STX __TMP2+1
	LDY #$00
	STA (_MAIN$WPTR),Y
	INY
	LDA __TMP2+1
	STA (_MAIN$WPTR),Y
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 78:     if wval == $AABB
	LDA _WVAL
	CMP #$BB
	BNE __ZAP_else_28
	LDX _WVAL+1
	CPX #$AA
	BNE __ZAP_else_28
; /home/dusan/src/ZAP-compiler/tests/pass/162-pointer-deref-types/162-pointer-deref-types.zap 79:         result = result + 1
	INC _RESULT
__ZAP_else_28:
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Constant Data
__ARRAY_DATA_1:
	.byte $AA, $BB, $CC
__ARRAY_DATA_2:
	.word $1234, $2345, $3456
; End of file