; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap -o tests/pass/246-multi-ptr-decl/246-multi-ptr-decl_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP0                  = __LVSLOT_9
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
__LVSLOT_4:	.res 2
__LVSLOT_5:	.res 2
__LVSLOT_9:	.res 2
; Pointer variables
; Byte variables
_BVAL1:	.res 1
_BVAL2:	.res 1
; Word variables
_WVAL1:	.res 2
_WVAL2:	.res 2
; ZP usage: 16 of 256 bytes ($00-$0F), 240 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 7: word result @$0200 = 0
	STZ _RESULT
	STZ _RESULT+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 9: byte bval1 = 11
	LDA #$0B
	STA _BVAL1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 10: byte bval2 = 22
	LDA #$16
	STA _BVAL2
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 11: word wval1 = $1234
	LDA #$34
	STA _WVAL1
	LDA #$12
	STA _WVAL1+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 12: word wval2 = $5678
	LDA #$78
	STA _WVAL2
	LDA #$56
	STA _WVAL2+1
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 14: proc check(byte cond)
; -- Procedure CHECK --
_CHECK:
_CHECK$COND             = __LVSLOT_1
	STA _CHECK$COND
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 15:     if cond != 0
	LDA _CHECK$COND
	BEQ __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 16:         result += 1
	INC _RESULT
	BNE __ZAP_INC_WORD_4
	INC _RESULT+1
__ZAP_INC_WORD_4:
	JMP __ZAP_endif_2
__ZAP_else_1:
__ZAP_endif_2:
	RTS


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 20: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$PTR1              = __LVSLOT_3
_MAIN$PTR2              = __LVSLOT_4
_MAIN$PTR3              = __LVSLOT_3
_MAIN$PLAIN             = __LVSLOT_2
_MAIN$PA                = __LVSLOT_3
_MAIN$PB                = __LVSLOT_4
_MAIN$PC                = __LVSLOT_5
_MAIN$WP1               = __LVSLOT_3
_MAIN$WP2               = __LVSLOT_4
_MAIN$LEGACY            = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 28:     ptr1 = @bval1
	LDA #<_BVAL1
	LDX #>_BVAL1
	STA _MAIN$PTR1
	STX _MAIN$PTR1+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 29:     ptr2 = @bval2
	LDA #<_BVAL2
	LDX #>_BVAL2
	STA _MAIN$PTR2
	STX _MAIN$PTR2+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 30:     check(ptr1^ == 11)    ; 1
	LDA (_MAIN$PTR1)
	CMP #11
	BEQ __ZAP_REL_TRUE_5
	LDA #$00
	JMP __ZAP_REL_END_6
__ZAP_REL_TRUE_5:
	LDA #1
__ZAP_REL_END_6:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 31:     check(ptr2^ == 22)    ; 2
	LDA (_MAIN$PTR2)
	CMP #22
	BEQ __ZAP_REL_TRUE_7
	LDA #$00
	JMP __ZAP_REL_END_8
__ZAP_REL_TRUE_7:
	LDA #1
__ZAP_REL_END_8:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 34:     wp1 = @wval1
	LDA #<_WVAL1
	LDX #>_WVAL1
	STA _MAIN$WP1
	STX _MAIN$WP1+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 35:     wp2 = @wval2
	LDA #<_WVAL2
	LDX #>_WVAL2
	STA _MAIN$WP2
	STX _MAIN$WP2+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 36:     check(wp1^ == $1234)  ; 3
	LDA #$34
	LDX #$12
	STA __TMP0
	STX __TMP0+1
	LDY #1
	LDA (_MAIN$WP1),Y
	TAX
	LDA (_MAIN$WP1)
	CPX __TMP0+1
	BNE __ZAP_REL_END_10
	CMP __TMP0
	BEQ __ZAP_REL_TRUE_9
	LDA #$00
	JMP __ZAP_REL_END_10
__ZAP_REL_TRUE_9:
	LDA #1
__ZAP_REL_END_10:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 37:     check(wp2^ == $5678)  ; 4
	LDA #$78
	LDX #$56
	STA __TMP0
	STX __TMP0+1
	LDY #1
	LDA (_MAIN$WP2),Y
	TAX
	LDA (_MAIN$WP2)
	CPX __TMP0+1
	BNE __ZAP_REL_END_12
	CMP __TMP0
	BEQ __ZAP_REL_TRUE_11
	LDA #$00
	JMP __ZAP_REL_END_12
__ZAP_REL_TRUE_11:
	LDA #1
__ZAP_REL_END_12:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 40:     ptr3 = @bval1
	LDA #<_BVAL1
	LDX #>_BVAL1
	STA _MAIN$PTR3
	STX _MAIN$PTR3+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 41:     plain = 99
	LDA #$63
	STA _MAIN$PLAIN
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 42:     check(ptr3^ == 11)    ; 5
	LDA (_MAIN$PTR3)
	CMP #11
	BEQ __ZAP_REL_TRUE_13
	LDA #$00
	JMP __ZAP_REL_END_14
__ZAP_REL_TRUE_13:
	LDA #1
__ZAP_REL_END_14:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 43:     check(plain == 99)    ; 6
	LDA _MAIN$PLAIN
	CMP #$63
	BEQ __ZAP_CMP_TRUE_15
	LDA #$00
	JMP __ZAP_CMP_END_16
__ZAP_CMP_TRUE_15:
	LDA #$01
__ZAP_CMP_END_16:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 46:     pa = @bval1
	LDA #<_BVAL1
	LDX #>_BVAL1
	STA _MAIN$PA
	STX _MAIN$PA+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 47:     pb = @bval2
	LDA #<_BVAL2
	LDX #>_BVAL2
	STA _MAIN$PB
	STX _MAIN$PB+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 48:     pc = @bval1
	LDA #<_BVAL1
	LDX #>_BVAL1
	STA _MAIN$PC
	STX _MAIN$PC+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 49:     check(pa^ == 11)      ; 7
	LDA (_MAIN$PA)
	CMP #11
	BEQ __ZAP_REL_TRUE_17
	LDA #$00
	JMP __ZAP_REL_END_18
__ZAP_REL_TRUE_17:
	LDA #1
__ZAP_REL_END_18:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 50:     check(pb^ == 22)      ; 8
	LDA (_MAIN$PB)
	CMP #22
	BEQ __ZAP_REL_TRUE_19
	LDA #$00
	JMP __ZAP_REL_END_20
__ZAP_REL_TRUE_19:
	LDA #1
__ZAP_REL_END_20:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 51:     check(pc^ == 11)      ; 9
	LDA (_MAIN$PC)
	CMP #11
	BEQ __ZAP_REL_TRUE_21
	LDA #$00
	JMP __ZAP_REL_END_22
__ZAP_REL_TRUE_21:
	LDA #1
__ZAP_REL_END_22:
	JSR _CHECK
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 54:     legacy = @bval2
	LDA #<_BVAL2
	LDX #>_BVAL2
	STA _MAIN$LEGACY
	STX _MAIN$LEGACY+1
; /home/dusan/src/ZAP-compiler/tests/pass/246-multi-ptr-decl/246-multi-ptr-decl.zap 55:     check(legacy^ == 22)  ; 10
	LDA (_MAIN$LEGACY)
	CMP #22
	BEQ __ZAP_REL_TRUE_23
	LDA #$00
	JMP __ZAP_REL_END_24
__ZAP_REL_TRUE_23:
	LDA #1
__ZAP_REL_END_24:
	JSR _CHECK
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file