; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\089-shadowing-local\089-shadowing-local.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\089-shadowing-local\089-shadowing-local_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
_X                      = $9C41
_MAIN$X                 = $9C42
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\089-shadowing-local\089-shadowing-local.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\089-shadowing-local\089-shadowing-local.zap 2: byte x @40001 = 1 ; global x
	LDA #$01
	STA _X
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\089-shadowing-local\089-shadowing-local.zap 4: proc main()
; -- Procedure MAIN --
_MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\089-shadowing-local\089-shadowing-local.zap 5:     byte x = 5 @40002; local shadows global
	LDA #$05
	STA _MAIN$X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\089-shadowing-local\089-shadowing-local.zap 6:     result = x ; expect 5 (local)
	LDA _MAIN$X
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file