; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/073-directives/073-directives.zap -o tests/pass/073-directives/073-directives_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/073-directives/073-directives.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure TEST1 --
_TEST1:
; /home/dusan/src/ZAP-compiler/tests/pass/073-directives/073-directives.zap 7:         result = result + $01
	INC _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/073-directives/073-directives.zap 15:         result = result + $01
	INC _RESULT
	RTS


; ---------------------------------------------------------------------------
; -- Procedure TEST2 --
_TEST2:
; /home/dusan/src/ZAP-compiler/tests/pass/073-directives/073-directives.zap 25:         result = result + $01
	INC _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/073-directives/073-directives.zap 29:         result = result + $01
	INC _RESULT
	RTS


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/073-directives/073-directives.zap 38:     test1()
	JSR _TEST1
; /home/dusan/src/ZAP-compiler/tests/pass/073-directives/073-directives.zap 39:     test2()
	JMP _TEST2


.segment "CODE"
; End of file