; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap -o tests/pass/227-lor-complex-operands/227-lor-complex-operands_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP4                  = __LVSLOT_7
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_7:	.res 2
; ZP usage: 2 of 256 bytes ($00-$01), 254 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Struct variables (BSS)
_R:	.res 1
; Arrays (BSS)
_ARR:	.res 3
_WARR:	.res 4


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 14: byte result @$0200 = 0
	STZ _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 16: byte arr[3] = {0, 5, 0}
	; Copy array [0, 5, 0] (3 elements)
	LDX #$00
__ZAP_ARR_COPY_1:
	LDA __ARRAY_DATA_1,X
	STA _ARR,X
	INX
	CPX #3
	BNE __ZAP_ARR_COPY_1
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 17: word warr[2] = {0, $0100}
	LDA #$00
	LDX #$00
	STA _WARR+0
	STX _WARR+1
	LDA #$00
	LDX #$01
	STA _WARR+2
	STX _WARR+3
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 24: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 25:     r.flag = 1
	LDA #$01
	STA _R
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 28:     if arr[0] || arr[1]
	LDA _ARR+0
	BNE __ZAP_LOR_TRUE_5
	LDA _ARR+1
	BNE __ZAP_LOR_TRUE_5
	LDA #$00
	JMP __ZAP_LOR_END_6
__ZAP_LOR_TRUE_5:
	LDA #1
__ZAP_LOR_END_6:
	BEQ __ZAP_else_2
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 29:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_3
__ZAP_else_2:
__ZAP_endif_3:
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 33:     if arr[0] || arr[2]
	LDA _ARR+0
	BNE __ZAP_LOR_TRUE_10
	LDA _ARR+2
	BNE __ZAP_LOR_TRUE_10
	LDA #$00
	JMP __ZAP_LOR_END_11
__ZAP_LOR_TRUE_10:
	LDA #1
__ZAP_LOR_END_11:
	BNE __ZAP_endif_8
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 35:         result = result + 1
	INC _RESULT
__ZAP_endif_8:
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 39:     if warr[0] || warr[1]
	LDA _WARR+0
	LDX _WARR+1
	STA __TMP4
	TXA
	ORA __TMP4
	BNE __ZAP_LOR_TRUE_15
	LDA _WARR+2
	LDX _WARR+3
	STA __TMP4
	TXA
	ORA __TMP4
	BNE __ZAP_LOR_TRUE_15
	LDA #$00
	JMP __ZAP_LOR_END_16
__ZAP_LOR_TRUE_15:
	LDA #1
__ZAP_LOR_END_16:
	BEQ __ZAP_else_12
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 40:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_13
__ZAP_else_12:
__ZAP_endif_13:
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 44:     if r.flag || 0
	LDA _R
	BNE __ZAP_LOR_TRUE_20
	LDA #$00
	BNE __ZAP_LOR_TRUE_20
	LDA #$00
	JMP __ZAP_LOR_END_21
__ZAP_LOR_TRUE_20:
	LDA #1
__ZAP_LOR_END_21:
	BEQ __ZAP_else_17
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 45:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_18
__ZAP_else_17:
__ZAP_endif_18:
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 49:     if arr[1] && arr[1]
	LDA _ARR+1
	BEQ __ZAP_LAND_FALSE_25
	LDA _ARR+1
	BEQ __ZAP_LAND_FALSE_25
	LDA #1
	JMP __ZAP_LAND_END_26
__ZAP_LAND_FALSE_25:
	LDA #$00
__ZAP_LAND_END_26:
	BEQ __ZAP_else_22
; /home/dusan/src/ZAP-compiler/tests/pass/227-lor-complex-operands/227-lor-complex-operands.zap 50:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_23
__ZAP_else_22:
__ZAP_endif_23:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; ---------------------------------------------------------------------------
; Constant Data
__ARRAY_DATA_1:
	.byte $00, $05, $00
; End of file