; Generated by Zap Compiler
; Command: /usr/bin/python3 compiler.py -6502 ./tests-todo/pass/test_math_1.zap -o ./tests-todo/pass/test_math_1.s
; ------------------------------

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2
TMP2:	.res 4
TMP3:	.res 2

; Pointer variables
_PTR1:	.res 2
_PTR2:	.res 2
; Byte variables
_MATH1_B1:	.res 1
_MATH1_B2:	.res 1
_MATH1_R:	.res 1
_MATH2_R:	.res 1
_MATH3_B1:	.res 1
_MATH3_B2:	.res 1
_MATH4_B1:	.res 1
_MATH4_B2:	.res 1
; Word variables
_MATH2_B1:	.res 2
_MATH2_B2:	.res 2
_MATH3_R:	.res 2
_MATH4_R:	.res 2

.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 6: byte ^ptr1 = 40000
	LDA #$40
	STA _PTR1
	LDA #$9C
	STA _PTR1+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 7: word ^ptr2 = 40000+32
	LDA #96
	LDX #156
	STA _PTR2
	STX _PTR2+1

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 9: proc math1(byte b1, byte b2)    ; 2, 9
; -- Procedure MATH1 --
MATH1:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 12:     r = b1 + 0
	LDA _MATH1_B1
	LDX #0
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 13:     r = b1 - 0
	LDA _MATH1_B1
	LDX #0
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 14:     r = b1 + 1
	LDA _MATH1_B1
	CLC
	ADC #1
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 15:     r = b1 - 1                 
	LDA _MATH1_B1
	SEC
	SBC #1
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 16:     ptr1^ = r               ; 0: 1
	LDA _MATH1_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 17:     ptr1 = ptr1+1
	INC _PTR1
	BNE INC_WORD_1
	INC _PTR1+1
INC_WORD_1:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 19:     r = b1 * 5
	LDA _MATH1_B1
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #5
	STA TMP2
	STX TMP3
	JSR MUL8
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 20:     ptr1^ = r
	LDA _MATH1_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 21:     ptr1 = ptr1+1           ; 1: $3D
	INC _PTR1
	BNE INC_WORD_2
	INC _PTR1+1
INC_WORD_2:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 23:     r = b2 / 4              
	LDA _MATH1_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #4
	STA TMP2
	STX TMP3
	JSR DIV8
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 24:     ptr1^ = r
	LDA _MATH1_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 25:     ptr1 = ptr1+1           ; 2: 2
	INC _PTR1
	BNE INC_WORD_3
	INC _PTR1+1
INC_WORD_3:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 27:     r = b2 / 3
	LDA _MATH1_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #3
	STA TMP2
	STX TMP3
	JSR DIV8
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 28:     ptr1^ = r
	LDA _MATH1_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 29:     ptr1 = ptr1+1           ; 3: 3
	INC _PTR1
	BNE INC_WORD_4
	INC _PTR1+1
INC_WORD_4:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 31:     r = b2 % 7
	LDA _MATH1_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #7
	STA TMP2
	STX TMP3
	JSR MOD8
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 32:     ptr1^ = r
	LDA _MATH1_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 33:     ptr1 = ptr1+1           ; 4: 2
	INC _PTR1
	BNE INC_WORD_5
	INC _PTR1+1
INC_WORD_5:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 35:     r = b2 % 1
	LDA _MATH1_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #1
	STA TMP2
	STX TMP3
	JSR MOD8
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 36:     ptr1^ = r
	LDA _MATH1_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 37:     ptr1 = ptr1+1           ; 5: 9
	INC _PTR1
	BNE INC_WORD_6
	INC _PTR1+1
INC_WORD_6:
	RTS
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 40: proc math2(word b1, word b2)    ; $fa02, $1209
; -- Procedure MATH2 --
MATH2:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 43:     r = b1 + 0
	LDA _MATH2_B1
	LDX _MATH2_B1+1
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 44:     r = b1 - 0
	LDA _MATH2_B1
	LDX _MATH2_B1+1
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 45:     r = b1 + 1
	LDA _MATH2_B1
	CLC
	ADC #1
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 46:     r = b1 - 1                 
	LDA _MATH2_B1
	SEC
	SBC #1
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 47:     ptr1^ = r               ; 6: 1
	LDA _MATH2_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 48:     ptr1 = ptr1+1
	INC _PTR1
	BNE INC_WORD_7
	INC _PTR1+1
INC_WORD_7:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 50:     r = b1 * 5
	LDA _MATH2_B1
	LDX _MATH2_B1+1
	STA TMP0
	STX TMP0+1
	LDA #5
	STA TMP2
	STX TMP3
	JSR MUL16_8
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 51:     ptr1^ = r
	LDA _MATH2_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 52:     ptr1 = ptr1+1           ; 7: $3D
	INC _PTR1
	BNE INC_WORD_8
	INC _PTR1+1
INC_WORD_8:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 54:     r = b2 / 4              
	LDA _MATH2_B2
	LDX _MATH2_B2+1
	STA TMP0
	STX TMP0+1
	LDA #4
	STA TMP2
	STX TMP3
	JSR DIV16_8
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 55:     ptr1^ = r
	LDA _MATH2_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 56:     ptr1 = ptr1+1           ; 8: 2
	INC _PTR1
	BNE INC_WORD_9
	INC _PTR1+1
INC_WORD_9:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 58:     r = b2 / 3
	LDA _MATH2_B2
	LDX _MATH2_B2+1
	STA TMP0
	STX TMP0+1
	LDA #3
	STA TMP2
	STX TMP3
	JSR DIV16_8
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 59:     ptr1^ = r
	LDA _MATH2_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 60:     ptr1 = ptr1+1           ; 9: 3
	INC _PTR1
	BNE INC_WORD_10
	INC _PTR1+1
INC_WORD_10:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 62:     r = b2 % 7
	LDA _MATH2_B2
	LDX _MATH2_B2+1
	STA TMP0
	STX TMP0+1
	LDA #7
	STA TMP2
	STX TMP3
	JSR MOD16_8
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 63:     ptr1^ = r
	LDA _MATH2_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 64:     ptr1 = ptr1+1           ; $0a: 2
	INC _PTR1
	BNE INC_WORD_11
	INC _PTR1+1
INC_WORD_11:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 66:     r = b2 % 1
	LDA _MATH2_B2
	LDX _MATH2_B2+1
	STA TMP0
	STX TMP0+1
	LDA #1
	STA TMP2
	STX TMP3
	JSR MOD16_8
	STA _MATH2_R
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 67:     ptr1^ = r
	LDA _MATH2_R
	LDX #0
	STA TMP2
	STX TMP2+1
	LDA _PTR1
	LDX _PTR1+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 68:     ptr1 = ptr1+1           ; $0b 9
	INC _PTR1
	BNE INC_WORD_12
	INC _PTR1+1
INC_WORD_12:
	RTS
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 73: proc math3(byte b1, byte b2)    ; $fa02, $1209
; -- Procedure MATH3 --
MATH3:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 76:     r = b1 + 0
	LDA _MATH3_B1
	LDX #0
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 77:     r = b1 - 0
	LDA _MATH3_B1
	LDX #0
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 78:     r = b1 + 1
	LDA _MATH3_B1
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #1
	CLC
	ADC TMP0
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 79:     r = b1 - 1                 
	LDA _MATH3_B1
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #1
	STA TMP2
	SEC
	LDA TMP0
	SBC TMP2
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 80:     ptr2^ = r               ; $10: 1
	LDA _MATH3_R
	LDX _MATH3_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 81:     ptr2 = ptr2+1
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_13
	INC _PTR2+1
CARRY_ADD_PTR_13:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 83:     r = b1 * 5
	LDA _MATH3_B1
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #5
	STA TMP2
	STX TMP3
	JSR MUL8
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 84:     ptr2^ = r
	LDA _MATH3_R
	LDX _MATH3_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 85:     ptr2 = ptr2+1           ; $12: $3D
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_14
	INC _PTR2+1
CARRY_ADD_PTR_14:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 87:     r = b2 / 4              
	LDA _MATH3_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #4
	STA TMP2
	STX TMP3
	JSR DIV8
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 88:     ptr2^ = r
	LDA _MATH3_R
	LDX _MATH3_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 89:     ptr2 = ptr2+1           ; $14: 2
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_15
	INC _PTR2+1
CARRY_ADD_PTR_15:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 91:     r = b2 / 3
	LDA _MATH3_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #3
	STA TMP2
	STX TMP3
	JSR DIV8
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 92:     ptr2^ = r
	LDA _MATH3_R
	LDX _MATH3_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 93:     ptr2 = ptr2+1           ; $16: 3
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_16
	INC _PTR2+1
CARRY_ADD_PTR_16:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 95:     r = b2 % 7
	LDA _MATH3_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #7
	STA TMP2
	STX TMP3
	JSR MOD8
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 96:     ptr2^ = r
	LDA _MATH3_R
	LDX _MATH3_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 97:     ptr2 = ptr2+1           ; $18: 2
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_17
	INC _PTR2+1
CARRY_ADD_PTR_17:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 99:     r = b2 % 1
	LDA _MATH3_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #1
	STA TMP2
	STX TMP3
	JSR MOD8
	LDX #0
	STA _MATH3_R
	STX _MATH3_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 100:     ptr2^ = r
	LDA _MATH3_R
	LDX _MATH3_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 101:     ptr2 = ptr2+1           ; $1a: 9
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_18
	INC _PTR2+1
CARRY_ADD_PTR_18:
	RTS
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 106: proc math4(byte b1, byte b2)    ; $fa02, $1209
; -- Procedure MATH4 --
MATH4:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 109:     r = b1 + 0
	LDA _MATH4_B1
	LDX #0
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 110:     r = b1 - 0
	LDA _MATH4_B1
	LDX #0
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 111:     r = b1 + 1
	LDA _MATH4_B1
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #1
	CLC
	ADC TMP0
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 112:     r = b1 - 1                 
	LDA _MATH4_B1
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #1
	STA TMP2
	SEC
	LDA TMP0
	SBC TMP2
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 113:     ptr2^ = r               ; $1c: $fa01
	LDA _MATH4_R
	LDX _MATH4_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 114:     ptr2 = ptr2+1
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_19
	INC _PTR2+1
CARRY_ADD_PTR_19:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 116:     r = b1 * 5
	LDA _MATH4_B1
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #5
	STA TMP2
	STX TMP3
	JSR MUL8
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 117:     ptr2^ = r
	LDA _MATH4_R
	LDX _MATH4_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 118:     ptr2 = ptr2+1           ; $1e: $0004 e20A
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_20
	INC _PTR2+1
CARRY_ADD_PTR_20:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 120:     r = b2 / 4              
	LDA _MATH4_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #4
	STA TMP2
	STX TMP3
	JSR DIV8
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 121:     ptr2^ = r
	LDA _MATH4_R
	LDX _MATH4_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 122:     ptr2 = ptr2+1           ; $20: $0482
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_21
	INC _PTR2+1
CARRY_ADD_PTR_21:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 124:     r = b2 / 3
	LDA _MATH4_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #3
	STA TMP2
	STX TMP3
	JSR DIV8
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 125:     ptr2^ = r
	LDA _MATH4_R
	LDX _MATH4_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 126:     ptr2 = ptr2+1           ; $22: $0603
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_22
	INC _PTR2+1
CARRY_ADD_PTR_22:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 128:     r = b2 % $0309
	LDA _MATH4_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #9
	LDX #3
	STA TMP2
	STX TMP3
	JSR MOD8_16
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 129:     ptr2^ = r
	LDA _MATH4_R
	LDX _MATH4_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 130:     ptr2 = ptr2+1           ; $24: $02dc
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_23
	INC _PTR2+1
CARRY_ADD_PTR_23:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 132:     r = b2 % 1
	LDA _MATH4_B2
	LDX #0
	STA TMP0
	STX TMP0+1
	LDA #1
	STA TMP2
	STX TMP3
	JSR MOD8
	LDX #0
	STA _MATH4_R
	STX _MATH4_R+1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 133:     ptr2^ = r
	LDA _MATH4_R
	LDX _MATH4_R+1
	STA TMP2
	STX TMP2+1
	LDA _PTR2
	LDX _PTR2+1
	STA TMP0
	STX TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 134:     ptr2 = ptr2+1           ; $26: $1209
	LDA _PTR2
	CLC
	ADC #2
	STA _PTR2
	BCC CARRY_ADD_PTR_24
	INC _PTR2+1
CARRY_ADD_PTR_24:
	RTS
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 140: proc main()
; -- Procedure MAIN --
MAIN:
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 141:     math1(2, 9)    
	LDA #2
	STA _MATH1_B1
	LDA #9
	STA _MATH1_B2
	JSR MATH1
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 142:     math2($fa02, $1209)
	LDA #2
	LDX #250
	STA _MATH2_B1
	STX _MATH2_B1+1
	LDA #9
	LDX #18
	STA _MATH2_B2
	STX _MATH2_B2+1
	JSR MATH2
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 143:     math3(2, 9)
	LDA #2
	STA _MATH3_B1
	LDA #9
	STA _MATH3_B2
	JSR MATH3
; /home/dusan/src/ZAP-compiler/tests-todo/pass/test_math_1.zap 144:     math4($fa02, $1209)    
	LDA #2
	LDX #250
	STA _MATH4_B1
	LDA #9
	LDX #18
	STA _MATH4_B2
	JSR MATH4
	RTS

.segment "CODE"
; ------------------------------
; Math Runtime Routines
; ------------------------------

; MUL8: 8x8=16 multiply
; Input: TMP0 (multiplicand), TMP2 (multiplier)
; Output: A=low, X=high
MUL8:
	LDA #0
	LDX #8
	CLC
MUL8_LOOP:
	ROR TMP2
	BCC MUL8_SKIP
	CLC
	ADC TMP0
MUL8_SKIP:
	ROR
	ROR TMP3
	DEX
	BNE MUL8_LOOP
	TAX
	LDA TMP3
	RTS

; MUL16_8: 16x8=16 multiply
; Input: TMP0,TMP1 (multiplicand), TMP2 (multiplier)
; Output: A=low, X=high
MUL16_8:
	LDA TMP0
	STA TMP3
	LDA TMP1
	PHA
	LDA TMP2
	STA TMP0
	LDA TMP3
	STA TMP2
	JSR MUL8
	STA TMP3
	STX TMP0
	PLA
	STA TMP2
	JSR MUL8
	CLC
	ADC TMP0
	TAX
	LDA TMP3
	RTS

; DIV8: 8/8=8 divide
; Input: TMP0 (dividend), TMP2 (divisor)
; Output: A=quotient, X=0
DIV8:
	LDA #0
	LDX #8
	CLC
DIV8_LOOP:
	ROL TMP0
	ROL
	CMP TMP2
	BCC DIV8_SKIP
	SBC TMP2
DIV8_SKIP:
	DEX
	BNE DIV8_LOOP
	ROL TMP0
	LDA TMP0
	LDX #0
	RTS

; DIV16_8: 16/8=16 divide
; Input: TMP0,TMP1 (dividend), TMP2 (divisor)
; Output: A=low, X=high
DIV16_8:
	LDA #0
	STA TMP3
	LDX #16
	CLC
DIV16_8_LOOP:
	ROL TMP0
	ROL TMP1
	ROL TMP3
	LDA TMP3
	CMP TMP2
	BCC DIV16_8_SKIP
	SBC TMP2
	STA TMP3
DIV16_8_SKIP:
	DEX
	BNE DIV16_8_LOOP
	ROL TMP0
	ROL TMP1
	LDA TMP0
	LDX TMP1
	RTS

; MOD8: 8%8=8 modulo
; Input: TMP0 (dividend), TMP2 (divisor)
; Output: A=remainder, X=0
MOD8:
	LDA #0
	LDX #8
	CLC
MOD8_LOOP:
	ROL TMP0
	ROL
	CMP TMP2
	BCC MOD8_SKIP
	SBC TMP2
MOD8_SKIP:
	DEX
	BNE MOD8_LOOP
	LDX #0
	RTS

; MOD16_8: 16%8=8 modulo
; Input: TMP0,TMP1 (dividend), TMP2 (divisor)
; Output: A=remainder, X=0
MOD16_8:
	LDA #0
	STA TMP3
	LDX #16
	CLC
MOD16_8_LOOP:
	ROL TMP0
	ROL TMP1
	ROL TMP3
	LDA TMP3
	CMP TMP2
	BCC MOD16_8_SKIP
	SBC TMP2
	STA TMP3
MOD16_8_SKIP:
	DEX
	BNE MOD16_8_LOOP
	LDA TMP3
	LDX #0
	RTS

; MOD8_16: 8%16=8 modulo
; Input: TMP0 (dividend), TMP2,TMP3 (divisor)
; Output: A=remainder, X=0
MOD8_16:
	LDA TMP0
	CMP TMP2
	LDA #0
	SBC TMP3
	BCC MOD8_16_RET
	LDA TMP0
	SBC TMP2
	LDX #0
	RTS
MOD8_16_RET:
	LDA TMP0
	LDX #0
	RTS

__END:
.export __END

; End of file