; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -O1 tests/pass/237-long-array-compound/237-long-array-compound.zap -o tests/pass/237-long-array-compound/237-long-array-compound_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH_STACK            = __LVSLOT_2
__MATH0                 = __LVSLOT_3
__MATH1                 = __LVSLOT_4
__TMP0                  = __LVSLOT_5
__TMP1:	.res 2
__TMP2                  = __LVSLOT_6
__TMP3                  = __LVSLOT_7
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 32
__LVSLOT_3:	.res 4
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 2
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
; Byte variables
; ZP usage: 49 of 256 bytes ($00-$30), 207 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Arrays (BSS)
_LARR:	.res 12


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 11: byte result @$0200 = 0
	STZ _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 13: long larr[3] = {0, $11111111, $33333333}
	; Copy array [0, 286331153, 858993459] (3 elements, 12 bytes)
	LDA #<__ARRAY_DATA_1
	LDX #>__ARRAY_DATA_1
	STA __TMP0
	STX __TMP0+1
	LDA #<_LARR
	LDX #>_LARR
	STA __TMP2
	STX __TMP2+1
	LDX #12
	JSR __COPY_BYTES
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$I                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 19:     larr[0] += 1000
	LDA _LARR+0
	STA __MATH0
	LDA _LARR+1
	STA __MATH0+1
	LDA _LARR+2
	STA __MATH0+2
	LDA _LARR+3
	STA __MATH0+3
	LDA __MATH0
	STA __MATH_STACK+0
	LDA __MATH0+1
	STA __MATH_STACK+1
	LDA __MATH0+2
	STA __MATH_STACK+2
	LDA __MATH0+3
	STA __MATH_STACK+3
	LDA #$E8
	LDX #$03
	STA __MATH1
	STX __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA __MATH_STACK+0
	STA __MATH0
	LDA __MATH_STACK+1
	STA __MATH0+1
	LDA __MATH_STACK+2
	STA __MATH0+2
	LDA __MATH_STACK+3
	STA __MATH0+3
	JSR ADD32
	LDA __MATH0
	LDX __MATH0+1
	STA _LARR+0
	LDA __MATH0+1
	STA _LARR+1
	LDA __MATH0+2
	STA _LARR+2
	LDA __MATH0+3
	STA _LARR+3
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 20:     if larr[0] == 1000
	LDA #$E8
	LDX #$03
	STA __MATH1
	STX __MATH1+1
	LDA #$00
	STA __MATH1+2
	STA __MATH1+3
	LDA _LARR+0
	STA __MATH0
	LDA _LARR+1
	STA __MATH0+1
	LDA _LARR+2
	STA __MATH0+2
	LDA _LARR+3
	STA __MATH0+3
	CMP __MATH1+3
	BNE __ZAP_else_1
	LDA __MATH0+2
	CMP __MATH1+2
	BNE __ZAP_else_1
	LDA __MATH0+1
	CMP __MATH1+1
	BNE __ZAP_else_1
	LDA __MATH0
	CMP __MATH1
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 21:         result = result + 1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 25:     larr[1] *= 2
	LDA _LARR+4
	STA __MATH0
	LDA _LARR+5
	STA __MATH0+1
	LDA _LARR+6
	STA __MATH0+2
	LDA _LARR+7
	STA __MATH0+3
	LDA __MATH0
	STA __MATH_STACK+0
	LDA __MATH0+1
	STA __MATH_STACK+1
	LDA __MATH0+2
	STA __MATH_STACK+2
	LDA __MATH0+3
	STA __MATH_STACK+3
	LDA #$02
	LDX #$00
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA __MATH_STACK+0
	STA __MATH0
	LDA __MATH_STACK+1
	STA __MATH0+1
	LDA __MATH_STACK+2
	STA __MATH0+2
	LDA __MATH_STACK+3
	STA __MATH0+3
	JSR MUL32
	LDA __MATH0
	LDX __MATH0+1
	STA _LARR+4
	LDA __MATH0+1
	STA _LARR+5
	LDA __MATH0+2
	STA _LARR+6
	LDA __MATH0+3
	STA _LARR+7
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 26:     if larr[1] == $22222222
	LDA #$22
	STA __MATH0
	STA __MATH0+1
	STA __MATH0+2
	STA __MATH0+3
	LDA __MATH0
	STA __MATH1
	LDA __MATH0+1
	STA __MATH1+1
	LDA __MATH0+2
	STA __MATH1+2
	LDA __MATH0+3
	STA __MATH1+3
	LDA _LARR+4
	STA __MATH0
	LDA _LARR+5
	STA __MATH0+1
	LDA _LARR+6
	STA __MATH0+2
	LDA _LARR+7
	STA __MATH0+3
	CMP __MATH1+3
	BNE __ZAP_else_5
	LDA __MATH0+2
	CMP __MATH1+2
	BNE __ZAP_else_5
	LDA __MATH0+1
	CMP __MATH1+1
	BNE __ZAP_else_5
	LDA __MATH0
	CMP __MATH1
	BNE __ZAP_else_5
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 27:         result = result + 1
	INC _RESULT
__ZAP_else_5:
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 31:     larr[2] |= $F
	LDA _LARR+8
	STA __MATH0
	LDA _LARR+9
	STA __MATH0+1
	LDA _LARR+10
	STA __MATH0+2
	LDA _LARR+11
	STA __MATH0+3
	LDA __MATH0
	ORA #$0F
	STA __MATH0
	LDA __MATH0+1
	ORA #$00
	STA __MATH0+1
	LDA __MATH0+2
	ORA #$00
	STA __MATH0+2
	LDA __MATH0+3
	ORA #$00
	STA __MATH0+3
	LDA __MATH0
	STA _LARR+8
	LDA __MATH0+1
	STA _LARR+9
	LDA __MATH0+2
	STA _LARR+10
	LDA __MATH0+3
	STA _LARR+11
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 32:     if larr[2] == $3333333F
	LDA #$3F
	STA __MATH0
	LDA #$33
	STA __MATH0+1
	STA __MATH0+2
	STA __MATH0+3
	LDA __MATH0
	STA __MATH1
	LDA __MATH0+1
	STA __MATH1+1
	LDA __MATH0+2
	STA __MATH1+2
	LDA __MATH0+3
	STA __MATH1+3
	LDA _LARR+8
	STA __MATH0
	LDA _LARR+9
	STA __MATH0+1
	LDA _LARR+10
	STA __MATH0+2
	LDA _LARR+11
	STA __MATH0+3
	CMP __MATH1+3
	BNE __ZAP_else_9
	LDA __MATH0+2
	CMP __MATH1+2
	BNE __ZAP_else_9
	LDA __MATH0+1
	CMP __MATH1+1
	BNE __ZAP_else_9
	LDA __MATH0
	CMP __MATH1
	BNE __ZAP_else_9
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 33:         result = result + 1
	INC _RESULT
__ZAP_else_9:
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 37:     i = 0
	STZ _MAIN$I
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 38:     while i < 3
__ZAP_while_13:
	LDA _MAIN$I
	CMP #$03
	BCS __ZAP_endwhile_14
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 39:         larr[0] += 1
	LDA _LARR+0
	STA __MATH0
	LDA _LARR+1
	STA __MATH0+1
	LDA _LARR+2
	STA __MATH0+2
	LDA _LARR+3
	STA __MATH0+3
	LDA __MATH0
	STA __MATH_STACK+0
	LDA __MATH0+1
	STA __MATH_STACK+1
	LDA __MATH0+2
	STA __MATH_STACK+2
	LDA __MATH0+3
	STA __MATH_STACK+3
	LDA #$01
	LDX #$00
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA __MATH_STACK+0
	STA __MATH0
	LDA __MATH_STACK+1
	STA __MATH0+1
	LDA __MATH_STACK+2
	STA __MATH0+2
	LDA __MATH_STACK+3
	STA __MATH0+3
	JSR ADD32
	LDA __MATH0
	LDX __MATH0+1
	STA _LARR+0
	LDA __MATH0+1
	STA _LARR+1
	LDA __MATH0+2
	STA _LARR+2
	LDA __MATH0+3
	STA _LARR+3
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 40:         i = i + 1
	INC _MAIN$I
	JMP __ZAP_while_13
__ZAP_endwhile_14:
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 42:     if larr[0] == 1003
	LDA #$EB
	LDX #$03
	STA __MATH1
	STX __MATH1+1
	LDA #$00
	STA __MATH1+2
	STA __MATH1+3
	LDA _LARR+0
	STA __MATH0
	LDA _LARR+1
	STA __MATH0+1
	LDA _LARR+2
	STA __MATH0+2
	LDA _LARR+3
	STA __MATH0+3
	CMP __MATH1+3
	BNE __ZAP_else_16
	LDA __MATH0+2
	CMP __MATH1+2
	BNE __ZAP_else_16
	LDA __MATH0+1
	CMP __MATH1+1
	BNE __ZAP_else_16
	LDA __MATH0
	CMP __MATH1
	BNE __ZAP_else_16
; /home/dusan/src/ZAP-compiler/tests/pass/237-long-array-compound/237-long-array-compound.zap 43:         result = result + 1
	INC _RESULT
__ZAP_else_16:
	RTS


.segment "CODE"


; ------------------------------
; Shared byte copy routine
; Inputs: __TMP0/__TMP0+1=src, __TMP2/__TMP2+1=dst, X=len (1..255), Y=0
; Clobbers: A, X, Y
; Note: length must fit in one page; longer copies stay inline
__COPY_BYTES:
	LDY #$00
	CPX #$00
	BEQ COPY_BYTES_DONE
COPY_BYTES_LOOP:
	LDA (__TMP0),Y
	STA (__TMP2),Y
	INY
	DEX
	BNE COPY_BYTES_LOOP
COPY_BYTES_DONE:
	RTS
ADD32:
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	LDA __MATH0+2
	ADC __MATH1+2
	STA __MATH0+2
	LDA __MATH0+3
	ADC __MATH1+3
	STA __MATH0+3
	RTS
MUL32:
	LDA __MATH0
	STA __TMP0
	LDA __MATH0+1
	STA __TMP1
	LDA __MATH0+2
	STA __TMP2
	LDA __MATH0+3
	STA __TMP3
	STZ __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	LDX #32
MUL32_LOOP:
	LSR __MATH1+3
	ROR __MATH1+2
	ROR __MATH1+1
	ROR __MATH1
	BCC MUL32_SKIP
	LDA __MATH0
	CLC
	ADC __TMP0
	STA __MATH0
	LDA __MATH0+1
	ADC __TMP1
	STA __MATH0+1
	LDA __MATH0+2
	ADC __TMP2
	STA __MATH0+2
	LDA __MATH0+3
	ADC __TMP3
	STA __MATH0+3
MUL32_SKIP:
	ASL __TMP0
	ROL __TMP1
	ROL __TMP2
	ROL __TMP3
	DEX
	BNE MUL32_LOOP
	RTS
__ARRAY_DATA_1:
	.byte $00, $00, $00, $00, $11, $11, $11, $11, $33, $33, $33, $33
; End of file