; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -6502 -O1 tests/pass/226-long-unary-neg/226-long-unary-neg.zap -o tests/pass/226-long-unary-neg/226-long-unary-neg_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_3
__MATH1                 = __LVSLOT_4
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 4
__LVSLOT_3:	.res 4
__LVSLOT_4:	.res 4
; Long variables
; ZP usage: 12 of 256 bytes ($00-$0B), 244 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 12: byte result @$0200 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
_MAIN$Y                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 19:     x = 0
	LDA #$00
	STA _MAIN$X
	STA _MAIN$X+1
	STA _MAIN$X+2
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 20:     y = -x
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	JSR NEG32
	LDA __MATH0
	STA _MAIN$Y
	LDA __MATH0+1
	STA _MAIN$Y+1
	LDA __MATH0+2
	STA _MAIN$Y+2
	LDA __MATH0+3
	STA _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 21:     if y == 0
	CMP #$00
	BNE __ZAP_else_1
	LDA _MAIN$Y+2
	BNE __ZAP_else_1
	LDA _MAIN$Y+1
	BNE __ZAP_else_1
	LDA _MAIN$Y
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 22:         result = result + 1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 26:     x = 10
	LDA #$0A
	STA _MAIN$X
	LDA #$00
	STA _MAIN$X+1
	STA _MAIN$X+2
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 27:     y = -x
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	JSR NEG32
	LDA __MATH0
	STA _MAIN$Y
	LDA __MATH0+1
	STA _MAIN$Y+1
	LDA __MATH0+2
	STA _MAIN$Y+2
	LDA __MATH0+3
	STA _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 28:     if y == $FFFFFFF6
	CMP #$FF
	BNE __ZAP_else_5
	LDA _MAIN$Y+2
	CMP #$FF
	BNE __ZAP_else_5
	LDA _MAIN$Y+1
	CMP #$FF
	BNE __ZAP_else_5
	LDA _MAIN$Y
	CMP #$F6
	BNE __ZAP_else_5
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 29:         result = result + 1
	INC _RESULT
__ZAP_else_5:
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 33:     x = $FFFFFFFF
	LDA #$FF
	STA _MAIN$X
	STA _MAIN$X+1
	STA _MAIN$X+2
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 34:     y = -x
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	JSR NEG32
	LDA __MATH0
	STA _MAIN$Y
	LDA __MATH0+1
	STA _MAIN$Y+1
	LDA __MATH0+2
	STA _MAIN$Y+2
	LDA __MATH0+3
	STA _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 35:     if y == 1
	CMP #$00
	BNE __ZAP_else_9
	LDA _MAIN$Y+2
	BNE __ZAP_else_9
	LDA _MAIN$Y+1
	BNE __ZAP_else_9
	LDA _MAIN$Y
	CMP #$01
	BNE __ZAP_else_9
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 36:         result = result + 1
	INC _RESULT
__ZAP_else_9:
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 40:     x = $12345678
	LDA #$78
	STA _MAIN$X
	LDA #$56
	STA _MAIN$X+1
	LDA #$34
	STA _MAIN$X+2
	LDA #$12
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 41:     y = x + (-x)
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	JSR NEG32
	LDA _MAIN$X
	STA __MATH1
	LDA _MAIN$X+1
	STA __MATH1+1
	LDA _MAIN$X+2
	STA __MATH1+2
	LDA _MAIN$X+3
	STA __MATH1+3
	JSR ADD32
	LDA __MATH0
	STA _MAIN$Y
	LDA __MATH0+1
	STA _MAIN$Y+1
	LDA __MATH0+2
	STA _MAIN$Y+2
	LDA __MATH0+3
	STA _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 42:     if y == 0
	CMP #$00
	BNE __ZAP_else_13
	LDA _MAIN$Y+2
	BNE __ZAP_else_13
	LDA _MAIN$Y+1
	BNE __ZAP_else_13
	LDA _MAIN$Y
	BNE __ZAP_else_13
; /home/dusan/src/ZAP-compiler/tests/pass/226-long-unary-neg/226-long-unary-neg.zap 43:         result = result + 1
	INC _RESULT
__ZAP_else_13:
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; ADD32: __MATH0 = __MATH0 + __MATH1
ADD32:
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	LDA __MATH0+2
	ADC __MATH1+2
	STA __MATH0+2
	LDA __MATH0+3
	ADC __MATH1+3
	STA __MATH0+3
	RTS
NEG32:
	SEC
	LDA __MATH0
	EOR #$FF
	ADC #$00
	STA __MATH0
	LDA __MATH0+1
	EOR #$FF
	ADC #$00
	STA __MATH0+1
	LDA __MATH0+2
	EOR #$FF
	ADC #$00
	STA __MATH0+2
	LDA __MATH0+3
	EOR #$FF
	ADC #$00
	STA __MATH0+3
	RTS