; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\039-procedures-basic\039-procedures-basic.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\039-procedures-basic\039-procedures-basic_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 1
; Pointer variables
; Byte variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\039-procedures-basic\039-procedures-basic.zap 6: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure SET42 --
_SET42:
_SET42$DEST             = __LVSLOT_1
_SET42$VAR1             = __LVSLOT_2
	STA _SET42$DEST
	STX _SET42$DEST+1
	STY _SET42$VAR1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\039-procedures-basic\039-procedures-basic.zap 2:     dest^ = var1
	LDA _SET42$VAR1
	STA (_SET42$DEST)
	RTS


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_3
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\039-procedures-basic\039-procedures-basic.zap 9:     byte x = 0
	STZ _MAIN$X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\039-procedures-basic\039-procedures-basic.zap 10:     set42(@x, 42)
	LDA #<_MAIN$X
	LDX #>_MAIN$X
	LDY #$2A
	JSR _SET42
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\039-procedures-basic\039-procedures-basic.zap 11:     result = x
	LDA _MAIN$X
	STA _RESULT
	RTS


.segment "CODE"
; End of file