; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/023-modulo//023-modulo.zap -o tests/pass/023-modulo//023-modulo_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0 = __LVSLOT_4
__MATH1 = __LVSLOT_5
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 4
; Byte variables
; ZP usage: 10 of 256 bytes ($00-$09), 246 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\023-modulo\023-modulo.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_X = __LVSLOT_1
_MAIN_Y = __LVSLOT_2
_MAIN_Z = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\023-modulo\023-modulo.zap 4:     byte x = 7
	LDA #$07
	STA _MAIN_X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\023-modulo\023-modulo.zap 5:     byte y = 3
	LDA #$03
	STA _MAIN_Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\023-modulo\023-modulo.zap 6:     byte z = x % y
	LDA _MAIN_X
	STA __MATH0
	LDA _MAIN_Y
	JSR __MOD8_A
	STA _MAIN_Z
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\023-modulo\023-modulo.zap 7:     result = z
	STA _RESULT
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; ---------------------------------------------------------------------------
; __MOD8_A: right operand in A
__MOD8_A:
	STA __MATH1
; __MOD8: 8%8=8 modulo
; Input: __MATH0 (dividend), __MATH1 (divisor)
; Output: __MATH0=remainder (low byte)
; __MOD8: 8%8=8 modulo
; Input: __MATH0 (dividend), __MATH1 (divisor)
; Output: __MATH0=remainder (low byte)
	LDA #$00
	LDX #$08
	CLC
MOD8_LOOP:
	ROL __MATH0
	ROL
	CMP __MATH1
	BCC MOD8_SKIP
	SBC __MATH1
MOD8_SKIP:
	DEX
	BNE MOD8_LOOP
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	RTS