; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures_6502_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure INCREMENT_ALL --
_INCREMENT_ALL:
_INCREMENT_ALL$COUNT    = __LVSLOT_1
	STA _INCREMENT_ALL$COUNT
_INCREMENT_ALL$I        = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures.zap 5:     i = 0
	LDA #$00
	STA _INCREMENT_ALL$I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures.zap 6:     while i < count
__ZAP_while_1:
	LDA _INCREMENT_ALL$I
	CMP _INCREMENT_ALL$COUNT
	BCS __ZAP_endwhile_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures.zap 7:         result = result + 1
	INC _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures.zap 8:         i = i + 1
	INC _INCREMENT_ALL$I
	JMP __ZAP_while_1
__ZAP_endwhile_2:
	RTS


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\013-nested-procedures\013-nested-procedures.zap 13:     increment_all(15)
	LDA #$0F
	JMP _INCREMENT_ALL


.segment "CODE"
; End of file