; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/054-nested-arrays//054-nested-arrays.zap -o tests/pass/054-nested-arrays//054-nested-arrays_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 6
; Arrays (BSS)


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_ARR = __LVSLOT_1
_MAIN_SUM = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 6:     arr[0] = 10
	LDA #$0A
	STA _MAIN_ARR+0
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 7:     arr[1] = 20
	LDA #$14
	STA _MAIN_ARR+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 8:     arr[2] = 30
	LDA #$1E
	STA _MAIN_ARR+2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 9:     arr[3] = 40
	LDA #$28
	STA _MAIN_ARR+3
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 10:     arr[4] = 50
	LDA #$32
	STA _MAIN_ARR+4
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 11:     arr[5] = 60
	LDA #$3C
	STA _MAIN_ARR+5
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 12:     sum = arr[0] + arr[5]
	LDA _MAIN_ARR+0
	CLC
	ADC _MAIN_ARR+5
	STA _MAIN_SUM
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\054-nested-arrays\054-nested-arrays.zap 13:     result = sum
	STA _RESULT
	RTS


.segment "CODE"
; End of file