; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py tests/fail/zp-overflow-cfg/zp-overflow-cfg.zap -o tests/fail/zp-overflow-cfg/zp-overflow-cfg_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP0                  = __LVSLOT_5
__TMP2                  = __LVSLOT_6
__TMP3                  = __LVSLOT_7
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_5:	.res 2
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
; Word variables
; ZP usage: 8 of 256 bytes ($00-$07), 248 free


.segment "CODE"
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/fail/zp-overflow-cfg/zp-overflow-cfg.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/fail/zp-overflow-cfg/zp-overflow-cfg.zap 5:     a = 1
	LDA #$01
	STA _MAIN$A
	STZ _MAIN$A+1
; /home/dusan/src/ZAP-compiler/tests/fail/zp-overflow-cfg/zp-overflow-cfg.zap 6:     b = a * 2
	LDA _MAIN$A
	LDX _MAIN$A+1
	STA __TMP0
	STX __TMP0+1
	ASL __TMP0
	ROL __TMP0+1
	LDA __TMP0
	LDX __TMP0+1
	STA _MAIN$B
	STX _MAIN$B+1
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file