; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -6502 -O1 tests/pass/094-struct-init/094-struct-init.zap -o tests/pass/094-struct-init/094-struct-init_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP1:	.res 2
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 2 of 256 bytes ($00-$01), 254 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 2
; Struct variables (BSS)


.segment "CODE"
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/094-struct-init/094-struct-init.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$S                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/094-struct-init/094-struct-init.zap 9:     S s = {1,2}
	LDA #$01
	STA _MAIN$S+0
	LDA #$02
	STA _MAIN$S+1
; /home/dusan/src/ZAP-compiler/tests/pass/094-struct-init/094-struct-init.zap 10:     result = s.a + s.b ; expect 3
	LDA _MAIN$S
	LDX #$00
	STA __TMP1
	LDA _MAIN$S+1
	CLC
	ADC __TMP1
	STA _RESULT
	RTS


.segment "CODE"
; End of file