; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py tests/pass/166-ptr-array-index/166-ptr-array-index.zap -o tests/pass/166-ptr-array-index/166-ptr-array-index_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_4
__MATH1                 = __LVSLOT_5
__TMP0                  = __LVSLOT_6
__TMP1:	.res 2
__TMP2                  = __LVSLOT_7
__TMP3                  = __LVSLOT_8
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 1
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
; Pointer variables
; Byte variables
; ZP usage: 19 of 256 bytes ($00-$12), 237 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Arrays (BSS)
_BARR:	.res 3
_WARR:	.res 6
_LARR:	.res 12
_SARR:	.res 6
_EARR:	.res 6


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 18: byte result @$9C40 = 0
	STZ _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 25: byte  barr[3] = {$AA, $BB, $CC}
	; Copy array [170, 187, 204] (3 elements)
	LDX #$00
__ZAP_ARR_COPY_1:
	LDA __ARRAY_DATA_1,X
	STA _BARR,X
	INX
	CPX #3
	BNE __ZAP_ARR_COPY_1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 26: word  warr[3] = {$1111, $2222, $3333}
	; Copy array [4369, 8738, 13107] (3 elements)
	LDX #$00
__ZAP_ARR_COPY_2:
	LDA __ARRAY_DATA_2,X
	STA _WARR,X
	LDA __ARRAY_DATA_2+1,X
	STA _WARR+1,X
	INX
	INX
	CPX #6
	BNE __ZAP_ARR_COPY_2
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 27: long  larr[3] = {$11111111, $22222222, $33333333}
	; Copy array [286331153, 572662306, 858993459] (3 elements, 12 bytes)
	LDA #<__ARRAY_DATA_3
	LDX #>__ARRAY_DATA_3
	STA __TMP0
	STX __TMP0+1
	LDA #<_LARR
	LDX #>_LARR
	STA __TMP2
	STX __TMP2+1
	LDX #12
	JSR __COPY_BYTES
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 28: MyPt  sarr[3] = {{1, 2}, {3, 4}, {5, 6}}
	LDA #$01
	STA _SARR+0
	LDA #$02
	STA _SARR+1
	LDA #$03
	STA _SARR+2
	LDA #$04
	STA _SARR+3
	LDA #$05
	STA _SARR+4
	LDA #$06
	STA _SARR+5
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 29: word  earr[3] = {100, 200, 300}             ; ENUM values stored as WORD
	; Copy array [100, 200, 300] (3 elements)
	LDX #$00
__ZAP_ARR_COPY_3:
	LDA __ARRAY_DATA_4,X
	STA _EARR,X
	LDA __ARRAY_DATA_4+1,X
	STA _EARR+1,X
	INX
	INX
	CPX #6
	BNE __ZAP_ARR_COPY_3
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 31: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$BPTR              = __LVSLOT_1
_MAIN$WPTR              = __LVSLOT_1
_MAIN$LPTR              = __LVSLOT_1
_MAIN$SPTR              = __LVSLOT_1
_MAIN$TMP               = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 39:     lptr = @larr
	LDA #<_LARR
	LDX #>_LARR
	STA _MAIN$LPTR
	STX _MAIN$LPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 40:     lptr += 2
	LDA _MAIN$LPTR
	CLC
	ADC #$08
	STA _MAIN$LPTR
	BCC __ZAP_CARRY_ADD_PTR_4
	INC _MAIN$LPTR+1
__ZAP_CARRY_ADD_PTR_4:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 41:     if lptr^ == $33333333
	LDA #$33
	STA __MATH0
	LDA #$33
	STA __MATH0+1
	LDA #$33
	STA __MATH0+2
	LDA #$33
	STA __MATH0+3
	LDA __MATH0
	STA __MATH1
	LDA __MATH0+1
	STA __MATH1+1
	LDA __MATH0+2
	STA __MATH1+2
	LDA __MATH0+3
	STA __MATH1+3
	LDA (_MAIN$LPTR)
	STA __MATH0
	LDY #1
	LDA (_MAIN$LPTR),Y
	STA __MATH0+1
	LDY #2
	LDA (_MAIN$LPTR),Y
	STA __MATH0+2
	LDY #3
	LDA (_MAIN$LPTR),Y
	STA __MATH0+3
	LDA __MATH0+3
	CMP __MATH1+3
	BNE __ZAP_REL_ELSE_TMP_8
	LDA __MATH0+2
	CMP __MATH1+2
	BNE __ZAP_REL_ELSE_TMP_8
	LDA __MATH0+1
	CMP __MATH1+1
	BNE __ZAP_REL_ELSE_TMP_8
	LDA __MATH0
	CMP __MATH1
	BEQ __ZAP_then_7
__ZAP_REL_ELSE_TMP_8:
	JMP __ZAP_else_5
__ZAP_then_7:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 42:         result = result | 1
	LDA _RESULT
	ORA #$01
	STA _RESULT
	JMP __ZAP_endif_6
__ZAP_else_5:
__ZAP_endif_6:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 46:     sptr = @sarr
	LDA #<_SARR
	LDX #>_SARR
	STA _MAIN$SPTR
	STX _MAIN$SPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 47:     sptr += 1
	LDA _MAIN$SPTR
	CLC
	ADC #$02
	STA _MAIN$SPTR
	BCC __ZAP_CARRY_ADD_PTR_9
	INC _MAIN$SPTR+1
__ZAP_CARRY_ADD_PTR_9:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 48:     tmp = sptr^.x + sptr^.y
	LDY #$00
	LDA (_MAIN$SPTR),Y
	STA _MAIN$TMP
	LDY #$01
	LDA (_MAIN$SPTR),Y
	CLC
	ADC _MAIN$TMP
	STA _MAIN$TMP
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 49:     if tmp == 7
	LDA _MAIN$TMP
	CMP #$07
	BNE __ZAP_else_10
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 50:         result = result | 2
	LDA _RESULT
	ORA #$02
	STA _RESULT
	JMP __ZAP_endif_11
__ZAP_else_10:
__ZAP_endif_11:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 54:     sptr = @sarr
	LDA #<_SARR
	LDX #>_SARR
	STA _MAIN$SPTR
	STX _MAIN$SPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 55:     sptr += 2
	LDA _MAIN$SPTR
	CLC
	ADC #$04
	STA _MAIN$SPTR
	BCC __ZAP_CARRY_ADD_PTR_13
	INC _MAIN$SPTR+1
__ZAP_CARRY_ADD_PTR_13:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 56:     if sptr^.x == 5
	LDY #$00
	LDA (_MAIN$SPTR),Y
	CMP #$05
	BNE __ZAP_else_14
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 57:         result = result | 4
	LDA _RESULT
	ORA #$04
	STA _RESULT
	JMP __ZAP_endif_15
__ZAP_else_14:
__ZAP_endif_15:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 61:     wptr = @earr
	LDA #<_EARR
	LDX #>_EARR
	STA _MAIN$WPTR
	STX _MAIN$WPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 62:     wptr += 1
	LDA _MAIN$WPTR
	CLC
	ADC #$02
	STA _MAIN$WPTR
	BCC __ZAP_CARRY_ADD_PTR_17
	INC _MAIN$WPTR+1
__ZAP_CARRY_ADD_PTR_17:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 63:     if wptr^ == 200
	LDY #1
	LDA (_MAIN$WPTR),Y
	TAX
	LDA (_MAIN$WPTR)
	CMP #$C8
	BNE __ZAP_REL_ELSE_TMP_21
	CPX #$00
	BEQ __ZAP_then_20
__ZAP_REL_ELSE_TMP_21:
	JMP __ZAP_else_18
__ZAP_then_20:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 64:         result = result | 8
	LDA _RESULT
	ORA #$08
	STA _RESULT
	JMP __ZAP_endif_19
__ZAP_else_18:
__ZAP_endif_19:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 68:     bptr = @barr[2]
	LDA #<(_BARR+2)
	LDX #>(_BARR+2)
	STA _MAIN$BPTR
	STX _MAIN$BPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 69:     if bptr^ == $CC
	LDA (_MAIN$BPTR)
	CMP #$CC
	BNE __ZAP_else_22
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 70:         result = result | 16
	LDA _RESULT
	ORA #$10
	STA _RESULT
	JMP __ZAP_endif_23
__ZAP_else_22:
__ZAP_endif_23:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 74:     wptr = @warr[2]
	LDA #<(_WARR+4)
	LDX #>(_WARR+4)
	STA _MAIN$WPTR
	STX _MAIN$WPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 75:     if wptr^ == $3333
	LDY #1
	LDA (_MAIN$WPTR),Y
	TAX
	LDA (_MAIN$WPTR)
	CMP #$33
	BNE __ZAP_REL_ELSE_TMP_28
	CPX #$33
	BEQ __ZAP_then_27
__ZAP_REL_ELSE_TMP_28:
	JMP __ZAP_else_25
__ZAP_then_27:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 76:         result = result | 32
	LDA _RESULT
	ORA #$20
	STA _RESULT
	JMP __ZAP_endif_26
__ZAP_else_25:
__ZAP_endif_26:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 80:     lptr = @larr[2]
	LDA #<(_LARR+8)
	LDX #>(_LARR+8)
	STA _MAIN$LPTR
	STX _MAIN$LPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 81:     if lptr^ == $33333333
	LDA #$33
	STA __MATH0
	LDA #$33
	STA __MATH0+1
	LDA #$33
	STA __MATH0+2
	LDA #$33
	STA __MATH0+3
	LDA __MATH0
	STA __MATH1
	LDA __MATH0+1
	STA __MATH1+1
	LDA __MATH0+2
	STA __MATH1+2
	LDA __MATH0+3
	STA __MATH1+3
	LDA (_MAIN$LPTR)
	STA __MATH0
	LDY #1
	LDA (_MAIN$LPTR),Y
	STA __MATH0+1
	LDY #2
	LDA (_MAIN$LPTR),Y
	STA __MATH0+2
	LDY #3
	LDA (_MAIN$LPTR),Y
	STA __MATH0+3
	LDA __MATH0+3
	CMP __MATH1+3
	BNE __ZAP_REL_ELSE_TMP_32
	LDA __MATH0+2
	CMP __MATH1+2
	BNE __ZAP_REL_ELSE_TMP_32
	LDA __MATH0+1
	CMP __MATH1+1
	BNE __ZAP_REL_ELSE_TMP_32
	LDA __MATH0
	CMP __MATH1
	BEQ __ZAP_then_31
__ZAP_REL_ELSE_TMP_32:
	JMP __ZAP_else_29
__ZAP_then_31:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 82:         result = result | 64
	LDA _RESULT
	ORA #$40
	STA _RESULT
	JMP __ZAP_endif_30
__ZAP_else_29:
__ZAP_endif_30:
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 86:     sptr = @sarr[1]
	LDA #<(_SARR+2)
	LDX #>(_SARR+2)
	STA _MAIN$SPTR
	STX _MAIN$SPTR+1
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 87:     if sptr^.y == 4
	LDY #$01
	LDA (_MAIN$SPTR),Y
	CMP #$04
	BNE __ZAP_else_33
; /home/dusan/src/ZAP-compiler/tests/pass/166-ptr-array-index/166-ptr-array-index.zap 88:         result = result | 128
	LDA _RESULT
	ORA #$80
	STA _RESULT
	JMP __ZAP_endif_34
__ZAP_else_33:
__ZAP_endif_34:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"


; ------------------------------
; Shared byte copy routine
; Inputs: __TMP0/__TMP0+1=src, __TMP2/__TMP2+1=dst, X=len (1..255), Y=0
; Clobbers: A, X, Y
; Note: length must fit in one page; longer copies stay inline
__COPY_BYTES:
	LDY #$00
	CPX #$00
	BEQ COPY_BYTES_DONE
COPY_BYTES_LOOP:
	LDA (__TMP0),Y
	STA (__TMP2),Y
	INY
	DEX
	BNE COPY_BYTES_LOOP
COPY_BYTES_DONE:
	RTS
; ---------------------------------------------------------------------------
; Constant Data
__ARRAY_DATA_1:
	.byte $AA, $BB, $CC
__ARRAY_DATA_2:
	.word $1111, $2222, $3333
__ARRAY_DATA_3:
	.byte $11, $11, $11, $11, $22, $22, $22, $22, $33, $33, $33, $33
__ARRAY_DATA_4:
	.word $0064, $00C8, $012C
; End of file