; Generated by Zap Compiler
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\005-if-statement\005-if-statement.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\005-if-statement\005-if-statement_default.s
; ==============================

.DEBUGINFO +  ; Enable debug information for symbol names

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2

; Fixed-address variables
_RESULT = $9C40


.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\005-if-statement\005-if-statement.zap 1: byte result @40000 = 0
	STZ _RESULT

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\005-if-statement\005-if-statement.zap 3: proc main()
; -- Procedure MAIN --
MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\005-if-statement\005-if-statement.zap 7:     result = 0
	LDA #0
	STA _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\005-if-statement\005-if-statement.zap 8:     while result == 0
while_1:
	LDA _RESULT
	LDX #0
	CMP #$00
	BNE REL_ELSE_TMP_4
	BEQ while_body_3
REL_ELSE_TMP_4:
	JMP endwhile_2
while_body_3:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\005-if-statement\005-if-statement.zap 9:         result = 1
	LDA #1
	STA _RESULT
	JMP while_1
endwhile_2:
	RTS

.segment "CODE"
__END:
.export __END

; End of file