; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -O1 tests/pass/231-word-unary/231-word-unary.zap -o tests/pass/231-word-unary/231-word-unary_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_3
__MATH1                 = __LVSLOT_4
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_3:	.res 4
__LVSLOT_4:	.res 4
; Word variables
; ZP usage: 10 of 256 bytes ($00-$09), 246 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 12: byte result @$0200 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
_MAIN$Y                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 19:     x = 100
	LDA #$64
	STA _MAIN$X
	STZ _MAIN$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 20:     y = -x
	LDX _MAIN$X+1
	STA __MATH0
	TXA
	STA __MATH0+1
	JSR NEG16
	LDA __MATH0
	LDX __MATH0+1
	STA _MAIN$Y
	STX _MAIN$Y+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 21:     if y == $FF9C
	CMP #$9C
	BNE __ZAP_else_1
	CPX #$FF
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 22:         result = result + 1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 26:     x = 1
	LDA #$01
	STA _MAIN$X
	STZ _MAIN$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 27:     y = -x
	LDX _MAIN$X+1
	STA __MATH0
	TXA
	STA __MATH0+1
	JSR NEG16
	LDA __MATH0
	LDX __MATH0+1
	STA _MAIN$Y
	STX _MAIN$Y+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 28:     if y == $FFFF
	CMP #$FF
	BNE __ZAP_else_5
	CPX #$FF
	BNE __ZAP_else_5
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 29:         result = result + 1
	INC _RESULT
__ZAP_else_5:
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 33:     x = 0
	STZ _MAIN$X
	STZ _MAIN$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 34:     y = -x
	LDA _MAIN$X
	LDX _MAIN$X+1
	STA __MATH0
	TXA
	STA __MATH0+1
	JSR NEG16
	LDA __MATH0
	LDX __MATH0+1
	STA _MAIN$Y
	STX _MAIN$Y+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 35:     if y == 0
	ORA _MAIN$Y+1
	BNE __ZAP_else_9
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 36:         result = result + 1
	INC _RESULT
__ZAP_else_9:
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 40:     x = $1234
	LDA #$34
	STA _MAIN$X
	LDA #$12
	STA _MAIN$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 41:     y = ~x
	LDA _MAIN$X
	EOR #$FF
	STA __MATH0
	LDA _MAIN$X+1
	EOR #$FF
	STA __MATH0+1
	LDA __MATH0
	LDX __MATH0+1
	STA _MAIN$Y
	STX _MAIN$Y+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 42:     if y == $EDCB
	CMP #$CB
	BNE __ZAP_else_12
	CPX #$ED
	BNE __ZAP_else_12
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 43:         result = result + 1
	INC _RESULT
__ZAP_else_12:
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 47:     x = $ABCD
	LDA #$CD
	STA _MAIN$X
	LDA #$AB
	STA _MAIN$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 48:     y = x + (-x)
	LDA _MAIN$X
	LDX _MAIN$X+1
	STA __MATH0
	TXA
	STA __MATH0+1
	JSR NEG16
	LDA _MAIN$X
	LDX _MAIN$X+1
	JSR __ADD16_AX
	LDA __MATH0
	LDX __MATH0+1
	STA _MAIN$Y
	STX _MAIN$Y+1
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 49:     if y == 0
	ORA _MAIN$Y+1
	BNE __ZAP_else_16
; /home/dusan/src/ZAP-compiler/tests/pass/231-word-unary/231-word-unary.zap 50:         result = result + 1
	INC _RESULT
__ZAP_else_16:
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; __ADD16_AX: right operand (word) in A/X
__ADD16_AX:
	STA __MATH1
	STX __MATH1+1
; __ADD16: 16-bit addition (accumulator style)
; Input: __MATH0 low word (left operand), __MATH1 low word (right operand)
; Output: __MATH0=sum (32-bit, high word cleared)
__ADD16:
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	RTS
NEG16:
	SEC
	LDA __MATH0
	EOR #$FF
	ADC #$00
	STA __MATH0
	LDA __MATH0+1
	EOR #$FF
	ADC #$00
	STA __MATH0+1
	RTS