; Generated by Zap Compiler
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/003-pointers/003-pointers.zap -o tests/pass/003-pointers/003-pointers-6502.s
; ------------------------------

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2

; Fixed-address variables
_PTR12 = $00A0
_PTR13 = $0086
_PTR22 = $00A2
_PTR23 = $008C
_DLIST = $0230

; Pointer variables
_PTR24:	.res 2
_PTR25:	.res 2

.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START
; /home/dusan/src/ZAP-compiler/tests/pass/003-pointers/003-pointers.zap 6: byte ^ptr13 @$86 = %101 ; $84, $85
	LDA #$05
	STA _PTR13
	LDA #0
	STA _PTR13+1
; /home/dusan/src/ZAP-compiler/tests/pass/003-pointers/003-pointers.zap 10: word ^ptr23 @$8c = 513  ; $8a, $8b
	LDA #$01
	STA _PTR23
	LDA #$02
	STA _PTR23+1
; /home/dusan/src/ZAP-compiler/tests/pass/003-pointers/003-pointers.zap 12: word ^ptr24 = 'a''b'    ; $8c, $8d
	LDA #$61
	STA _PTR24
	LDA #$62
	STA _PTR24+1
; /home/dusan/src/ZAP-compiler/tests/pass/003-pointers/003-pointers.zap 16: byte ^ptr25 = DLIST     ; $8e, $8f
	LDA _DLIST
	LDX _DLIST+1
	STA _PTR25
	STX _PTR25+1

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; /home/dusan/src/ZAP-compiler/tests/pass/003-pointers/003-pointers.zap 19: proc main()
; -- Procedure MAIN --
MAIN:
	RTS

.segment "CODE"
__END:
.export __END

; End of file