; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_VALUE                  = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 2
; Pointer variables
; Byte variables
; ZP usage: 3 of 256 bytes ($00-$02), 253 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 1: byte value @40000 = 0
	LDA #$00
	STA _VALUE
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$TARGET            = __LVSLOT_1
_MAIN$PTR               = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 4:     byte target = 42
	LDA #$2A
	STA _MAIN$TARGET
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 5:     byte ^ptr = @value
	LDA #<$9C40
	LDX #>$9C40
	STA _MAIN$PTR
	STX _MAIN$PTR+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 6:     ptr^ = target    
	LDA _MAIN$TARGET
	LDY #$00
	STA (_MAIN$PTR),Y
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file