; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/004-byte-pointer//004-byte-pointer.zap -o tests/pass/004-byte-pointer//004-byte-pointer_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_VALUE = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 2
; Pointer variables
; Byte variables
; ZP usage: 3 of 256 bytes ($00-$02), 253 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 1: byte value @40000 = 0
	STZ _VALUE
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_TARGET = __LVSLOT_1
_MAIN_PTR = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 4:     byte target = 42
	LDA #$2A
	STA _MAIN_TARGET
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 5:     byte ^ptr = @value
	LDA #<$9C40
	LDX #>$9C40
	STA _MAIN_PTR
	STX _MAIN_PTR+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-byte-pointer\004-byte-pointer.zap 6:     ptr^ = target    
	LDA _MAIN_TARGET
	STA (_MAIN_PTR)
	RTS


.segment "CODE"
; End of file