; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py tests/pass/043-functions-basic/043-functions-basic.zap -o tests/pass/043-functions-basic/043-functions-basic_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/043-functions-basic/043-functions-basic.zap 2: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Function ADD2 --
_ADD2:
_ADD2$A                 = __LVSLOT_1
_ADD2$B                 = __LVSLOT_2
	STA _ADD2$A
	STX _ADD2$B
; /home/dusan/src/ZAP-compiler/tests/pass/043-functions-basic/043-functions-basic.zap 6:     if a > 5 
	LDA _ADD2$A
	CMP #$05
	BEQ __ZAP_REL_ELSE_TMP_4
	BCS __ZAP_then_3
__ZAP_REL_ELSE_TMP_4:
	JMP __ZAP_else_1
__ZAP_then_3:
; /home/dusan/src/ZAP-compiler/tests/pass/043-functions-basic/043-functions-basic.zap 7:         return a
	LDA _ADD2$A
	RTS
	JMP __ZAP_endif_2
__ZAP_else_1:
__ZAP_endif_2:
; /home/dusan/src/ZAP-compiler/tests/pass/043-functions-basic/043-functions-basic.zap 10:     return a + b
	LDA _ADD2$A
	CLC
	ADC _ADD2$B
	RTS


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/043-functions-basic/043-functions-basic.zap 13: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/043-functions-basic/043-functions-basic.zap 14:     result = add2(2, 4)
	LDA #$02
	LDX #$04
	JSR _ADD2
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file