; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py tests/pass/070-global-local-scope/070-global-local-scope.zap -o tests/pass/070-global-local-scope/070-global-local-scope_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
_VALUE:	.res 1
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/070-global-local-scope/070-global-local-scope.zap 1: byte value = 5
	LDA #$05
	STA _VALUE
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/070-global-local-scope/070-global-local-scope.zap 2: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/070-global-local-scope/070-global-local-scope.zap 4: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$VALUE             = __LVSLOT_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/070-global-local-scope/070-global-local-scope.zap 5:     byte value = 2
	LDA #$02
	STA _MAIN$VALUE
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/070-global-local-scope/070-global-local-scope.zap 6:     result = value
	LDA _MAIN$VALUE
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file