; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\070-global-local-scope\070-global-local-scope.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\070-global-local-scope\070-global-local-scope_6502_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
_VALUE:	.res 1
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\070-global-local-scope\070-global-local-scope.zap 1: byte value = 5
	LDA #$05
	STA _VALUE
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\070-global-local-scope\070-global-local-scope.zap 2: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$VALUE             = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\070-global-local-scope\070-global-local-scope.zap 5:     byte value = 2
	LDA #$02
	STA _MAIN$VALUE
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\070-global-local-scope\070-global-local-scope.zap 6:     result = value
	STA _RESULT
	RTS


.segment "CODE"
; End of file