; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -6502 tests/pass/214-word-target-byte-add/214-word-target-byte-add.zap -o tests/pass/214-word-target-byte-add/214-word-target-byte-add_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT_LO              = $0200
_RESULT_HI              = $0201
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
; Byte variables
; Word variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/214-word-target-byte-add/214-word-target-byte-add.zap 8: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$W                 = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/214-word-target-byte-add/214-word-target-byte-add.zap 12:     a = 200
	LDA #$C8
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/214-word-target-byte-add/214-word-target-byte-add.zap 13:     b = 100
	LDA #$64
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/214-word-target-byte-add/214-word-target-byte-add.zap 14:     w = a + b       ; WORD target -> 16-bit ADD -> 300 = $012C
	LDA _MAIN$A
	CLC
	ADC _MAIN$B
	STA _MAIN$W
	LDA #$00
	ADC #$00
	STA _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/214-word-target-byte-add/214-word-target-byte-add.zap 15:     result_lo = low(w)
	LDA _MAIN$W
	STA _RESULT_LO
; /home/dusan/src/ZAP-compiler/tests/pass/214-word-target-byte-add/214-word-target-byte-add.zap 16:     result_hi = high(w)
	LDA _MAIN$W+1
	STA _RESULT_HI
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file