; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py tests/pass/083-integer-literals/083-integer-literals.zap -o tests/pass/083-integer-literals/083-integer-literals_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_4
__MATH1                 = __LVSLOT_5
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 4
; Byte variables
; ZP usage: 10 of 256 bytes ($00-$09), 246 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/083-integer-literals/083-integer-literals.zap 3: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/083-integer-literals/083-integer-literals.zap 5: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$C                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/083-integer-literals/083-integer-literals.zap 6:     byte a = 10
	LDA #$0A
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/083-integer-literals/083-integer-literals.zap 7:     byte b = 0x0A
	LDA #$0A
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/083-integer-literals/083-integer-literals.zap 8:     byte c = a + b + 'A' + $10 + 0b00000010 ; 10+10+65+16+2=103
	LDA _MAIN$A
	CLC
	ADC _MAIN$B
	STA __MATH0
	LDA #$41
	STA __MATH1
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA #$10
	STA __MATH1
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA #$02
	STA __MATH1
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0
	LDX #$00
	STA _MAIN$C
; /home/dusan/src/ZAP-compiler/tests/pass/083-integer-literals/083-integer-literals.zap 9:     result = c
	LDA _MAIN$C
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file