; Generated by Zap Compiler 0.9.4
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap -o /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Pointer variables
_LPTR:	.res 2
; ZP usage: 2 of 256 bytes ($00-$01), 254 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Struct variables (BSS)
_SV:	.res 2


.segment "CODE"
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 12: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 35: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 37:     if SIZEOF(Small) == 2
	LDA #$02
	LDX #$00
	CMP #$02
	BNE __ZAP_REL_ELSE_TMP_4
	CPX #$00
	BEQ __ZAP_then_3
__ZAP_REL_ELSE_TMP_4:
	JMP __ZAP_else_1
__ZAP_then_3:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 38:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
__ZAP_endif_2:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 42:     if SIZEOF(Large) == 5
	LDA #$05
	LDX #$00
	CMP #$05
	BNE __ZAP_REL_ELSE_TMP_8
	CPX #$00
	BEQ __ZAP_then_7
__ZAP_REL_ELSE_TMP_8:
	JMP __ZAP_else_5
__ZAP_then_7:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 43:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_6
__ZAP_else_5:
__ZAP_endif_6:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 47:     if SIZEOF(sv) == 2
	LDA #$02
	LDX #$00
	CMP #$02
	BNE __ZAP_REL_ELSE_TMP_12
	CPX #$00
	BEQ __ZAP_then_11
__ZAP_REL_ELSE_TMP_12:
	JMP __ZAP_else_9
__ZAP_then_11:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 48:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_10
__ZAP_else_9:
__ZAP_endif_10:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 52:     if SIZEOF(lptr) == 5
	LDA #$05
	LDX #$00
	CMP #$05
	BNE __ZAP_REL_ELSE_TMP_16
	CPX #$00
	BEQ __ZAP_then_15
__ZAP_REL_ELSE_TMP_16:
	JMP __ZAP_else_13
__ZAP_then_15:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 53:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_14
__ZAP_else_13:
__ZAP_endif_14:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 57:     if SIZEOF(WithLong) == 6
	LDA #$06
	LDX #$00
	CMP #$06
	BNE __ZAP_REL_ELSE_TMP_20
	CPX #$00
	BEQ __ZAP_then_19
__ZAP_REL_ELSE_TMP_20:
	JMP __ZAP_else_17
__ZAP_then_19:
; /home/dusan/src/ZAP-compiler/tests/pass/159-sizeof/159-sizeof.zap 58:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_18
__ZAP_else_17:
__ZAP_endif_18:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file