; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/105-switch//105-switch.zap -o tests/pass/105-switch//105-switch_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 1: word result @40000 = 42
	LDA #$2A
	STA _RESULT
	STZ _RESULT+1
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_I = __LVSLOT_1
_MAIN_FOR_END_1 = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 6:     for i = 0 to 10
	STZ _MAIN_I
	LDA #$0A
	STA _MAIN_FOR_END_1
__ZAP_while_1:
	LDA _MAIN_I
	CMP _MAIN_FOR_END_1
	BCS __ZAP_endwhile_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 7:         switch i
	LDA _MAIN_I
	CMP #$01
	BEQ __ZAP_case_5
	LDA _MAIN_I
	CMP #$05
	BEQ __ZAP_case_6
	LDA _MAIN_I
	CMP #$04
	BEQ __ZAP_case_6
	LDA _MAIN_I
	CMP #$09
	BEQ __ZAP_case_7
	JMP __ZAP_case_8
__ZAP_case_5:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 9:                 result = result - 10
	LDA _RESULT
	SEC
	SBC #$0A
	STA _RESULT
	LDA _RESULT+1
	SBC #$00
	STA _RESULT+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 10:                 break
	JMP __ZAP_endswitch_4
__ZAP_case_6:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 14:                 result = result + 2
	INC _RESULT
	BNE __ZAP_INC_WORD_13
	INC _RESULT+1
__ZAP_INC_WORD_13:
	INC _RESULT
	BNE __ZAP_INC_WORD_14
	INC _RESULT+1
__ZAP_INC_WORD_14:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 15:                 break
	JMP __ZAP_endswitch_4
__ZAP_case_7:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 18:                 result = result + 3
	INC _RESULT
	BNE __ZAP_INC_WORD_15
	INC _RESULT+1
__ZAP_INC_WORD_15:
	INC _RESULT
	BNE __ZAP_INC_WORD_16
	INC _RESULT+1
__ZAP_INC_WORD_16:
	INC _RESULT
	BNE __ZAP_INC_WORD_17
	INC _RESULT+1
__ZAP_INC_WORD_17:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 19:                 break       
	JMP __ZAP_endswitch_4
__ZAP_case_8:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 22:                 result = result + 1
	INC _RESULT
	BNE __ZAP_INC_WORD_18
	INC _RESULT+1
__ZAP_INC_WORD_18:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\105-switch\105-switch.zap 23:                 break
__ZAP_endswitch_4:
	INC _MAIN_I
	JMP __ZAP_while_1
__ZAP_endwhile_2:
	RTS


.segment "CODE"
; End of file