; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -6502 tests/pass/205-peek-poke/205-peek-poke.zap -o tests/pass/205-peek-poke/205-peek-poke_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_2
__MATH1                 = __LVSLOT_3
; Shared slots (for aliased locals)
__LVSLOT_2:	.res 4
__LVSLOT_3:	.res 4
; Byte variables
_RESULT:	.res 1
_VAL:	.res 1
_BADDR:	.res 1
; Word variables
_ADDR:	.res 2
_WVAL:	.res 2
; Long variables
_LADDR:	.res 4
_LVAL:	.res 4
; ZP usage: 23 of 256 bytes ($00-$16), 233 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 4: byte val = $42
	LDA #$42
	STA _VAL
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 5: word addr = $D400
	LDA #$00
	STA _ADDR
	LDA #$D4
	STA _ADDR+1
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 6: byte baddr = $80
	LDA #$80
	STA _BADDR
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 7: long laddr = $12345678
	LDA #$78
	STA _LADDR
	LDA #$56
	STA _LADDR+1
	LDA #$34
	STA _LADDR+2
	LDA #$12
	STA _LADDR+3
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 8: word wval = $1234
	LDA #$34
	STA _WVAL
	LDA #$12
	STA _WVAL+1
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 9: long lval = $12345678
	LDA #$78
	STA _LVAL
	LDA #$56
	STA _LVAL+1
	LDA #$34
	STA _LVAL+2
	LDA #$12
	STA _LVAL+3
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 11: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 13:     result = PEEK(baddr)
	LDA _BADDR
	STA __MATH0
	STX __MATH0+1
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 16:     result = PEEK(addr)
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 19:     result = PEEK($D400)
	LDA $D400
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 20:     result = PEEK($80)
	LDA $0080
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 23:     result = PEEK(addr + 1)
	LDA _ADDR
	STA __MATH0
	LDA #$01
	STA __MATH1
	INC __MATH0
	LDA __MATH0
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 24:     result = PEEK(baddr + 2)
	LDA _BADDR
	CLC
	ADC #$02
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 25:     result = PEEK($D400 + 3)
	LDA $D403
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 28:     result = PEEK(LOWW(laddr))
	LDA _LADDR
	LDX _LADDR+1
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 29:     result = PEEK(HIGHW(laddr))
	LDA _LADDR+2
	LDX _LADDR+3
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 32:     POKE($D400, $42)
	LDA #$42
	STA $D400
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 33:     POKE($D400, val)
	LDA _VAL
	LDX #$00
	STA $D400
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 34:     POKE(addr, val)
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _VAL
	LDX #$00
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 35:     POKE(baddr, val)
	LDA _BADDR
	LDX #$00
	STA __MATH0
	STX __MATH0+1
	LDA _VAL
	LDX #$00
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 38:     POKE(addr + 1, val)
	LDA _ADDR
	LDX _ADDR+1
	STX __MATH0+1
	CLC
	ADC #$01
	BCC __ZAP_ADD16C_NC_1
	INC __MATH0+1
__ZAP_ADD16C_NC_1:
	LDX __MATH0+1
	LDA _VAL
	LDX #$00
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 39:     POKE(baddr + 2, val)
	LDA _BADDR
	CLC
	ADC #$02
	LDA _VAL
	LDX #$00
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 40:     POKE($D400 + 3, $FF)
	LDA #$FF
	STA $D403
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 43:     POKE(addr, LOW(wval))
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _WVAL
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 44:     POKE(addr, HIGH(wval))
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _WVAL+1
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 47:     POKE(addr, LOW(LOWW(lval)))
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _LVAL
	LDX _LVAL+1
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 48:     POKE(addr, HIGH(LOWW(lval)))
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _LVAL
	LDX _LVAL+1
	TXA
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 49:     POKE(addr, LOW(HIGHW(lval)))
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _LVAL+2
	LDX _LVAL+3
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 50:     POKE(addr, HIGH(HIGHW(lval)))
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _LVAL+2
	LDX _LVAL+3
	TXA
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 53:     POKE(addr, val + 1)
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA _VAL
	CLC
	ADC #$01
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 54:     POKE(addr, $42 + $10)
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDA #$52
	LDY #$00
	STA (__MATH0),Y
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 57:     result = PEEK(addr) + 1
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
	LDA #$01
	CLC
	ADC _RESULT
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/205-peek-poke/205-peek-poke.zap 58:     result = PEEK(addr) + val
	LDA _ADDR
	LDX _ADDR+1
	STA __MATH0
	STX __MATH0+1
	LDY #$00
	LDA (__MATH0),Y
	LDX #$00
	STA _RESULT
	LDA _VAL
	CLC
	ADC _RESULT
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file