; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/164-struct-array-pow2-index//164-struct-array-pow2-index.zap -o tests/pass/164-struct-array-pow2-index//164-struct-array-pow2-index_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP0 = __LVSLOT_6
; Fixed-address variables
_ARR4 = $C350
_ARR8 = $C360
_ARR16 = $C378
_OUT0 = $9C40
_OUT1 = $9C41
_OUT2 = $9C42
_OUT3 = $9C43
_OUT4 = $9C44
_OUT5 = $9C45
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 2
__LVSLOT_6:	.res 2
; Byte variables
; Word variables
; ZP usage: 5 of 256 bytes ($00-$04), 251 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 45: byte out0 @40000 = 0
	STZ _OUT0
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 46: byte out1 @40001 = 0
	STZ _OUT1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 47: byte out2 @40002 = 0
	STZ _OUT2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 48: byte out3 @40003 = 0
	STZ _OUT3
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 49: byte out4 @40004 = 0
	STZ _OUT4
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 50: byte out5 @40005 = 0
	STZ _OUT5
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_I = __LVSLOT_1
_MAIN___SBM_1 = __LVSLOT_2
_MAIN___SBM_2 = __LVSLOT_2
_MAIN___SBM_3 = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 56:     arr4[0].a = $10
	LDA #$00
	TAX
	CLC
	ADC #<_ARR4
	STA __TMP0
	TXA
	ADC #>_ARR4
	STA __TMP0+1
	LDA #$10
	LDY #$00
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 57:     arr4[1].a = $20
	LDA #$04
	CLC
	ADC #<_ARR4
	STA __TMP0
	TXA
	ADC #>_ARR4
	STA __TMP0+1
	LDA #$20
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 58:     arr4[2].a = $30
	LDA #$08
	CLC
	ADC #<_ARR4
	STA __TMP0
	TXA
	ADC #>_ARR4
	STA __TMP0+1
	LDA #$30
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 59:     arr4[3].a = $40
	LDA #$0C
	CLC
	ADC #<_ARR4
	STA __TMP0
	TXA
	ADC #>_ARR4
	STA __TMP0+1
	LDA #$40
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 60:     i = 0
	STZ _MAIN_I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 61:     out0 = arr4[i].a    ; expect $10
	LDA _MAIN_I
	ASL A
	ASL A
	CLC
	ADC #<_ARR4
	STA __TMP0
	TXA
	ADC #>_ARR4
	STA __TMP0+1
	LDA __TMP0
	STA _MAIN___SBM_1
	LDA __TMP0+1
	STA _MAIN___SBM_1+1
	LDA (__TMP0),Y
	STA _OUT0
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 62:     i = 2
	LDA #$02
	STA _MAIN_I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 63:     out1 = arr4[i].a    ; expect $30
	ASL A
	ASL A
	CLC
	ADC #<_ARR4
	STA __TMP0
	TXA
	ADC #>_ARR4
	STA __TMP0+1
	LDA __TMP0
	STA _MAIN___SBM_1
	LDA __TMP0+1
	STA _MAIN___SBM_1+1
	LDA (__TMP0),Y
	STA _OUT1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 66:     arr8[0].a = $AA
	TXA
	CLC
	ADC #<_ARR8
	STA __TMP0
	TXA
	ADC #>_ARR8
	STA __TMP0+1
	LDA #$AA
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 67:     arr8[1].a = $BB
	LDA #$08
	CLC
	ADC #<_ARR8
	STA __TMP0
	TXA
	ADC #>_ARR8
	STA __TMP0+1
	LDA #$BB
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 68:     arr8[2].a = $CC
	LDA #$10
	CLC
	ADC #<_ARR8
	STA __TMP0
	TXA
	ADC #>_ARR8
	STA __TMP0+1
	LDA #$CC
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 69:     i = 1
	LDA #$01
	STA _MAIN_I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 70:     out2 = arr8[i].a    ; expect $BB
	ASL A
	ASL A
	ASL A
	CLC
	ADC #<_ARR8
	STA __TMP0
	TXA
	ADC #>_ARR8
	STA __TMP0+1
	LDA __TMP0
	STA _MAIN___SBM_2
	LDA __TMP0+1
	STA _MAIN___SBM_2+1
	LDA (__TMP0),Y
	STA _OUT2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 71:     i = 2
	LDA #$02
	STA _MAIN_I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 72:     out3 = arr8[i].a    ; expect $CC
	ASL A
	ASL A
	ASL A
	CLC
	ADC #<_ARR8
	STA __TMP0
	TXA
	ADC #>_ARR8
	STA __TMP0+1
	LDA __TMP0
	STA _MAIN___SBM_2
	LDA __TMP0+1
	STA _MAIN___SBM_2+1
	LDA (__TMP0),Y
	STA _OUT3
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 75:     arr16[0].f0 = $11
	TXA
	CLC
	ADC #<_ARR16
	STA __TMP0
	TXA
	ADC #>_ARR16
	STA __TMP0+1
	LDA #$11
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 76:     arr16[1].f0 = $22
	LDA #$10
	CLC
	ADC #<_ARR16
	STA __TMP0
	TXA
	ADC #>_ARR16
	STA __TMP0+1
	LDA #$22
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 77:     i = 0
	STZ _MAIN_I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 78:     out4 = arr16[i].f0  ; expect $11
	LDA _MAIN_I
	ASL A
	ASL A
	ASL A
	ASL A
	CLC
	ADC #<_ARR16
	STA __TMP0
	TXA
	ADC #>_ARR16
	STA __TMP0+1
	LDA __TMP0
	STA _MAIN___SBM_3
	LDA __TMP0+1
	STA _MAIN___SBM_3+1
	LDA (__TMP0),Y
	STA _OUT4
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 79:     i = 1
	LDA #$01
	STA _MAIN_I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\164-struct-array-pow2-index\164-struct-array-pow2-index.zap 80:     out5 = arr16[i].f0  ; expect $22
	ASL A
	ASL A
	ASL A
	ASL A
	CLC
	ADC #<_ARR16
	STA __TMP0
	TXA
	ADC #>_ARR16
	STA __TMP0+1
	LDA __TMP0
	STA _MAIN___SBM_3
	LDA __TMP0+1
	STA _MAIN___SBM_3+1
	LDA (__TMP0),Y
	STA _OUT5
	RTS


.segment "CODE"
; End of file