; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\057-struct-basic\057-struct-basic.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\057-struct-basic\057-struct-basic_6502_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 2
; Struct variables (BSS)


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\057-struct-basic\057-struct-basic.zap 6: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$P                 = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\057-struct-basic\057-struct-basic.zap 10:     p.x = 75
	LDA #$4B
	STA _MAIN$P
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\057-struct-basic\057-struct-basic.zap 11:     p.y = 25
	LDA #$19
	STA _MAIN$P+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\057-struct-basic\057-struct-basic.zap 12:     result = p.y
	STA _RESULT
	RTS


.segment "CODE"
; End of file