; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/057-struct-basic/057-struct-basic.zap -o tests/pass/057-struct-basic/057-struct-basic_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 2
; Struct variables (BSS)


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/057-struct-basic/057-struct-basic.zap 6: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$P                 = __LVSLOT_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/057-struct-basic/057-struct-basic.zap 10:     p.x = 75
	LDA #$4B
	STA _MAIN$P
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/057-struct-basic/057-struct-basic.zap 11:     p.y = 25
	LDA #$19
	STA _MAIN$P+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/057-struct-basic/057-struct-basic.zap 12:     result = p.y
	STA _RESULT
	RTS


.segment "CODE"
; End of file