; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -6502 -O1 tests/pass/008-if-statement/008-if-statement.zap -o tests/pass/008-if-statement/008-if-statement_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/008-if-statement/008-if-statement.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/008-if-statement/008-if-statement.zap 7:     result = 0
	LDA #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/008-if-statement/008-if-statement.zap 8:     while result == 0
__ZAP_while_1:
	LDA _RESULT
	BNE __ZAP_endwhile_2
; /home/dusan/src/ZAP-compiler/tests/pass/008-if-statement/008-if-statement.zap 9:         result = 1
	LDA #$01
	STA _RESULT
	JMP __ZAP_while_1
__ZAP_endwhile_2:
	RTS


.segment "CODE"
; End of file