; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -6502 -O1 tests/pass/082-identifiers-shadow/082-identifiers-shadow.zap -o tests/pass/082-identifiers-shadow/082-identifiers-shadow_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/082-identifiers-shadow/082-identifiers-shadow.zap 2: byte result @40000 = 1
	LDA #$01
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
	RTS


.segment "CODE"
; End of file