; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-word-pointers\006-word-pointers.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-word-pointers\006-word-pointers_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 2
; Word variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-word-pointers\006-word-pointers.zap 1: word result @40000 = 0
	STZ _RESULT
	STZ _RESULT+1
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$TARGET            = __LVSLOT_1
_MAIN$PTR               = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-word-pointers\006-word-pointers.zap 4:     word target = 3000
	LDA #$B8
	STA _MAIN$TARGET
	LDA #$0B
	STA _MAIN$TARGET+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-word-pointers\006-word-pointers.zap 5:     word ptr = 0
	STZ _MAIN$PTR
	STZ _MAIN$PTR+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-word-pointers\006-word-pointers.zap 6:     ptr = @target
	LDA #<_MAIN$TARGET
	LDX #>_MAIN$TARGET
	STA _MAIN$PTR
	STX _MAIN$PTR+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-word-pointers\006-word-pointers.zap 7:     result = target
	LDA _MAIN$TARGET
	LDX _MAIN$TARGET+1
	STA _RESULT
	STX _RESULT+1
	RTS


.segment "CODE"
; End of file