; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/034-inequality//034-inequality.zap -o tests/pass/034-inequality//034-inequality_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
; Byte variables
; Word variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_X = __LVSLOT_1
_MAIN_Y = __LVSLOT_2
_MAIN_X1 = __LVSLOT_3
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 4:     byte x = 30
	LDA #$1E
	STA _MAIN_X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 5:     byte y = 20
	LDA #$14
	STA _MAIN_Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 6:     word x1 = $1030
	LDA #$30
	STA _MAIN_X1
	LDA #$10
	STA _MAIN_X1+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 8:     if x != y 
	LDA _MAIN_X
	CMP _MAIN_Y
	BEQ __ZAP_else_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 9:         result = 1
	LDA #$01
	STA _RESULT
__ZAP_else_1:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 12:     if x1 != x 
	LDX _MAIN_X1+1
	BNE __ZAP_then_6
	LDA _MAIN_X1
	CMP _MAIN_X
	BEQ __ZAP_else_4
__ZAP_then_6:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\034-inequality\034-inequality.zap 13:         result = result + $10
	LDA _RESULT
	CLC
	ADC #$10
	STA _RESULT
__ZAP_else_4:
	RTS


.segment "CODE"
; End of file