; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_6
__TMP0                  = __LVSLOT_8
__TMP2                  = __LVSLOT_9
__TMP3                  = __LVSLOT_10
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_10:	.res 2
__LVSLOT_2:	.res 2
__LVSLOT_3:	.res 2
__LVSLOT_6:	.res 4
__LVSLOT_8:	.res 2
__LVSLOT_9:	.res 2
; Word variables
; ZP usage: 14 of 256 bytes ($00-$0D), 242 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 512
__LVSLOT_4:	.res 600
; Arrays (BSS)


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 6: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 8: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$FLAGS             = __LVSLOT_1
_MAIN$I                 = __LVSLOT_2
_MAIN$ARR               = __LVSLOT_4
_MAIN$PRIME             = __LVSLOT_2
_MAIN$FOR_END_1         = __LVSLOT_3
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 16:     for i = 0 to 512
	LDA #$00
	STA _MAIN$I
	STA _MAIN$I+1
	LDA #$00
	STA _MAIN$FOR_END_1
	LDA #$02
	STA _MAIN$FOR_END_1+1
	LDA #<_MAIN$FLAGS
	STA __TMP0
	LDA #>_MAIN$FLAGS
	STA __TMP0+1
	LDY #$00
	LDA #$00
__ZAP_while_1:
	LDX _MAIN$I+1
	CPX _MAIN$FOR_END_1+1
	BCC __ZAP_while_body_2
	BNE __ZAP_REL_ELSE_TMP_4
	LDA _MAIN$I
	CMP _MAIN$FOR_END_1
	BCC __ZAP_while_body_2
__ZAP_REL_ELSE_TMP_4:
	JMP __ZAP_endwhile_3
__ZAP_while_body_2:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 17:         flags[i] = 0
	STA (__TMP0),Y
	INC __TMP0
	BNE __ZAP_LSR_NC_5
	INC __TMP0+1
__ZAP_LSR_NC_5:
	INC _MAIN$I
	BNE __ZAP_INC_WORD_6
	INC _MAIN$I+1
__ZAP_INC_WORD_6:
	JMP __ZAP_while_1
__ZAP_endwhile_3:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 19:     i = 260
	LDA #$04
	STA _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 20:     flags[i] = 42
	LDA _MAIN$I
	CLC
	ADC #<_MAIN$FLAGS
	STA __TMP0
	LDA _MAIN$I+1
	ADC #>_MAIN$FLAGS
	STA __TMP0+1
	LDA #$2A
	LDY #$00
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 23:     i = 260
	LDA #$04
	STA _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 24:     if flags[i] == 42
	LDA _MAIN$I
	CLC
	ADC #<_MAIN$FLAGS
	STA __TMP0
	LDA _MAIN$I+1
	ADC #>_MAIN$FLAGS
	STA __TMP0+1
	LDY #$00
	LDA (__TMP0),Y
	CMP #$2A
	BNE __ZAP_else_7
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 25:         result += 1     ; +1
	INC _RESULT
	JMP __ZAP_endif_8
__ZAP_else_7:
__ZAP_endif_8:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 29:     i = 0
	LDA #$00
	STA _MAIN$I
	STA _MAIN$I+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 30:     if flags[i] == 0
	LDA _MAIN$I
	CLC
	ADC #<_MAIN$FLAGS
	STA __TMP0
	LDA _MAIN$I+1
	ADC #>_MAIN$FLAGS
	STA __TMP0+1
	LDY #$00
	LDA (__TMP0),Y
	BNE __ZAP_else_10
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 31:         result += 1     ; +2
	INC _RESULT
	JMP __ZAP_endif_11
__ZAP_else_10:
__ZAP_endif_11:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 36:     i = 300
	LDA #$2C
	STA _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 37:     flags[i] = 99
	LDA _MAIN$I
	CLC
	ADC #<_MAIN$FLAGS
	STA __TMP0
	LDA _MAIN$I+1
	ADC #>_MAIN$FLAGS
	STA __TMP0+1
	LDA #$63
	LDY #$00
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 39:     if flags[300] == 99
	LDA _MAIN$FLAGS+300
	CMP #$63
	BNE __ZAP_else_13
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 40:         result += 1     ; +3
	INC _RESULT
	JMP __ZAP_endif_14
__ZAP_else_13:
__ZAP_endif_14:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 44:     i = 150
	LDA #$96
	STA _MAIN$I
	LDA #$00
	STA _MAIN$I+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 45:     arr[i] = 1234
	LDA _MAIN$I
	LDX _MAIN$I+1
	STA __TMP3
	STX __TMP3+1
	ASL __TMP3
	ROL __TMP3+1
	LDA __TMP3
	LDX __TMP3+1
	CLC
	ADC #<_MAIN$ARR
	STA __TMP0
	TXA
	ADC #>_MAIN$ARR
	STA __TMP0+1
	LDA #$D2
	LDY #$00
	STA (__TMP0),Y
	LDY #$01
	LDA #$04
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 48:     if arr[150] == 1234
	LDA _MAIN$ARR+300
	LDX _MAIN$ARR+301
	CMP #$D2
	BNE __ZAP_REL_ELSE_TMP_19
	CPX #$04
	BEQ __ZAP_then_18
__ZAP_REL_ELSE_TMP_19:
	JMP __ZAP_else_16
__ZAP_then_18:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 49:         result += 1     ; +4
	INC _RESULT
	JMP __ZAP_endif_17
__ZAP_else_16:
__ZAP_endif_17:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 54:     i = 200
	LDA #$C8
	STA _MAIN$I
	LDA #$00
	STA _MAIN$I+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 55:     arr[i] = 5678
	LDA _MAIN$I
	LDX _MAIN$I+1
	STA __TMP3
	STX __TMP3+1
	ASL __TMP3
	ROL __TMP3+1
	LDA __TMP3
	LDX __TMP3+1
	CLC
	ADC #<_MAIN$ARR
	STA __TMP0
	TXA
	ADC #>_MAIN$ARR
	STA __TMP0+1
	LDA #$2E
	LDY #$00
	STA (__TMP0),Y
	LDY #$01
	LDA #$16
	STA (__TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 56:     if arr[200] == 5678
	LDA _MAIN$ARR+400
	LDX _MAIN$ARR+401
	CMP #$2E
	BNE __ZAP_REL_ELSE_TMP_23
	CPX #$16
	BEQ __ZAP_then_22
__ZAP_REL_ELSE_TMP_23:
	JMP __ZAP_else_20
__ZAP_then_22:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 57:         result += 1     ; +5
	INC _RESULT
	JMP __ZAP_endif_21
__ZAP_else_20:
__ZAP_endif_21:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 61:     i = 300
	LDA #$2C
	STA _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 62:     prime = i * 2 + 3
	LDA _MAIN$I
	LDX _MAIN$I+1
	STA __MATH0
	STX __MATH0+1
	ASL __MATH0
	ROL __MATH0+1
	LDA __MATH0
	LDX __MATH0+1
	STX __MATH0+1
	CLC
	ADC #$03
	BCC __ZAP_ADD16C_NC_24
	INC __MATH0+1
__ZAP_ADD16C_NC_24:
	LDX __MATH0+1
	STA _MAIN$PRIME
	STX _MAIN$PRIME+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 63:     if prime == 603
	LDA _MAIN$PRIME
	CMP #$5B
	BNE __ZAP_REL_ELSE_TMP_28
	LDX _MAIN$PRIME+1
	CPX #$02
	BEQ __ZAP_then_27
__ZAP_REL_ELSE_TMP_28:
	JMP __ZAP_else_25
__ZAP_then_27:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\204-word-index-array\204-word-index-array.zap 64:         result += 1     ; +6
	INC _RESULT
	JMP __ZAP_endif_26
__ZAP_else_25:
__ZAP_endif_26:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file