; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -6502 -O1 tests/pass/173-string-highbyte/173-string-highbyte.zap -o tests/pass/173-string-highbyte/173-string-highbyte_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_4
__MATH1                 = __LVSLOT_5
__TMP0                  = __LVSLOT_6
; Fixed-address variables
_GNAME                  = $9C4A
_OUT0                   = $9C40
_OUT1                   = $9C41
_OUT2                   = $9C42
_OUT3                   = $9C43
_OUT4                   = $9C44
_OUT5                   = $9C45
_OUT6                   = $9C46
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 1
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 2
; Pointer variables
; Byte variables
; ZP usage: 13 of 256 bytes ($00-$0C), 243 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 8: byte gname[4] @40010 = "C\x9B"  ; C $9B NUL
	LDA #$43
	STA _GNAME+0
	LDA #$9B
	STA _GNAME+1
	LDA #$00
	STA _GNAME+2
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 15: byte out0 @40000 = 0    ; cname[0] = 'A' = $41
	STA _OUT0
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 16: byte out1 @40001 = 0    ; cname[1] = 'B' = $42
	STA _OUT1
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 17: byte out2 @40002 = 0    ; cname[2] = $9B
	STA _OUT2
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 18: byte out3 @40003 = 0    ; gname[0] = 'C' = $43
	STA _OUT3
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 19: byte out4 @40004 = 0    ; gname[1] = $9B
	STA _OUT4
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 20: byte out5 @40005 = 0    ; string-literal arg: byte 0 = 'X' = $58
	STA _OUT5
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 21: byte out6 @40006 = 0    ; string-literal arg: byte 1 = $9B
	STA _OUT6
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Function BYTE_AT --
_BYTE_AT:
_BYTE_AT$PTR            = __LVSLOT_1
_BYTE_AT$IDX            = __LVSLOT_2
	STA _BYTE_AT$PTR
	STX _BYTE_AT$PTR+1
	STY _BYTE_AT$IDX
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 12:     return (ptr + idx)^
	STA __MATH0
	LDA _BYTE_AT$PTR+1
	STA __MATH0+1
	LDA _BYTE_AT$IDX
	LDX #$00
	JSR __ADD16_AX
	LDA __MATH0
	LDX __MATH0+1
	STA __TMP0
	STX __TMP0+1
	LDY #$00
	LDA (__TMP0),Y
	RTS


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 25:     out0 = cname[0]     ; expect $41
	LDA #$00
	TAY
	LDA __ARRAY_DATA_1,Y
	STA _OUT0
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 26:     out1 = cname[1]     ; expect $42
	LDA #$01
	TAY
	LDA __ARRAY_DATA_1,Y
	STA _OUT1
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 27:     out2 = cname[2]     ; expect $9B
	LDA #$02
	TAY
	LDA __ARRAY_DATA_1,Y
	STA _OUT2
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 30:     out3 = gname[0]     ; expect $43
	LDA _GNAME+0
	STA _OUT3
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 31:     out4 = gname[1]     ; expect $9B
	LDA _GNAME+1
	STA _OUT4
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 34:     out5 = byte_at("X\x9B", 0)   ; expect $58 ('X')
	LDA #<__STR_DATA_1
	LDX #>__STR_DATA_1
	PHA
	TXA
	PHA
	LDA #$00
	PHA
	PLA
	TAY
	PLA
	TAX
	PLA
	JSR _BYTE_AT
	STA _OUT5
; /home/dusan/src/ZAP-compiler/tests/pass/173-string-highbyte/173-string-highbyte.zap 35:     out6 = byte_at("X\x9B", 1)   ; expect $9B
	LDA #<__STR_DATA_1
	LDX #>__STR_DATA_1
	PHA
	TXA
	PHA
	LDA #$01
	PHA
	PLA
	TAY
	PLA
	TAX
	PLA
	JSR _BYTE_AT
	STA _OUT6
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; __ADD16_AX: right operand (word) in A/X
__ADD16_AX:
	STA __MATH1
	STX __MATH1+1
; __ADD16: 16-bit addition (accumulator style)
; Input: __MATH0 low word (left operand), __MATH1 low word (right operand)
; Output: __MATH0=sum (32-bit, high word cleared)
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	LDA #$00
	STA __MATH0+2
	STA __MATH0+3
	RTS
__STR_DATA_1:
	.byte "X", $9B, $00
__ARRAY_DATA_1:
	.byte $41, $42, $9B, $00
; End of file