; Generated by Zap Compiler
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word_6502.s
; ==============================

.DEBUGINFO +  ; Enable debug information for symbol names

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2
TMP2:	.res 4
TMP3:	.res 2

; Fixed-address variables
_RESULT = $9C40

; Word variables
_MAIN_SUM:	.res 2

.segment "BSS"
; Array variables (BSS)
_MAIN_ARR:	.res 6

.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap 1: word result @40000 = 0
	LDA #0
	STA _RESULT
	LDA #0
	STA _RESULT+1

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap 3: proc main()
; -- Procedure MAIN --
MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap 6:     arr[0] = 1000
	LDA #232
	LDX #3
	STA TMP2
	STX TMP2+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #0
	ASL A
	BCC NOCARRY_MULT_1
NOCARRY_MULT_1:
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap 7:     arr[1] = 2000
	LDA #208
	LDX #7
	STA TMP2
	STX TMP2+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #1
	ASL A
	BCC NOCARRY_MULT_2
NOCARRY_MULT_2:
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap 8:     arr[2] = 3000
	LDA #184
	LDX #11
	STA TMP2
	STX TMP2+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #2
	ASL A
	BCC NOCARRY_MULT_3
NOCARRY_MULT_3:
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
	INY
	LDA TMP2+1
	STA (TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap 9:     sum = arr[0] + arr[1] + arr[2]
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #0
	ASL A
	BCC NOCARRY_MULT_4
NOCARRY_MULT_4:
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	PHA
	INY
	LDA (TMP0),Y
	TAX
	PLA
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #1
	ASL A
	BCC NOCARRY_MULT_5
NOCARRY_MULT_5:
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	PHA
	INY
	LDA (TMP0),Y
	TAX
	PLA
	STA TMP3
	STX TMP3+1
	LDA TMP3
	CLC
	ADC TMP1
	TAY
	LDA TMP3+1
	ADC TMP1+1
	TAX
	TYA
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #2
	ASL A
	BCC NOCARRY_MULT_6
NOCARRY_MULT_6:
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	PHA
	INY
	LDA (TMP0),Y
	TAX
	PLA
	STA TMP3
	STX TMP3+1
	LDA TMP3
	CLC
	ADC TMP1
	TAY
	LDA TMP3+1
	ADC TMP1+1
	TAX
	TYA
	STA _MAIN_SUM
	STX _MAIN_SUM+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\006-arrays-1d-word\006-arrays-1d-word.zap 10:     result = sum
	LDA _MAIN_SUM
	LDX _MAIN_SUM+1
	STA _RESULT
	STX _RESULT+1
	RTS

.segment "CODE"
__END:
.export __END

; End of file