; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_13
__MATH1                 = __LVSLOT_14
__TMP0                  = __LVSLOT_15
__TMP1:	.res 2
__TMP2                  = __LVSLOT_16
__TMP3                  = __LVSLOT_17
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_10:	.res 2
__LVSLOT_11:	.res 2
__LVSLOT_13:	.res 4
__LVSLOT_14:	.res 4
__LVSLOT_15:	.res 2
__LVSLOT_16:	.res 2
__LVSLOT_17:	.res 2
__LVSLOT_3:	.res 1
__LVSLOT_4:	.res 1
__LVSLOT_5:	.res 1
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
__LVSLOT_9:	.res 2
; Pointer variables
; Byte variables
; Word variables
; ZP usage: 31 of 256 bytes ($00-$1E), 225 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 6
__LVSLOT_2:	.res 3
; Arrays (BSS)


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 7: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Function COUNT_BYTES --
_COUNT_BYTES:
_COUNT_BYTES$PTR        = __LVSLOT_10
	STA _COUNT_BYTES$PTR
	STX _COUNT_BYTES$PTR+1
_COUNT_BYTES$COUNT      = __LVSLOT_5
	STZ _COUNT_BYTES$COUNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 14:     while ptr^ != 0
__ZAP_while_1:
	LDA (_COUNT_BYTES$PTR)
	BEQ __ZAP_endwhile_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 15:         count += 1
	INC _COUNT_BYTES$COUNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 16:         ptr += 1        ; modifies __LVSLOT holding 'ptr'
	INC _COUNT_BYTES$PTR
	BNE __ZAP_while_1
	INC _COUNT_BYTES$PTR+1
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 18:     return count
	LDA _COUNT_BYTES$COUNT
	RTS


; ---------------------------------------------------------------------------
; -- Function WRITE_DATA --
_WRITE_DATA:
_WRITE_DATA$CHANNEL     = __LVSLOT_4
_WRITE_DATA$BUF         = __LVSLOT_11
_WRITE_DATA$LEN         = __LVSLOT_5
	STA _WRITE_DATA$CHANNEL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 25:     return buf^ + len
	LDA (_WRITE_DATA$BUF)
	STA __TMP1
	LDA _WRITE_DATA$LEN
	CLC
	ADC __TMP1
	RTS


; ---------------------------------------------------------------------------
; -- Function SUM3 --
_SUM3:
_SUM3$A                 = __LVSLOT_7
_SUM3$B                 = __LVSLOT_8
_SUM3$C                 = __LVSLOT_9
	STA _SUM3$A
	STX _SUM3$A+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 31:     return a + b + c
	STA __MATH0
	STX __MATH0+1
	LDA _SUM3$B
	LDX _SUM3$B+1
	JSR __ADD16_AX
	LDA _SUM3$C
	LDX _SUM3$C+1
	JSR __ADD16_AX
	LDA __MATH0
	LDX __MATH0+1
	RTS


; ---------------------------------------------------------------------------
; -- Function DOUBLE --
_DOUBLE:
_DOUBLE$X               = __LVSLOT_9
	STA _DOUBLE$X
	STX _DOUBLE$X+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 35:     return x + x
	STA __MATH0
	STX __MATH0+1
	LDA _DOUBLE$X
	LDX _DOUBLE$X+1
	JSR __ADD16_AX
	LDA __MATH0
	LDX __MATH0+1
	RTS


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$TEXT              = __LVSLOT_1
_MAIN$TEXT2             = __LVSLOT_2
_MAIN$R                 = __LVSLOT_3
_MAIN$W                 = __LVSLOT_6
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 40:     byte text[] = "Hello"
	LDA #<__STR_DATA_1
	LDX #>__STR_DATA_1
	STA __TMP0
	STX __TMP0+1
	LDA #<_MAIN$TEXT
	LDX #>_MAIN$TEXT
	STA __TMP2
	STX __TMP2+1
	LDX #6
	JSR __COPY_BYTES
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 41:     byte text2[] = "AB"
	LDA #$41
	STA _MAIN$TEXT2+0
	LDA #$42
	STA _MAIN$TEXT2+1
	LDA #$00
	STA _MAIN$TEXT2+2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 48:     r = write_data(1, text, count_bytes(text))
	LDA #<_MAIN$TEXT
	LDX #>_MAIN$TEXT
	JSR _COUNT_BYTES
	STA _WRITE_DATA$LEN
	LDA #<_MAIN$TEXT
	LDX #>_MAIN$TEXT
	STA _WRITE_DATA$BUF
	STX _WRITE_DATA$BUF+1
	LDA #$01
	JSR _WRITE_DATA
	STA _MAIN$R
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 49:     if r == 77
	CMP #$4D
	BNE __ZAP_else_5
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 50:         result += 1     ; +1
	INC _RESULT
__ZAP_else_5:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 54:     r = write_data(2, text2, count_bytes(text2))
	LDA #<_MAIN$TEXT2
	LDX #>_MAIN$TEXT2
	JSR _COUNT_BYTES
	STA _WRITE_DATA$LEN
	LDA #<_MAIN$TEXT2
	LDX #>_MAIN$TEXT2
	STA _WRITE_DATA$BUF
	STX _WRITE_DATA$BUF+1
	LDA #$02
	JSR _WRITE_DATA
	STA _MAIN$R
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 57:     if r == 67
	CMP #$43
	BNE __ZAP_else_8
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 58:         result += 1     ; +2
	INC _RESULT
__ZAP_else_8:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 64:     w = sum3(100, double(50), double(75))
	LDA #$32
	LDX #$00
	JSR _DOUBLE
	PHA
	TXA
	PHA
	LDA #$4B
	LDX #$00
	JSR _DOUBLE
	STA _SUM3$C
	STX _SUM3$C+1
	PLA
	STA _SUM3$B+1
	PLA
	STA _SUM3$B
	LDA #$64
	LDX #$00
	JSR _SUM3
	STA _MAIN$W
	STX _MAIN$W+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 65:     if w == 350
	CMP #$5E
	BNE __ZAP_else_11
	CPX #$01
	BNE __ZAP_else_11
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 66:         result += 1     ; +3
	INC _RESULT
__ZAP_else_11:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 72:     r = write_data(0, text, count_bytes(text) + count_bytes(text2))
	LDA #<_MAIN$TEXT
	LDX #>_MAIN$TEXT
	JSR _COUNT_BYTES
	PHA
	LDA #<_MAIN$TEXT2
	LDX #>_MAIN$TEXT2
	JSR _COUNT_BYTES
	STA __TMP0
	PLA
	CLC
	ADC __TMP0
	STA _WRITE_DATA$LEN
	LDA #<_MAIN$TEXT
	LDX #>_MAIN$TEXT
	STA _WRITE_DATA$BUF
	STX _WRITE_DATA$BUF+1
	LDA #$00
	JSR _WRITE_DATA
	STA _MAIN$R
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 73:     if r == 79
	CMP #$4F
	BNE __ZAP_else_15
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\202-deferred-param-store\202-deferred-param-store.zap 74:         result += 1     ; +4
	INC _RESULT
__ZAP_else_15:
	RTS


.segment "CODE"


; ------------------------------
; Shared byte copy routine
; Inputs: __TMP0/__TMP0+1=src, __TMP2/__TMP2+1=dst, X=len (1..255), Y=0
; Clobbers: A, X, Y
; Note: length must fit in one page; longer copies stay inline
__COPY_BYTES:
	LDY #$00
	CPX #$00
	BEQ COPY_BYTES_DONE
COPY_BYTES_LOOP:
	LDA (__TMP0),Y
	STA (__TMP2),Y
	INY
	DEX
	BNE COPY_BYTES_LOOP
COPY_BYTES_DONE:
	RTS
__ADD16_AX:
	STA __MATH1
	STX __MATH1+1
; __ADD16: 16-bit addition (accumulator style)
; Input: __MATH0 low word (left operand), __MATH1 low word (right operand)
; Output: __MATH0=sum (32-bit, high word cleared)
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	RTS
__STR_DATA_1:
	.byte "Hello", $00
; End of file