; Generated by Zap Compiler
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array_default.s
; ==============================

.DEBUGINFO +  ; Enable debug information for symbol names

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2
TMP2:	.res 4

; Fixed-address variables
_RESULT = $9C40

; Byte variables
_MAIN_SUM:	.res 1

.segment "BSS"
; Array variables (BSS)
_MAIN_ARR:	.res 3

.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap 1: byte result @40000 = 0
	STZ _RESULT

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap 3: proc main()
; -- Procedure MAIN --
MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap 6:     arr[0] = 10
	LDA #10
	STA TMP2
	STX TMP2+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #0
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap 7:     arr[1] = 20
	LDA #20
	STA TMP2
	STX TMP2+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #1
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap 8:     arr[2] = 30
	LDA #30
	STA TMP2
	STX TMP2+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #2
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA TMP2
	STA (TMP0),Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap 9:     sum = arr[0] + arr[1] + arr[2]  ; 10 + 20 + 30 = 60
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #0
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #1
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	CLC
	ADC TMP1
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #2
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	CLC
	ADC TMP1
	STA _MAIN_SUM
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\004-simple-array\004-simple-array.zap 10:     result = sum
	LDA _MAIN_SUM
	LDX #0
	STA _RESULT
	RTS

.segment "CODE"
__END:
.export __END

; End of file