; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py tests/pass/003-word-type/003-word-type.zap -o tests/pass/003-word-type/003-word-type_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 2
; Word variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/003-word-type/003-word-type.zap 1: word result @40000 = 0
	STZ _RESULT
	STZ _RESULT+1
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/003-word-type/003-word-type.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
_MAIN$Y                 = __LVSLOT_2
_MAIN$Z                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/003-word-type/003-word-type.zap 4:     word x = 1000
	LDA #$E8
	STA _MAIN$X
	LDA #$03
	STA _MAIN$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/003-word-type/003-word-type.zap 5:     word y = 1995
	LDA #$CB
	STA _MAIN$Y
	LDA #$07
	STA _MAIN$Y+1
; /home/dusan/src/ZAP-compiler/tests/pass/003-word-type/003-word-type.zap 6:     word z = x + y + 5    ; z = 3000
	LDA _MAIN$X
	CLC
	ADC _MAIN$Y
	STA _MAIN$Z
	LDA _MAIN$X+1
	ADC _MAIN$Y+1
	STA _MAIN$Z+1
	LDA #$05
	CLC
	ADC _MAIN$Z
	STA _MAIN$Z
	LDA #$00
	ADC _MAIN$Z+1
	STA _MAIN$Z+1
; /home/dusan/src/ZAP-compiler/tests/pass/003-word-type/003-word-type.zap 7:     result = z
	LDA _MAIN$Z
	LDX _MAIN$Z+1
	STA _RESULT
	STX _RESULT+1
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file