; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/003-word-type//003-word-type.zap -o tests/pass/003-word-type//003-word-type_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 2
; Word variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\003-word-type\003-word-type.zap 1: word result @40000 = 0
	STZ _RESULT
	STZ _RESULT+1
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_X = __LVSLOT_1
_MAIN_Y = __LVSLOT_2
_MAIN_Z = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\003-word-type\003-word-type.zap 4:     word x = 1000
	LDA #$E8
	STA _MAIN_X
	LDA #$03
	STA _MAIN_X+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\003-word-type\003-word-type.zap 5:     word y = 1995
	LDA #$CB
	STA _MAIN_Y
	LDA #$07
	STA _MAIN_Y+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\003-word-type\003-word-type.zap 6:     word z = x + y + 5    ; z = 3000
	LDA _MAIN_X
	CLC
	ADC _MAIN_Y
	STA _MAIN_Z
	LDA _MAIN_X+1
	ADC _MAIN_Y+1
	STA _MAIN_Z+1
	LDA #$05
	CLC
	ADC _MAIN_Z
	STA _MAIN_Z
	LDA #$00
	ADC _MAIN_Z+1
	STA _MAIN_Z+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\003-word-type\003-word-type.zap 7:     result = z
	LDA _MAIN_Z
	LDX _MAIN_Z+1
	STA _RESULT
	STX _RESULT+1
	RTS


.segment "CODE"
; End of file