; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/066-const-scalar/066-const-scalar.zap -o tests/pass/066-const-scalar/066-const-scalar_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Constants
_TEN                    = $0A
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/066-const-scalar/066-const-scalar.zap 2: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/066-const-scalar/066-const-scalar.zap 4: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/066-const-scalar/066-const-scalar.zap 5:     result = TEN + 2
	LDA #$0C
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file