; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py tests/pass/249-struct-comparison/249-struct-comparison.zap -o tests/pass/249-struct-comparison/249-struct-comparison_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP0                  = __LVSLOT_7
__TMP1:	.res 2
__TMP2                  = __LVSLOT_8
__TMP3                  = __LVSLOT_9
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
__LVSLOT_9:	.res 2
; ZP usage: 8 of 256 bytes ($00-$07), 248 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 2
__LVSLOT_3:	.res 2
; Struct variables (BSS)


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 14: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 16: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$V                 = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 21:     a.x = 3
	LDA #$03
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 22:     a.y = 7
	LDA #$07
	STA _MAIN$A+1
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 23:     b.x = 3
	LDA #$03
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 24:     b.y = 7
	LDA #$07
	STA _MAIN$B+1
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 27:     if a == b
	LDA #<_MAIN$A
	STA __TMP0
	LDA #>_MAIN$A
	STA __TMP0+1
	LDA #<_MAIN$B
	STA __TMP2
	LDA #>_MAIN$B
	STA __TMP2+1
	LDX #$02
	JSR __MEMCMP
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 28:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
__ZAP_endif_2:
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 32:     b.y = 99
	LDA #$63
	STA _MAIN$B+1
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 33:     if a != b
	LDA #<_MAIN$A
	STA __TMP0
	LDA #>_MAIN$A
	STA __TMP0+1
	LDA #<_MAIN$B
	STA __TMP2
	LDA #>_MAIN$B
	STA __TMP2+1
	LDX #$02
	JSR __MEMCMP
	BEQ __ZAP_else_4
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 34:         result = result + 10
	LDA _RESULT
	CLC
	ADC #$0A
	STA _RESULT
	JMP __ZAP_endif_5
__ZAP_else_4:
__ZAP_endif_5:
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 38:     v.dx = 3
	LDA #$03
	STA _MAIN$V
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 39:     v.dy = 7
	LDA #$07
	STA _MAIN$V+1
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 40:     if a == v
	LDA #<_MAIN$A
	STA __TMP0
	LDA #>_MAIN$A
	STA __TMP0+1
	LDA #<_MAIN$V
	STA __TMP2
	LDA #>_MAIN$V
	STA __TMP2+1
	LDX #$02
	JSR __MEMCMP
	BNE __ZAP_else_7
; /home/dusan/src/ZAP-compiler/tests/pass/249-struct-comparison/249-struct-comparison.zap 41:         result = result + 100
	LDA _RESULT
	CLC
	ADC #$64
	STA _RESULT
	JMP __ZAP_endif_8
__ZAP_else_7:
__ZAP_endif_8:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"


; ------------------------------
; __MEMCMP: compare up to 255 bytes at two addresses
; Inputs: __TMP0/__TMP0+1=addr1, __TMP2/__TMP2+1=addr2, X=len (1..255)
; Output: Z=1 if equal, Z=0 if different
; Clobbers: A, X, Y
__MEMCMP:
	LDY #$00
MEMCMP_LOOP:
	LDA (__TMP0),Y
	CMP (__TMP2),Y
	BNE MEMCMP_DONE
	INY
	DEX
	BNE MEMCMP_LOOP
; all bytes matched; DEX left Z=1
MEMCMP_DONE:
	RTS
; End of file