; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/049-control-flow-while//049-control-flow-while.zap -o tests/pass/049-control-flow-while//049-control-flow-while_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\049-control-flow-while\049-control-flow-while.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_COUNT = __LVSLOT_1
_MAIN_SUM = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\049-control-flow-while\049-control-flow-while.zap 4:     byte count = 3
	LDA #$03
	STA _MAIN_COUNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\049-control-flow-while\049-control-flow-while.zap 5:     byte sum = 0
	STZ _MAIN_SUM
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\049-control-flow-while\049-control-flow-while.zap 7:     while count > 0
__ZAP_while_1:
	LDA _MAIN_COUNT
	BEQ __ZAP_endwhile_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\049-control-flow-while\049-control-flow-while.zap 8:         sum = sum + 2
	INC _MAIN_SUM
	INC _MAIN_SUM
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\049-control-flow-while\049-control-flow-while.zap 9:         count = count - 1
	DEC _MAIN_COUNT
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\049-control-flow-while\049-control-flow-while.zap 12:     result = sum
	LDA _MAIN_SUM
	STA _RESULT
	RTS


.segment "CODE"
; End of file