; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py tests/pass/209-pure-asm-proc-params/209-pure-asm-proc-params.zap -o tests/pass/209-pure-asm-proc-params/209-pure-asm-proc-params_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/209-pure-asm-proc-params/209-pure-asm-proc-params.zap 7: proc my_poke(byte val) #asm
; -- Procedure MY_POKE --
_MY_POKE:
_MY_POKE$VAL            = __LVSLOT_1
	STA _MY_POKE$VAL
; ASM_BLOCK_BEGIN
	lda _MY_POKE$VAL
	sta $4200
	rts
; ASM_BLOCK_END
	.segment "CODE"


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/209-pure-asm-proc-params/209-pure-asm-proc-params.zap 13: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/209-pure-asm-proc-params/209-pure-asm-proc-params.zap 14:     my_poke($42)
	LDA #$42
	JSR _MY_POKE
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file