; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\033-structs-nested\033-structs-nested.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\033-structs-nested\033-structs-nested_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP1:	.res 2
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 2 of 256 bytes ($00-$01), 254 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 2
; Struct variables (BSS)


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\033-structs-nested\033-structs-nested.zap 10: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$O                 = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\033-structs-nested\033-structs-nested.zap 14:     o.inner.v = 9
	LDA #$09
	STA _MAIN$O
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\033-structs-nested\033-structs-nested.zap 15:     o.extra = 2
	LDA #$02
	STA _MAIN$O+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\033-structs-nested\033-structs-nested.zap 16:     result = o.inner.v + o.extra
	LDA _MAIN$O
	LDX #$00
	STA __TMP1
	LDA _MAIN$O+1
	CLC
	ADC __TMP1
	STA _RESULT
	RTS


.segment "CODE"
; End of file