; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -O1 tests/pass/210-pure-asm-func/210-pure-asm-func.zap -o tests/pass/210-pure-asm-func/210-pure-asm-func_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $4200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Function ADD_BYTES --
_ADD_BYTES:
_ADD_BYTES$A            = __LVSLOT_1
_ADD_BYTES$B            = __LVSLOT_2
	STA _ADD_BYTES$A
	STX _ADD_BYTES$B
; ASM_BLOCK_BEGIN
	clc
	adc _ADD_BYTES$B
	rts
; ASM_BLOCK_END
	.segment "CODE"


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/210-pure-asm-func/210-pure-asm-func.zap 18: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/210-pure-asm-func/210-pure-asm-func.zap 19:     result = add_bytes(3, 4)
	LDA #$03
	LDX #$04
	JSR _ADD_BYTES
	STA _RESULT
	RTS


.segment "CODE"
; End of file