; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/075-early-return/075-early-return.zap -o tests/pass/075-early-return/075-early-return_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP0                  = __LVSLOT_5
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_5:	.res 2
; Byte variables
; ZP usage: 3 of 256 bytes ($00-$02), 253 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 3: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 6: proc helper2(byte a)
; -- Procedure HELPER2 --
_HELPER2:
_HELPER2$A              = __LVSLOT_1
	STA _HELPER2$A
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 7:     if a > 10
	LDA _HELPER2$A
	CMP #$0A
	BEQ __ZAP_REL_ELSE_TMP_4
	BCS __ZAP_then_3
__ZAP_REL_ELSE_TMP_4:
	JMP __ZAP_else_1
__ZAP_then_3:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 8:         return
	RTS
	JMP __ZAP_endif_2
__ZAP_else_1:
__ZAP_endif_2:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 11:     if a > 5
	LDA _HELPER2$A
	CMP #$05
	BEQ __ZAP_REL_ELSE_TMP_8
	BCS __ZAP_then_7
__ZAP_REL_ELSE_TMP_8:
	JMP __ZAP_else_5
__ZAP_then_7:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 12:         return
	RTS
	JMP __ZAP_endif_6
__ZAP_else_5:
__ZAP_endif_6:
	RTS


; ---------------------------------------------------------------------------
; -- Function HELPER1 --
_HELPER1:
_HELPER1$PAR1           = __LVSLOT_1
	STA _HELPER1$PAR1
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 17:     if par1 > 10
	LDA _HELPER1$PAR1
	CMP #$0A
	BEQ __ZAP_REL_ELSE_TMP_12
	BCS __ZAP_then_11
__ZAP_REL_ELSE_TMP_12:
	JMP __ZAP_else_9
__ZAP_then_11:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 18:         return 1
	LDA #$01
	RTS
	JMP __ZAP_endif_10
__ZAP_else_9:
__ZAP_endif_10:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 21:     if par1 > 5
	LDA _HELPER1$PAR1
	CMP #$05
	BEQ __ZAP_REL_ELSE_TMP_16
	BCS __ZAP_then_15
__ZAP_REL_ELSE_TMP_16:
	JMP __ZAP_else_13
__ZAP_then_15:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 22:         return 2
	LDA #$02
	RTS
	JMP __ZAP_endif_14
__ZAP_else_13:
__ZAP_endif_14:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 25:     return 3
	LDA #$03
	RTS


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 29: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 30:     helper2(15)
	LDA #$0F
	JSR _HELPER2
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 31:     helper2(7)
	LDA #$07
	JSR _HELPER2
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 32:     helper2(3)
	LDA #$03
	JSR _HELPER2
; /home/dusan/src/ZAP-compiler/tests/pass/075-early-return/075-early-return.zap 34:     result = helper1(15) + helper1(7) + helper1(3)  ; 6
	LDA #$0F
	JSR _HELPER1
	PHA
	LDA #$07
	JSR _HELPER1
	STA __TMP0
	PLA
	CLC
	ADC __TMP0
	PHA
	LDA #$03
	JSR _HELPER1
	STA __TMP0
	PLA
	CLC
	ADC __TMP0
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file