; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -6502 -O1 tests/pass/045-functions-return-values/045-functions-return-values.zap -o tests/pass/045-functions-return-values/045-functions-return-values_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_5
__MATH1                 = __LVSLOT_6
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 4
; Byte variables
; Word variables
; ZP usage: 12 of 256 bytes ($00-$0B), 244 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/045-functions-return-values/045-functions-return-values.zap 9: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Function LO --
_LO:
_LO$W                   = __LVSLOT_3
	STA _LO$W
	STX _LO$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/045-functions-return-values/045-functions-return-values.zap 2:     return w
	RTS


; ---------------------------------------------------------------------------
; -- Function WIDEN --
_WIDEN:
_WIDEN$B                = __LVSLOT_2
	STA _WIDEN$B
; /home/dusan/src/ZAP-compiler/tests/pass/045-functions-return-values/045-functions-return-values.zap 6:     return b
	LDX #$00
	RTS


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$R1                = __LVSLOT_1
_MAIN$W1                = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/045-functions-return-values/045-functions-return-values.zap 12:     byte r1 = lo($12ab)       ; low byte expected $ab
	LDA #$AB
	LDX #$12
	JSR _LO
	STA _MAIN$R1
; /home/dusan/src/ZAP-compiler/tests/pass/045-functions-return-values/045-functions-return-values.zap 13:     word w1 = widen(1)
	LDA #$01
	JSR _WIDEN
	STA _MAIN$W1
	STX _MAIN$W1+1
; /home/dusan/src/ZAP-compiler/tests/pass/045-functions-return-values/045-functions-return-values.zap 14:     result = r1 + w1          ; $ab + 1 -> $ac
	LDA _MAIN$R1
	STA __MATH0
	LDA _MAIN$W1
	STA __MATH1
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	STA _RESULT
	RTS


.segment "CODE"
; End of file