; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -O1 tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap -o tests/pass/220-long-target-byte-mul/220-long-target-byte-mul_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_5
__MATH1                 = __LVSLOT_6
__TMP0                  = __LVSLOT_7
__TMP1:	.res 2
__TMP2                  = __LVSLOT_8
__TMP3                  = __LVSLOT_9
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 4
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 4
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
__LVSLOT_9:	.res 2
; Byte variables
; Long variables
; ZP usage: 22 of 256 bytes ($00-$15), 234 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 7: byte result @$0200 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$AA                = __LVSLOT_1
_MAIN$BB                = __LVSLOT_2
_MAIN$LL                = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 15:     aa = 200
	LDA #$C8
	STA _MAIN$AA
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 16:     bb = 200
	STA _MAIN$BB
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 17:     ll = aa * bb
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA _MAIN$AA
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	JSR MUL32
	LDA __MATH0
	STA _MAIN$LL
	LDA __MATH0+1
	STA _MAIN$LL+1
	LDA __MATH0+2
	STA _MAIN$LL+2
	LDA __MATH0+3
	STA _MAIN$LL+3
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 18:     if ll == 40000
	CMP #$00
	BNE __ZAP_else_1
	LDA _MAIN$LL+2
	BNE __ZAP_else_1
	LDA _MAIN$LL+1
	CMP #$9C
	BNE __ZAP_else_1
	LDA _MAIN$LL
	CMP #$40
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 19:         result = result + 1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 23:     aa = 200
	LDA #$C8
	STA _MAIN$AA
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 24:     bb = 5
	LDA #$05
	STA _MAIN$BB
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 25:     ll = aa / bb
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA _MAIN$AA
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	JSR DIV32
	LDA __MATH0
	STA _MAIN$LL
	LDA __MATH0+1
	STA _MAIN$LL+1
	LDA __MATH0+2
	STA _MAIN$LL+2
	LDA __MATH0+3
	STA _MAIN$LL+3
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 26:     if ll == 40
	CMP #$00
	BNE __ZAP_else_5
	LDA _MAIN$LL+2
	BNE __ZAP_else_5
	LDA _MAIN$LL+1
	BNE __ZAP_else_5
	LDA _MAIN$LL
	CMP #$28
	BNE __ZAP_else_5
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 27:         result = result + 1
	INC _RESULT
__ZAP_else_5:
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 31:     aa = 200
	LDA #$C8
	STA _MAIN$AA
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 32:     bb = 7
	LDA #$07
	STA _MAIN$BB
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 33:     ll = aa % bb
	STA __MATH1
	STZ __MATH1+1
	STZ __MATH1+2
	STZ __MATH1+3
	LDA _MAIN$AA
	STA __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	JSR MOD32
	LDA __MATH0
	STA _MAIN$LL
	LDA __MATH0+1
	STA _MAIN$LL+1
	LDA __MATH0+2
	STA _MAIN$LL+2
	LDA __MATH0+3
	STA _MAIN$LL+3
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 34:     if ll == 4
	CMP #$00
	BNE __ZAP_else_9
	LDA _MAIN$LL+2
	BNE __ZAP_else_9
	LDA _MAIN$LL+1
	BNE __ZAP_else_9
	LDA _MAIN$LL
	CMP #$04
	BNE __ZAP_else_9
; /home/dusan/src/ZAP-compiler/tests/pass/220-long-target-byte-mul/220-long-target-byte-mul.zap 35:         result = result + 1
	INC _RESULT
__ZAP_else_9:
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; MUL32: __MATH0 = __MATH0 * __MATH1
MUL32:
	LDA __MATH0
	STA __TMP0
	LDA __MATH0+1
	STA __TMP1
	LDA __MATH0+2
	STA __TMP2
	LDA __MATH0+3
	STA __TMP3
	STZ __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	LDX #32
MUL32_LOOP:
	LSR __MATH1+3
	ROR __MATH1+2
	ROR __MATH1+1
	ROR __MATH1
	BCC MUL32_SKIP
	LDA __MATH0
	CLC
	ADC __TMP0
	STA __MATH0
	LDA __MATH0+1
	ADC __TMP1
	STA __MATH0+1
	LDA __MATH0+2
	ADC __TMP2
	STA __MATH0+2
	LDA __MATH0+3
	ADC __TMP3
	STA __MATH0+3
MUL32_SKIP:
	ASL __TMP0
	ROL __TMP1
	ROL __TMP2
	ROL __TMP3
	DEX
	BNE MUL32_LOOP
	RTS
DIV32:
	STZ __TMP0
	STZ __TMP1
	STZ __TMP2
	STZ __TMP3
	LDX #32
DIV32_LOOP:
	ASL __MATH0
	ROL __MATH0+1
	ROL __MATH0+2
	ROL __MATH0+3
	ROL __TMP0
	ROL __TMP1
	ROL __TMP2
	ROL __TMP3
	SEC
	LDA __TMP0
	SBC __MATH1
	TAY
	LDA __TMP1
	SBC __MATH1+1
	PHA
	LDA __TMP2
	SBC __MATH1+2
	PHA
	LDA __TMP3
	SBC __MATH1+3
	BCC DIV32_SKIP
	STA __TMP3
	PLA
	STA __TMP2
	PLA
	STA __TMP1
	STY __TMP0
	INC __MATH0
	JMP DIV32_NEXT
DIV32_SKIP:
	PLA
	PLA
DIV32_NEXT:
	DEX
	BNE DIV32_LOOP
	RTS
MOD32:
	STZ __TMP0
	STZ __TMP1
	STZ __TMP2
	STZ __TMP3
	LDX #32
MOD32_LOOP:
	ASL __MATH0
	ROL __MATH0+1
	ROL __MATH0+2
	ROL __MATH0+3
	ROL __TMP0
	ROL __TMP1
	ROL __TMP2
	ROL __TMP3
	SEC
	LDA __TMP0
	SBC __MATH1
	TAY
	LDA __TMP1
	SBC __MATH1+1
	PHA
	LDA __TMP2
	SBC __MATH1+2
	PHA
	LDA __TMP3
	SBC __MATH1+3
	BCC MOD32_SKIP
	STA __TMP3
	PLA
	STA __TMP2
	PLA
	STA __TMP1
	STY __TMP0
	INC __MATH0
	JMP MOD32_NEXT
MOD32_SKIP:
	PLA
	PLA
MOD32_NEXT:
	DEX
	BNE MOD32_LOOP
	LDA __TMP0
	STA __MATH0
	LDA __TMP1
	STA __MATH0+1
	LDA __TMP2
	STA __MATH0+2
	LDA __TMP3
	STA __MATH0+3
	RTS