; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\063-expressions-complex\063-expressions-complex.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\063-expressions-complex\063-expressions-complex_6502_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH_STACK            = __LVSLOT_1
__MATH0                 = __LVSLOT_2
__MATH1                 = __LVSLOT_3
; Fixed-address variables
_RESULT                 = $9C40
_MAIN$EXPR              = $9C41
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 32
__LVSLOT_2:	.res 4
__LVSLOT_3:	.res 4
; ZP usage: 40 of 256 bytes ($00-$27), 216 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\063-expressions-complex\063-expressions-complex.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\063-expressions-complex\063-expressions-complex.zap 4:     byte expr @40001 = ((1 + 2) * (3 + 4)) - ((5 - 2) * 2)   ; 3*7 - 3*2 = 21 - 6 = 15
	LDA #$0F
	STA _MAIN$EXPR
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\063-expressions-complex\063-expressions-complex.zap 6:     if ((expr > 5) && (expr < 20)) || (expr == 0) 
	CMP #$05
	BCC __ZAP_CMP_END_5
	BNE __ZAP_CMP_TRUE_4
	LDA #$00
	JMP __ZAP_CMP_END_5
__ZAP_CMP_TRUE_4:
	LDA #$01
__ZAP_CMP_END_5:
	STA __MATH0
	STA __MATH_STACK+0
	LDA _MAIN$EXPR
	CMP #$14
	BCC __ZAP_CMP_TRUE_6
	LDA #$00
	JMP __ZAP_CMP_END_7
__ZAP_CMP_TRUE_6:
	LDA #$01
__ZAP_CMP_END_7:
	STA __MATH0
	LDA __MATH_STACK+0
	STA __MATH1
	LDA __MATH0
	BEQ __ZAP_AND_ZERO_8
	LDA __MATH1
	BEQ __ZAP_AND_ZERO_8
	LDA #$01
	JMP __ZAP_AND_END_9
__ZAP_AND_ZERO_8:
	LDA #$00
__ZAP_AND_END_9:
	STA __MATH0
	STA __MATH_STACK+0
	LDA _MAIN$EXPR
	BEQ __ZAP_CMP_TRUE_10
	LDA #$00
	JMP __ZAP_CMP_END_11
__ZAP_CMP_TRUE_10:
	LDA #$01
__ZAP_CMP_END_11:
	STA __MATH0
	LDA __MATH_STACK+0
	STA __MATH1
	LDA __MATH0
	BNE __ZAP_OR_ONE_12
	LDA __MATH1
	BNE __ZAP_OR_ONE_12
	LDA #$00
	JMP __ZAP_OR_END_13
__ZAP_OR_ONE_12:
	LDA #$01
__ZAP_OR_END_13:
	STA __MATH0
	BEQ __ZAP_else_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\063-expressions-complex\063-expressions-complex.zap 7:         result = 1
	LDA #$01
	STA _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\063-expressions-complex\063-expressions-complex.zap 9:         result = 0
	LDA #$00
	STA _RESULT
__ZAP_endif_2:
	RTS


.segment "CODE"
; End of file