; Generated by Zap Compiler 0.9.4
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/001-main-entry-point/001-main-entry-point.zap -o /home/dusan/src/ZAP-compiler/tests/pass/001-main-entry-point/001-main-entry-point_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/001-main-entry-point/001-main-entry-point.zap 2: proc main()
; -- Procedure MAIN --
_MAIN:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file