; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/156-continue-in-switch/156-continue-in-switch.zap -o tests/pass/156-continue-in-switch/156-continue-in-switch_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$I                 = __LVSLOT_2
_MAIN$K                 = __LVSLOT_2
_MAIN$CNT               = __LVSLOT_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 4:     byte i = 0
	LDA #$00
	STA _MAIN$I
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 5:     byte k = 0
	LDA #$00
	STA _MAIN$K
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 6:     byte cnt = 0
	LDA #$00
	STA _MAIN$CNT
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 11:     i = 0
	LDA #$00
	STA _MAIN$I
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 12:     cnt = 0
	LDA #$00
	STA _MAIN$CNT
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 13:     while i < 5
__ZAP_while_1:
	LDA _MAIN$I
	CMP #$05
	BCS __ZAP_endwhile_2
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 14:         i = i + 1
	INC _MAIN$I
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 15:         switch i
	LDA _MAIN$I
	CMP #$03
	BEQ __ZAP_while_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 17:             continue    ; jumps to while condition check, skipping cnt++
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 19:         cnt = cnt + 1   ; runs for i=1,2,4,5 but NOT i=3
	INC _MAIN$CNT
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 21:     if cnt == 4
	LDA _MAIN$CNT
	CMP #$04
	BNE __ZAP_else_7
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 22:         result = result + 1     ; 1: continue skipped cnt++ on i=3 iteration
	INC _RESULT
	JMP __ZAP_endif_8
__ZAP_else_7:
__ZAP_endif_8:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 24:     if i == 5
	LDA _MAIN$I
	CMP #$05
	BNE __ZAP_else_10
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 25:         result = result + 1     ; 2: while ran to completion (continue didn't exit it)
	INC _RESULT
	JMP __ZAP_endif_11
__ZAP_else_10:
__ZAP_endif_11:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 30:     k = 0
	LDA #$00
	STA _MAIN$K
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 31:     cnt = 0
	LDA #$00
	STA _MAIN$CNT
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 32:     repeat
__ZAP_repeat_13:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 33:         k = k + 1
	INC _MAIN$K
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 34:         switch k
	LDA _MAIN$K
	CMP #$02
	BEQ __ZAP_repeat_cond_14
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 36:             continue    ; jumps to [until k==5], skipping cnt++
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 38:         cnt = cnt + 1   ; runs for k=1,3,4,5 but NOT k=2
	INC _MAIN$CNT
__ZAP_repeat_cond_14:
	LDA _MAIN$K
	CMP #$05
	BNE __ZAP_repeat_13
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 40:     if cnt == 4
	LDA _MAIN$CNT
	CMP #$04
	BNE __ZAP_else_19
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 41:         result = result + 1     ; 3: continue skipped cnt++ on k=2 iteration
	INC _RESULT
	JMP __ZAP_endif_20
__ZAP_else_19:
__ZAP_endif_20:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 43:     if k == 5
	LDA _MAIN$K
	CMP #$05
	BNE __ZAP_else_22
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/156-continue-in-switch/156-continue-in-switch.zap 44:         result = result + 1     ; 4: repeat ran to its until-condition
	INC _RESULT
	JMP __ZAP_endif_23
__ZAP_else_22:
__ZAP_endif_23:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file