; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/055-operators-arithmetic/055-operators-arithmetic.zap -o /home/dusan/src/ZAP-compiler/tests/pass/055-operators-arithmetic/055-operators-arithmetic_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/055-operators-arithmetic/055-operators-arithmetic.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/055-operators-arithmetic/055-operators-arithmetic.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/055-operators-arithmetic/055-operators-arithmetic.zap 4:     result = 2 + 3 * 4 - 5    ; 2 + 12 - 5 = 9
	LDA #$09
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file