; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/114-unary-bnot-rpn//114-unary-bnot-rpn.zap -o tests/pass/114-unary-bnot-rpn//114-unary-bnot-rpn_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\114-unary-bnot-rpn\114-unary-bnot-rpn.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_X = __LVSLOT_1
_MAIN_Y = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\114-unary-bnot-rpn\114-unary-bnot-rpn.zap 4:     byte x = 0x0F  ; 0000 1111 in binary
	LDA #$0F
	STA _MAIN_X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\114-unary-bnot-rpn\114-unary-bnot-rpn.zap 5:     byte y = ~x    ; Should be 1111 0000 = 0xF0
	LDX #$00
	EOR #$FF
	STA _MAIN_Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\114-unary-bnot-rpn\114-unary-bnot-rpn.zap 6:     if y == 0xF0
	CMP #$F0
	BNE __ZAP_else_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\114-unary-bnot-rpn\114-unary-bnot-rpn.zap 7:         result = 1
	LDA #$01
	STA _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\114-unary-bnot-rpn\114-unary-bnot-rpn.zap 9:         result = 0
	LDA #$00
	STA _RESULT
__ZAP_endif_2:
	RTS


.segment "CODE"
; End of file