; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else.zap -o /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$FLAG              = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else.zap 4:     byte flag = 0
	STZ _MAIN$FLAG
; /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else.zap 6:     if flag == 1 
	LDA _MAIN$FLAG
	CMP #$01
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else.zap 7:         result = 1
	LDA #$01
	STA _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/046-control-flow-if-else/046-control-flow-if-else.zap 9:         result = 2
	LDA #$02
	STA _RESULT
__ZAP_endif_2:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file