; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$FLAG              = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else.zap 4:     byte flag = 0
	LDA #$00
	STA _MAIN$FLAG
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else.zap 6:     if flag == 1 
	LDA _MAIN$FLAG
	CMP #$01
	BNE __ZAP_else_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else.zap 7:         result = 1
	LDA #$01
	STA _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\046-control-flow-if-else\046-control-flow-if-else.zap 9:         result = 2
	LDA #$02
	STA _RESULT
__ZAP_endif_2:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file