; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -6502 -O1 tests/pass/044-bitwise-operations/044-bitwise-operations.zap -o tests/pass/044-bitwise-operations/044-bitwise-operations_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/044-bitwise-operations/044-bitwise-operations.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
_MAIN$Y                 = __LVSLOT_2
_MAIN$Z                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/044-bitwise-operations/044-bitwise-operations.zap 4:     byte x = 255
	LDA #$FF
	STA _MAIN$X
; /home/dusan/src/ZAP-compiler/tests/pass/044-bitwise-operations/044-bitwise-operations.zap 5:     byte y = 127
	LDA #$7F
	STA _MAIN$Y
; /home/dusan/src/ZAP-compiler/tests/pass/044-bitwise-operations/044-bitwise-operations.zap 6:     byte z = x - y
	LDA _MAIN$X
	SEC
	SBC _MAIN$Y
	STA _MAIN$Z
; /home/dusan/src/ZAP-compiler/tests/pass/044-bitwise-operations/044-bitwise-operations.zap 7:     result = z
	STA _RESULT
	RTS


.segment "CODE"
; End of file