; errno.zap
; Error codes for ZAP
; Based on Linux kernel error codes https://man7.org/linux/man-pages/man3/errno.3.html

.module "errno"


; Error codes
const byte E2BIG = $01          ; Argument list too long
const byte EACCES = $02         ; Permission denied
const byte EADDRINUSE = $03     ; Address already in use
const byte EADDRNOTAVAIL = $04  ; Address not available
const byte EAFNOSUPPORT = $05   ; Address family not supported
const byte EAGAIN = $06         ; Resource temporarily unavailable
const byte EALREADY = $07       ; Connection already in progress
const byte EBADE = $08          ; Invalid exchange
const byte EBADF = $09          ; Bad file descriptor
const byte EBADFD = $0a         ; File descriptor in bad state
const byte EBADMSG = $0b        ; Bad message
const byte EBADR = $0c          ; Invalid request descriptor
const byte EBADRQC = $0d        ; Invalid request code
const byte EBADSLT = $0e        ; Invalid slot
const byte EBUSY = $0f          ; Device or resource busy
const byte ECANCELED = $10      ; Operation canceled
const byte ECHILD = $11         ; No child processes
const byte ECHRNG = $12         ; Channel number out of range
const byte ECOMM = $13          ; Communication error on send
const byte ECONNABORTED = $14   ; Connection aborted
const byte ECONNREFUSED = $15   ; Connection refused
const byte ECONNRESET = $16     ; Connection reset
const byte EDEADLK = $17        ; Deadlock
const byte EDEADLOCK = $18      ; Deadlock
const byte EDESTADDRREQ = $19   ; Destination address required
const byte EDOM = $1a           ; Domain error
const byte EDQUOT = $1b         ; Disk quota exceeded
const byte EEXIST = $1c         ; File exists
const byte EFAULT = $1d         ; Bad address
const byte EFBIG = $1e          ; File too large
const byte EHOSTDOWN = $1f      ; Host is down
const byte EHOSTUNREACH = $20   ; Host is unreachable
const byte EHWPOISON = $21      ; Hardware error
const byte EIDRM = $22          ; Identifier removed
const byte EILSEQ = $23         ; Invalid sequence
const byte EINPROGRESS = $24    ; Operation in progress
const byte EINTR = $25          ; Interrupted
const byte EINVAL = $26         ; Invalid argument
const byte EIO = $27            ; I/O error
const byte EISCONN = $28        ; Connection already in progress
const byte EISDIR = $29         ; Is a directory
const byte EISNAM = $2a         ; Is a named file
const byte EKEYEXPIRED = $2b    ; Key expired
const byte EKEYREJECTED = $2c   ; Key rejected
const byte EKEYREVOKED = $2d    ; Key revoked
const byte EL2HLT = $2e         ; Level 2 halted
const byte EL2NSYNC = $2f       ; Level 2 not synchronized
const byte EL3HLT = $30         ; Level 3 halted
const byte EL3RST = $31         ; Level 3 reset
const byte ELIBACC = $32        ; Library access
const byte ELIBBAD = $33        ; Library bad
const byte ELIBMAX = $34        ; Library max
const byte ELIBSCN = $35        ; Library section
const byte ELIBEXEC = $36       ; Library execution
const byte ELNRNG = $37         ; Link number range
const byte ELOOP = $38          ; Loop
const byte EMEDIUMTYPE = $39    ; Medium type
const byte EMFILE = $3a         ; Too many files
const byte EMLINK = $3b         ; Too many links
const byte EMSGSIZE = $3c       ; Message too long
const byte EMULTIHOP = $3d      ; Multihop
const byte ENAMETOOLONG = $3e   ; Filename too long
const byte ENETDOWN = $3f       ; Network down
const byte ENETRESET = $40      ; Network reset
const byte ENETUNREACH = $41    ; Network unreachable
const byte ENOANO = $42         ; No anonymous node
const byte ENOBUFS = $43        ; No buffers
const byte ENODATA = $44        ; No data
const byte ENODEV = $45         ; No device
const byte ENOENT = $46         ; No entry
const byte ENOEXEC = $47        ; No execute
const byte ENOKEY = $48         ; No key
const byte ENOLCK = $49         ; No lock
const byte ENOLINK = $4a        ; No link
const byte ENOMEDIUM = $4b      ; No medium
const byte ENOMEM = $4c         ; No memory
const byte ENOMSG = $4d         ; No message
const byte ENONET = $4e         ; No network
const byte ENOPKG = $4f         ; No package
const byte ENOPROTOOPT = $50    ; No protocol option
const byte ENOSPC = $51         ; No space
const byte ENOSR = $52          ; No stream resources
const byte ENOSTR = $53         ; No stream
const byte ENOSYS = $54         ; No system
const byte ENOTBLK = $55        ; Not a block device
const byte ENOTCONN = $56       ; Not connected
const byte ENOTDIR = $57        ; Not a directory
const byte ENOTEMPTY = $58      ; Directory not empty
const byte ENOTRECOVERABLE = $59    ; Not recoverable
const byte ENOTSOCK = $5a       ; Not a socket
const byte ENOTSUP = $5b        ; Not supported
const byte ENOTTY = $5c         ; Not a terminal
const byte ENOTUNIQ = $5d       ; Not unique
const byte ENXIO = $5e          ; No such device or address
const byte EOPNOTSUPP = $5f      ; Operation not supported
const byte EOVERFLOW = $60      ; Value too large
const byte EOWNERDEAD = $61     ; Owner died
const byte EPERM = $62          ; Operation not permitted
const byte EPFNOSUPPORT = $63   ; Protocol family not supported
const byte EPIPE = $64          ; Broken pipe
const byte EPROTO = $65         ; Protocol error    
const byte EPROTONOSUPPORT = $66; Protocol not supported
const byte EPROTOTYPE = $67     ; Protocol wrong type for socket
const byte ERANGE = $68         ; Value too large
const byte EREMCHG = $69        ; Remote address changed
const byte EREMOTE = $6a        ; Object is remote
const byte EREMOTEIO = $6b      ; Remote I/O error
const byte ERESTART = $6c       ; Interrupted system call should be restarted
const byte ERFKILL = $6d        ; RFILL error
const byte EROFS = $6e          ; Read-only file system
const byte ESHUTDOWN = $6f      ; Cannot send after socket shutdown
const byte ESPIPE = $70         ; Invalid seek
const byte ESOCKTNOSUPPORT = $71 ; Socket type not supported
const byte ESRCH = $72          ; No such proc  ess
const byte ESTALE = $73         ; File handle is stale
const byte ESTRPIPE = $74       ; Stream pipe error
const byte ETIME = $75          ; Timer expired
const byte ETIMEDOUT = $76      ; Connection timed out
const byte ETOOMANYREFS = $77   ; Too many references
const byte ETXTBSY = $78        ; Text file busy
const byte EUCLEAN = $79        ; File system needs cleaning
const byte EUNATCH = $7a        ; Protocol driver not attached
const byte EUSERS = $7b         ; Too many users
const byte EWOULDBLOCK = $7c    ; Operation would block
const byte EXDEV = $7d          ; Cross-device link
const byte EXFULL = $7e         ; Exchange full
