; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -ZPSTART 254 generated_tests/test_zp_overflow3.zap -o generated_tests/test_zp_overflow3.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names


.segment "ZEROPAGE"
; System variables
__MATH0 = __LVSLOT_3
__MATH1 = __LVSLOT_4
__TMP0 = __LVSLOT_5
__TMP1:	.res 2
__TMP2 = __LVSLOT_6
__TMP3 = __LVSLOT_7
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_3:	.res 4
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 2
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2


.segment "BSS"
; Word variables (BSS)


.segment "CODE"
; Globals initialization
; ------------------------------
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\generated_tests\test_zp_overflow3.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN_A = __LVSLOT_1
_MAIN_B = __LVSLOT_1
_MAIN_C = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\generated_tests\test_zp_overflow3.zap 5:     a = 1
	LDA #$01
	STA _MAIN_A
	STZ _MAIN_A+1
; C:\Users\dusan.holub\src\ZAP-compiler\generated_tests\test_zp_overflow3.zap 6:     b = a * 2
	LDA _MAIN_A
	LDX _MAIN_A+1
	STA __MATH0
	TXA
	STA __MATH0+1
	LDA #$02
	LDX #$00
	LDA _MAIN_A
	LDX _MAIN_A+1
	STA __TMP0
	STX __TMP0+1
	ASL __TMP0
	ROL __TMP0+1
	LDA __TMP0
	LDX __TMP0+1
	STA _MAIN_B
	STX _MAIN_B+1
; C:\Users\dusan.holub\src\ZAP-compiler\generated_tests\test_zp_overflow3.zap 7:     c = b * 3
	LDA _MAIN_B
	LDX _MAIN_B+1
	STA __MATH0
	TXA
	STA __MATH0+1
	LDA #$03
	LDX #$00
	JSR __MUL16_8_A
	STA _MAIN_C
	STX _MAIN_C+1
; C:\Users\dusan.holub\src\ZAP-compiler\generated_tests\test_zp_overflow3.zap 8:     a = c / 4
	LDA _MAIN_C
	LDX _MAIN_C+1
	STA __MATH0
	TXA
	STA __MATH0+1
	LDA #$04
	LDX #$00
	LDA _MAIN_C
	LDX _MAIN_C+1
	STA __TMP0
	STX __TMP0+1
	LSR __TMP0+1
	ROR __TMP0
	LSR __TMP0+1
	ROR __TMP0
	LDA __TMP0
	LDX __TMP0+1
	STA _MAIN_A
	STX _MAIN_A+1
	RTS


.segment "CODE"


; ------------------------------
; Math Runtime Routines
; ------------------------------
; __MUL8: 8x8=16 multiply
; Input: __MATH0 (multiplicand), __MATH1 (multiplier)
; Output: __MATH0=product (low word), __MATH0+2/+3 cleared
	LDA __MATH0
	STA __TMP0
	STZ __TMP0+1
	LDA __MATH1
	STA __TMP1
	STZ __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	LDX #$08
MUL8_LOOP:
	LSR __TMP1
	BCC MUL8_SKIP
	LDA __MATH0
	CLC
	ADC __TMP0
	STA __MATH0
	LDA __MATH0+1
	ADC __TMP0+1
	STA __MATH0+1
MUL8_SKIP:
	ASL __TMP0
	ROL __TMP0+1
	DEX
	BNE MUL8_LOOP
	LDA __MATH0
	LDX __MATH0+1
	RTS
; __MUL16_8_A: right operand (byte) in A
__MUL16_8_A:
	STA __MATH1
; __MUL16_8: 16x8=24 multiply
; Input: __MATH0 low word (multiplicand), __MATH1 low byte (multiplier)
; Output: __MATH0=product (32-bit)
	LDA __MATH0
	STA __TMP0
	LDA __MATH0+1
	STA __TMP0+1
	LDA __MATH1
	STA __TMP1
	STZ __MATH0
	STZ __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	LDX #$08
MUL16_8_LOOP:
	LSR __TMP1
	BCC MUL16_8_SKIP
	LDA __MATH0
	CLC
	ADC __TMP0
	STA __MATH0
	LDA __MATH0+1
	ADC __TMP0+1
	STA __MATH0+1
	LDA __MATH0+2
	ADC #$00
	STA __MATH0+2
	LDA __MATH0+3
	ADC #$00
	STA __MATH0+3
MUL16_8_SKIP:
	ASL __TMP0
	ROL __TMP0+1
	DEX
	BNE MUL16_8_LOOP
	LDA __MATH0
	LDX __MATH0+1
	RTS
; End of file