; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -6502 -O1 tests/pass/136-pointer-math/136-pointer-math.zap -o tests/pass/136-pointer-math/136-pointer-math_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_4
__MATH1                 = __LVSLOT_5
__TMP0                  = __LVSLOT_6
__TMP1:	.res 2
__TMP2                  = __LVSLOT_7
__TMP3                  = __LVSLOT_8
; Fixed-address variables
_RESULT                 = $9C40
_MAIN$BYTE_VAR          = $9C41
_MAIN$WORD_VAR          = $9C42
_MAIN$LONG_VAR          = $9C44
_MAIN$PTR_VAR           = $9C47
_MAIN$PTR_WORD          = $9C48
_MAIN$PTR_LONG          = $9C4A
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 2
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
; Word variables
; ZP usage: 20 of 256 bytes ($00-$13), 236 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$RESULT_WORD       = __LVSLOT_1
_MAIN$FOR_END_1         = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 4:     byte byte_var @40001 = 0
	LDA #$00
	STA _MAIN$BYTE_VAR
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 5:     word word_var @40002 = 0
	STA _MAIN$WORD_VAR
	STA _MAIN$WORD_VAR+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 6:     long long_var @40004 = 0
	STA _MAIN$LONG_VAR
	STA _MAIN$LONG_VAR+1
	STA _MAIN$LONG_VAR+2
	STA _MAIN$LONG_VAR+3
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 7:     byte ^ptr_var @40007 = @byte_var
	LDA #<$9C41
	LDX #>$9C41
	STA _MAIN$PTR_VAR
	STX _MAIN$PTR_VAR+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 8:     word ^ptr_word @40008 = @word_var
	LDA #<$9C42
	LDX #>$9C42
	STA _MAIN$PTR_WORD
	STX _MAIN$PTR_WORD+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 9:     long ^ptr_long @40010 = @long_var
	LDA #<$9C44
	LDX #>$9C44
	STA _MAIN$PTR_LONG
	STX _MAIN$PTR_LONG+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 11:     word result_word = 0
	LDA #$00
	STA _MAIN$RESULT_WORD
	STA _MAIN$RESULT_WORD+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 14:     if ptr_long == @long_var
	LDA #<$9C44
	LDX #>$9C44
	STA __TMP0
	STX __TMP0+1
	LDA _MAIN$PTR_LONG
	LDX _MAIN$PTR_LONG+1
	CMP __TMP0
	BNE __ZAP_else_1
	CPX __TMP0+1
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 15:         byte_var = 1
	LDA #$01
	STA _MAIN$BYTE_VAR
	JMP __ZAP_endif_2
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 17:         byte_var = 2    
	LDA #$02
	STA _MAIN$BYTE_VAR
__ZAP_endif_2:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 20:     ptr_long = ptr_long + 1
	LDA _MAIN$PTR_LONG
	CLC
	ADC #$04
	STA _MAIN$PTR_LONG
	BCC __ZAP_CARRY_ADD_PTR_5
	INC _MAIN$PTR_LONG+1
__ZAP_CARRY_ADD_PTR_5:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 21:     ptr_long = 1 + ptr_long
	LDA _MAIN$PTR_LONG
	CLC
	ADC #$04
	STA _MAIN$PTR_LONG
	BCC __ZAP_CARRY_ADD_PTR_6
	INC _MAIN$PTR_LONG+1
__ZAP_CARRY_ADD_PTR_6:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 22:     ptr_long = ptr_long - 1
	LDA _MAIN$PTR_LONG
	SEC
	SBC #$04
	STA _MAIN$PTR_LONG
	BCS __ZAP_CARRY_SUB_PTR_7
	DEC _MAIN$PTR_LONG+1
__ZAP_CARRY_SUB_PTR_7:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 25:     if ptr_long == @long_var + 1
	LDA #<$9C44
	LDX #>$9C44
	STA __TMP1
	STX __TMP1+1
	STA __MATH0
	LDA __TMP1+1
	STA __MATH0+1
	LDA #$04
	STA __MATH1
	LDA #$00
	STA __MATH1+1
	JSR __ADD16
	LDA __MATH0
	LDX __MATH0+1
	STA __TMP0
	STX __TMP0+1
	LDA _MAIN$PTR_LONG
	LDX _MAIN$PTR_LONG+1
	CMP __TMP0
	BNE __ZAP_else_8
	CPX __TMP0+1
	BNE __ZAP_else_8
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 26:         byte_var = 1
	LDA #$01
	STA _MAIN$BYTE_VAR
__ZAP_else_8:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 31:     ptr_var = ptr_var + 5
	LDA _MAIN$PTR_VAR
	CLC
	ADC #$05
	STA _MAIN$PTR_VAR
	LDA _MAIN$PTR_VAR+1
	ADC #$00
	STA _MAIN$PTR_VAR+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 32:     ptr_var = 5 + ptr_var
	LDA _MAIN$PTR_VAR
	CLC
	ADC #$05
	STA _MAIN$PTR_VAR
	LDA _MAIN$PTR_VAR+1
	ADC #$00
	STA _MAIN$PTR_VAR+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 34:     ptr_word = ptr_word + 3  ; Should scale by 2 (sizeof WORD)
	LDA _MAIN$PTR_WORD
	CLC
	ADC #$06
	STA _MAIN$PTR_WORD
	BCC __ZAP_CARRY_ADD_PTR_12
	INC _MAIN$PTR_WORD+1
__ZAP_CARRY_ADD_PTR_12:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 35:     ptr_word = 3 + ptr_word  ; Should scale by 2
	LDA _MAIN$PTR_WORD
	CLC
	ADC #$06
	STA _MAIN$PTR_WORD
	BCC __ZAP_CARRY_ADD_PTR_13
	INC _MAIN$PTR_WORD+1
__ZAP_CARRY_ADD_PTR_13:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 38:     ptr_word = ptr_word - 2  ; Should scale by 2
	LDA _MAIN$PTR_WORD
	SEC
	SBC #$04
	STA _MAIN$PTR_WORD
	BCS __ZAP_CARRY_SUB_PTR_14
	DEC _MAIN$PTR_WORD+1
__ZAP_CARRY_SUB_PTR_14:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 41:     result_word = ptr_word - @word_var  ; Should divide by 2
	LDA _MAIN$PTR_WORD
	LDX _MAIN$PTR_WORD+1
	STA _MAIN$RESULT_WORD
	STX _MAIN$RESULT_WORD+1
	LDA #<$9C42
	LDX #>$9C42
	STA __TMP3
	STX __TMP3+1
	ASL __TMP3
	ROL __TMP3+1
	LDA __TMP3
	LDX __TMP3+1
	STA __TMP2
	STX __TMP2+1
	SEC
	LDA _MAIN$RESULT_WORD
	SBC __TMP2
	STA _MAIN$RESULT_WORD
	LDA _MAIN$RESULT_WORD+1
	SBC __TMP2+1
	STA _MAIN$RESULT_WORD+1
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 44:     if ptr_word == 0
	LDA _MAIN$PTR_WORD
	ORA _MAIN$PTR_WORD+1
	BNE __ZAP_else_15
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 45:         byte_var = 1
	LDA #$01
	STA _MAIN$BYTE_VAR
__ZAP_else_15:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 48:     if ptr_word > @word_var
	LDA #<$9C42
	LDX #>$9C42
	STA __TMP0
	STX __TMP0+1
	LDA _MAIN$PTR_WORD
	LDX _MAIN$PTR_WORD+1
	CPX __TMP0+1
	BCC __ZAP_else_18
	BNE __ZAP_then_20
	CMP __TMP0
	BEQ __ZAP_else_18
	BCC __ZAP_else_18
__ZAP_then_20:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 49:         byte_var = 2
	LDA #$02
	STA _MAIN$BYTE_VAR
__ZAP_else_18:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 54:     if !ptr_word
	LDA _MAIN$PTR_WORD
	LDX _MAIN$PTR_WORD+1
	STA __MATH0
	TXA
	ORA __MATH0
	BNE __ZAP_NOT_NONZERO_25
	LDA #$01
	JMP __ZAP_NOT_END_26
__ZAP_NOT_NONZERO_25:
	LDA #$00
__ZAP_NOT_END_26:
	STA __MATH0
	BEQ __ZAP_else_22
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 55:         byte_var = 3
	LDA #$03
	STA _MAIN$BYTE_VAR
__ZAP_else_22:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 60:     for ptr_var = @byte_var to @byte_var + 10 step 1
	LDA #<$9C41
	LDX #>$9C41
	STA _MAIN$PTR_VAR
	STX _MAIN$PTR_VAR+1
	LDA #<$9C41
	LDX #>$9C41
	STA _MAIN$FOR_END_1
	STX _MAIN$FOR_END_1+1
	STA __MATH0
	LDA _MAIN$FOR_END_1+1
	STA __MATH0+1
	LDA #$0A
	STA __MATH1
	LDA #$00
	STA __MATH1+1
	JSR __ADD16
	LDA __MATH0
	LDX __MATH0+1
	STA _MAIN$FOR_END_1
	STX _MAIN$FOR_END_1+1
__ZAP_while_27:
	LDA _MAIN$PTR_VAR
	LDX _MAIN$PTR_VAR+1
	CPX _MAIN$FOR_END_1+1
	BCC __ZAP_while_body_29
	BNE __ZAP_endwhile_28
	CMP _MAIN$FOR_END_1
	BCS __ZAP_endwhile_28
__ZAP_while_body_29:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 61:         result_word = result_word + 1
	INC _MAIN$RESULT_WORD
	BNE __ZAP_INC_WORD_31
	INC _MAIN$RESULT_WORD+1
__ZAP_INC_WORD_31:
	INC _MAIN$PTR_VAR
	BNE __ZAP_while_27
	INC _MAIN$PTR_VAR+1
	JMP __ZAP_while_27
__ZAP_endwhile_28:
; /home/dusan/src/ZAP-compiler/tests/pass/136-pointer-math/136-pointer-math.zap 65:     result = 1
	LDA #$01
	STA _RESULT
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; __ADD16: 16-bit addition (accumulator style)
; Input: __MATH0 low word (left operand), __MATH1 low word (right operand)
; Output: __MATH0=sum (32-bit, high word cleared)
__ADD16:
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	LDA #$00
	STA __MATH0+2
	STA __MATH0+3
	RTS