; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py tests/pass/201-nested-call-args/201-nested-call-args.zap -o tests/pass/201-nested-call-args/201-nested-call-args_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_11
__MATH1                 = __LVSLOT_12
__TMP1:	.res 2
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_11:	.res 4
__LVSLOT_12:	.res 4
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 1
__LVSLOT_4:	.res 1
__LVSLOT_5:	.res 2
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
__LVSLOT_9:	.res 2
; Pointer variables
; Byte variables
; Word variables
; ZP usage: 23 of 256 bytes ($00-$16), 233 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 5
; Arrays (BSS)


.segment "CODE"
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 9: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Function WALK_PTR --
_WALK_PTR:
_WALK_PTR$PTR           = __LVSLOT_8
_WALK_PTR$N             = __LVSLOT_3
	STA _WALK_PTR$PTR
	STX _WALK_PTR$PTR+1
	STY _WALK_PTR$N
_WALK_PTR$I             = __LVSLOT_4
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 15:     for i = 0 to n
	STZ _WALK_PTR$I
__ZAP_while_1:
	LDA _WALK_PTR$I
	CMP _WALK_PTR$N
	BCS __ZAP_endwhile_2
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 16:         ptr += 1       ; this MODIFIES the local param 'ptr' (and its __LVSLOT)
	INC _WALK_PTR$PTR
	BNE __ZAP_INC_WORD_4
	INC _WALK_PTR$PTR+1
__ZAP_INC_WORD_4:
	INC _WALK_PTR$I
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 18:     return ptr^
	LDA (_WALK_PTR$PTR)
	RTS


; ---------------------------------------------------------------------------
; -- Function COMBINE --
_COMBINE:
_COMBINE$DATA           = __LVSLOT_9
_COMBINE$EXTRA          = __LVSLOT_3
	STA _COMBINE$DATA
	STX _COMBINE$DATA+1
	STY _COMBINE$EXTRA
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 26:     return data^ + extra
	LDA (_COMBINE$DATA)
	STA __TMP1
	LDA _COMBINE$EXTRA
	CLC
	ADC __TMP1
	RTS


; ---------------------------------------------------------------------------
; -- Function ADD_W --
_ADD_W:
_ADD_W$A                = __LVSLOT_6
_ADD_W$B                = __LVSLOT_7
	STA _ADD_W$A
	STX _ADD_W$A+1
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 32:     return a + b
	LDA _ADD_W$A
	LDX _ADD_W$A+1
	STA __MATH0
	TXA
	STA __MATH0+1
	LDA _ADD_W$B
	LDX _ADD_W$B+1
	JSR __ADD16_AX
	LDA __MATH0
	LDX __MATH0+1
	RTS


; ---------------------------------------------------------------------------
; -- Function GET_VAL --
_GET_VAL:
_GET_VAL$X              = __LVSLOT_7
	STA _GET_VAL$X
	STX _GET_VAL$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 36:     return x + 100
	LDA _GET_VAL$X
	LDX _GET_VAL$X+1
	STX __MATH0+1
	CLC
	ADC #$64
	BCC __ZAP_ADD16C_NC_5
	INC __MATH0+1
__ZAP_ADD16C_NC_5:
	LDX __MATH0+1
	RTS


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 40: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$BUF               = __LVSLOT_1
_MAIN$R                 = __LVSLOT_2
_MAIN$W                 = __LVSLOT_5
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 41:     byte buf[] = {10, 20, 30, 40, 50}
	; Copy array [10, 20, 30, 40, 50] (5 elements)
	LDX #$00
__ZAP_ARR_COPY_6:
	LDA __ARRAY_DATA_1,X
	STA _MAIN$BUF,X
	INX
	CPX #5
	BNE __ZAP_ARR_COPY_6
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 48:     r = combine(buf, walk_ptr(buf, 3))
	LDA #<_MAIN$BUF
	LDX #>_MAIN$BUF
	PHA
	TXA
	PHA
	LDA #<_MAIN$BUF
	LDX #>_MAIN$BUF
	LDY #$03
	JSR _WALK_PTR
	PHA
	PLA
	TAY
	PLA
	TAX
	PLA
	JSR _COMBINE
	STA _MAIN$R
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 49:     if r == 50
	LDA _MAIN$R
	CMP #$32
	BNE __ZAP_else_7
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 50:         result += 1     ; +1
	INC _RESULT
	JMP __ZAP_endif_8
__ZAP_else_7:
__ZAP_endif_8:
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 55:     w = add_w(500, get_val(200))
	LDA #$C8
	LDX #$00
	JSR _GET_VAL
	STA _ADD_W$B
	STX _ADD_W$B+1
	LDA #$F4
	LDX #$01
	JSR _ADD_W
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 56:     if w == 800
	LDA _MAIN$W
	CMP #$20
	BNE __ZAP_REL_ELSE_TMP_13
	LDX _MAIN$W+1
	CPX #$03
	BEQ __ZAP_then_12
__ZAP_REL_ELSE_TMP_13:
	JMP __ZAP_else_10
__ZAP_then_12:
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 57:         result += 1     ; +2
	INC _RESULT
	JMP __ZAP_endif_11
__ZAP_else_10:
__ZAP_endif_11:
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 63:     r = combine(buf, walk_ptr(buf, 1))
	LDA #<_MAIN$BUF
	LDX #>_MAIN$BUF
	PHA
	TXA
	PHA
	LDA #<_MAIN$BUF
	LDX #>_MAIN$BUF
	LDY #$01
	JSR _WALK_PTR
	PHA
	PLA
	TAY
	PLA
	TAX
	PLA
	JSR _COMBINE
	STA _MAIN$R
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 64:     if r == 30
	LDA _MAIN$R
	CMP #$1E
	BNE __ZAP_else_14
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 65:         result += 1     ; +3
	INC _RESULT
	JMP __ZAP_endif_15
__ZAP_else_14:
__ZAP_endif_15:
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 71:     w = add_w(get_val(10), get_val(20))
	LDA #$0A
	LDX #$00
	JSR _GET_VAL
	PHA
	TXA
	PHA
	LDA #$14
	LDX #$00
	JSR _GET_VAL
	STA _ADD_W$B
	STX _ADD_W$B+1
	PLA
	TAX
	PLA
	JSR _ADD_W
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 72:     if w == 230
	LDA _MAIN$W
	CMP #$E6
	BNE __ZAP_REL_ELSE_TMP_20
	LDX _MAIN$W+1
	CPX #$00
	BEQ __ZAP_then_19
__ZAP_REL_ELSE_TMP_20:
	JMP __ZAP_else_17
__ZAP_then_19:
; /home/dusan/src/ZAP-compiler/tests/pass/201-nested-call-args/201-nested-call-args.zap 73:         result += 1     ; +4
	INC _RESULT
	JMP __ZAP_endif_18
__ZAP_else_17:
__ZAP_endif_18:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; __ADD16_AX: right operand (word) in A/X
__ADD16_AX:
	STA __MATH1
	STX __MATH1+1
; __ADD16: 16-bit addition (accumulator style)
; Input: __MATH0 low word (left operand), __MATH1 low word (right operand)
; Output: __MATH0=sum (32-bit, high word cleared)
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	RTS
; ---------------------------------------------------------------------------
; Constant Data
__ARRAY_DATA_1:
	.byte $0A, $14, $1E, $28, $32
; End of file