; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap -o tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_5
__MATH1                 = __LVSLOT_6
__TMP0                  = __LVSLOT_7
__TMP2                  = __LVSLOT_8
__TMP3                  = __LVSLOT_9
__TMP4                  = __LVSLOT_10
; Fixed-address variables
_R1_LO                  = $0200
_R1_HI                  = $0201
_R2_LO                  = $0202
_R2_HI                  = $0203
_R3_LO                  = $0204
_R3_HI                  = $0205
_R4_LO                  = $0206
_R4_HI                  = $0207
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_10:	.res 2
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 4
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
__LVSLOT_9:	.res 2
; Byte variables
; Word variables
; ZP usage: 20 of 256 bytes ($00-$13), 236 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 19: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
_MAIN$Y                 = __LVSLOT_2
_MAIN$A                 = __LVSLOT_1
_MAIN$W                 = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 26:     x = 3
	LDA #$03
	STA _MAIN$X
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 27:     y = 7
	LDA #$07
	STA _MAIN$Y
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 28:     w = 40*y + x
	LDA _MAIN$Y
	LDX #$00
	STA __TMP3
	LDA #$00
	STA __TMP3+1
	STA __TMP4
	STA __TMP4+1
	ASL __TMP3
	ROL __TMP3+1
	ASL __TMP3
	ROL __TMP3+1
	ASL __TMP3
	ROL __TMP3+1
	CLC
	LDA __TMP3
	ADC __TMP4
	STA __TMP4
	LDA __TMP3+1
	ADC __TMP4+1
	STA __TMP4+1
	ASL __TMP3
	ROL __TMP3+1
	ASL __TMP3
	ROL __TMP3+1
	CLC
	LDA __TMP3
	ADC __TMP4
	STA __TMP4
	LDA __TMP3+1
	ADC __TMP4+1
	STA __TMP4+1
	LDA __TMP4
	LDX __TMP4+1
	STA __MATH0
	TXA
	STA __MATH0+1
	LDA _MAIN$X
	LDX #$00
	JSR __ADD16_AX
	LDA __MATH0
	LDX __MATH0+1
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 29:     r1_lo = low(w)
	LDA _MAIN$W
	STA _R1_LO
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 30:     r1_hi = high(w)
	LDA _MAIN$W+1
	STA _R1_HI
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 33:     a = 250
	LDA #$FA
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 34:     w = a + 5
	LDA _MAIN$A
	CLC
	ADC #$05
	STA _MAIN$W
	LDA #$00
	ADC #$00
	STA _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 35:     r2_lo = low(w)
	LDA _MAIN$W
	STA _R2_LO
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 36:     r2_hi = high(w)
	LDA _MAIN$W+1
	STA _R2_HI
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 39:     a = 100
	LDA #$64
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 40:     w = a + 300
	LDA _MAIN$A
	CLC
	ADC #$2C
	STA _MAIN$W
	LDA #$00
	ADC #$01
	STA _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 41:     r3_lo = low(w)
	LDA _MAIN$W
	STA _R3_LO
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 42:     r3_hi = high(w)
	LDA _MAIN$W+1
	STA _R3_HI
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 45:     a = 200
	LDA #$C8
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 46:     w = a * 4
	LDA _MAIN$A
	LDX #$00
	STA __TMP0
	STX __TMP0+1
	ASL __TMP0
	ROL __TMP0+1
	ASL __TMP0
	ROL __TMP0+1
	LDA __TMP0
	LDX __TMP0+1
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 47:     r4_lo = low(w)
	LDA _MAIN$W
	STA _R4_LO
; /home/dusan/src/ZAP-compiler/tests/pass/218-word-target-mixed-chain/218-word-target-mixed-chain.zap 48:     r4_hi = high(w)
	LDA _MAIN$W+1
	STA _R4_HI
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; __ADD16_AX: right operand (word) in A/X
__ADD16_AX:
	STA __MATH1
	STX __MATH1+1
; __ADD16: 16-bit addition (accumulator style)
; Input: __MATH0 low word (left operand), __MATH1 low word (right operand)
; Output: __MATH0=sum (32-bit, high word cleared)
__ADD16:
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0+1
	ADC __MATH1+1
	STA __MATH0+1
	STZ __MATH0+2
	STZ __MATH0+3
	RTS
; End of file