; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\047-shift-operations\047-shift-operations.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\047-shift-operations\047-shift-operations_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\047-shift-operations\047-shift-operations.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$SHIFT             = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\047-shift-operations\047-shift-operations.zap 4:     byte shift = 5
	LDA #$05
	STA _MAIN$SHIFT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\047-shift-operations\047-shift-operations.zap 5:     result = shift + shift
	CLC
	ADC _MAIN$SHIFT
	STA _RESULT
	RTS


.segment "CODE"
; End of file