; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -6502 -O1 tests/pass/229-long-logical/229-long-logical.zap -o tests/pass/229-long-logical/229-long-logical_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_4
__MATH1                 = __LVSLOT_5
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 4
__LVSLOT_2:	.res 4
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 4
; Long variables
; ZP usage: 16 of 256 bytes ($00-$0F), 240 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Arrays (BSS)
_LARR:	.res 8


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 15: byte result @$0200 = 0
	LDA #$00
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 17: long larr[2] = {0, $11111111}
	STA _LARR+0
	STA _LARR+1
	STA _LARR+2
	STA _LARR+3
	LDA #$11
	STA _LARR+4
	STA _LARR+5
	STA _LARR+6
	STA _LARR+7
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$Z                 = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 20:     long a = $10000
	LDA #$00
	STA _MAIN$A
	STA _MAIN$A+1
	STA _MAIN$A+3
	LDA #$01
	STA _MAIN$A+2
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 21:     long z = 0
	LDA #$00
	STA _MAIN$Z
	STA _MAIN$Z+1
	STA _MAIN$Z+2
	STA _MAIN$Z+3
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 24:     if a && a
	LDA _MAIN$A
	STA __MATH1
	LDA _MAIN$A+1
	STA __MATH1+1
	LDA _MAIN$A+2
	STA __MATH1+2
	LDA _MAIN$A+3
	STA __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	LDA _MAIN$A+1
	STA __MATH0+1
	LDA _MAIN$A+2
	STA __MATH0+2
	LDA _MAIN$A+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND32_BRANCH_4
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BEQ __ZAP_LAND32_BRANCH_4
	LDA #$01
	JMP __ZAP_LAND32_END_5
__ZAP_LAND32_BRANCH_4:
	LDA #$00
__ZAP_LAND32_END_5:
	STA __MATH0
	BEQ __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 25:         result = result + 1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 29:     if z && a
	LDA _MAIN$A
	STA __MATH1
	LDA _MAIN$A+1
	STA __MATH1+1
	LDA _MAIN$A+2
	STA __MATH1+2
	LDA _MAIN$A+3
	STA __MATH1+3
	LDA _MAIN$Z
	STA __MATH0
	LDA _MAIN$Z+1
	STA __MATH0+1
	LDA _MAIN$Z+2
	STA __MATH0+2
	LDA _MAIN$Z+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND32_BRANCH_9
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BEQ __ZAP_LAND32_BRANCH_9
	LDA #$01
	JMP __ZAP_LAND32_END_10
__ZAP_LAND32_BRANCH_9:
	LDA #$00
__ZAP_LAND32_END_10:
	STA __MATH0
	BNE __ZAP_endif_7
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 31:         result = result + 1
	INC _RESULT
__ZAP_endif_7:
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 35:     if a || z
	LDA _MAIN$Z
	STA __MATH1
	LDA _MAIN$Z+1
	STA __MATH1+1
	LDA _MAIN$Z+2
	STA __MATH1+2
	LDA _MAIN$Z+3
	STA __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	LDA _MAIN$A+1
	STA __MATH0+1
	LDA _MAIN$A+2
	STA __MATH0+2
	LDA _MAIN$A+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BNE __ZAP_LOR32_BRANCH_14
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BNE __ZAP_LOR32_BRANCH_14
	LDA #$00
	JMP __ZAP_LOR32_END_15
__ZAP_LOR32_BRANCH_14:
	LDA #$01
__ZAP_LOR32_END_15:
	STA __MATH0
	BEQ __ZAP_else_11
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 36:         result = result + 1
	INC _RESULT
__ZAP_else_11:
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 40:     if z || z
	LDA _MAIN$Z
	STA __MATH1
	LDA _MAIN$Z+1
	STA __MATH1+1
	LDA _MAIN$Z+2
	STA __MATH1+2
	LDA _MAIN$Z+3
	STA __MATH1+3
	LDA _MAIN$Z
	STA __MATH0
	LDA _MAIN$Z+1
	STA __MATH0+1
	LDA _MAIN$Z+2
	STA __MATH0+2
	LDA _MAIN$Z+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BNE __ZAP_LOR32_BRANCH_19
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BNE __ZAP_LOR32_BRANCH_19
	LDA #$00
	JMP __ZAP_LOR32_END_20
__ZAP_LOR32_BRANCH_19:
	LDA #$01
__ZAP_LOR32_END_20:
	STA __MATH0
	BNE __ZAP_endif_17
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 42:         result = result + 1
	INC _RESULT
__ZAP_endif_17:
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 46:     if larr[0] || larr[1]
	LDA _LARR+0
	STA __MATH0
	LDA _LARR+1
	STA __MATH0+1
	LDA _LARR+2
	STA __MATH0+2
	LDA _LARR+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BNE __ZAP_LOR_TRUE_24
	LDA _LARR+4
	STA __MATH0
	LDA _LARR+5
	STA __MATH0+1
	LDA _LARR+6
	STA __MATH0+2
	LDA _LARR+7
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BNE __ZAP_LOR_TRUE_24
	LDA #$00
	JMP __ZAP_LOR_END_25
__ZAP_LOR_TRUE_24:
	LDA #1
__ZAP_LOR_END_25:
	BEQ __ZAP_else_21
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 47:         result = result + 1
	INC _RESULT
__ZAP_else_21:
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 53:     if larr[1] && larr[1]
	LDA _LARR+4
	STA __MATH0
	LDA _LARR+5
	STA __MATH0+1
	LDA _LARR+6
	STA __MATH0+2
	LDA _LARR+7
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND_FALSE_29
	LDA _LARR+4
	STA __MATH0
	LDA _LARR+5
	STA __MATH0+1
	LDA _LARR+6
	STA __MATH0+2
	LDA _LARR+7
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND_FALSE_29
	LDA #1
	JMP __ZAP_LAND_END_30
__ZAP_LAND_FALSE_29:
	LDA #$00
__ZAP_LAND_END_30:
	BEQ __ZAP_else_26
; /home/dusan/src/ZAP-compiler/tests/pass/229-long-logical/229-long-logical.zap 54:         result = result + 1
	INC _RESULT
__ZAP_else_26:
	RTS


.segment "CODE"
; End of file