; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -6502 -O1 tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap -o tests/pass/111-logical-or-rpn/111-logical-or-rpn_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH_STACK            = __LVSLOT_5
__MATH0                 = __LVSLOT_6
__MATH1                 = __LVSLOT_7
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 1
__LVSLOT_4:	.res 1
__LVSLOT_5:	.res 32
__LVSLOT_6:	.res 4
__LVSLOT_7:	.res 4
; Byte variables
; ZP usage: 44 of 256 bytes ($00-$2B), 212 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$C                 = __LVSLOT_3
_MAIN$D                 = __LVSLOT_4
_MAIN$R                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap 4:     byte a = 5
	LDA #$05
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap 5:     byte b = 10
	LDA #$0A
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap 6:     byte c = 3
	LDA #$03
	STA _MAIN$C
; /home/dusan/src/ZAP-compiler/tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap 7:     byte d = 5
	LDA #$05
	STA _MAIN$D
; /home/dusan/src/ZAP-compiler/tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap 9:     byte r = (a > b) || (c < d)
	LDA _MAIN$A
	CMP _MAIN$B
	BCC __ZAP_CMP_END_2
	BNE __ZAP_CMP_TRUE_1
	LDA #$00
	JMP __ZAP_CMP_END_2
__ZAP_CMP_TRUE_1:
	LDA #$01
__ZAP_CMP_END_2:
	STA __MATH0
	STA __MATH_STACK+0
	LDA _MAIN$C
	CMP _MAIN$D
	BCC __ZAP_CMP_TRUE_3
	LDA #$00
	JMP __ZAP_CMP_END_4
__ZAP_CMP_TRUE_3:
	LDA #$01
__ZAP_CMP_END_4:
	STA __MATH0
	LDA __MATH_STACK+0
	STA __MATH1
	LDA __MATH0
	BNE __ZAP_OR_ONE_5
	LDA __MATH1
	BNE __ZAP_OR_ONE_5
	LDA #$00
	JMP __ZAP_OR_END_6
__ZAP_OR_ONE_5:
	LDA #$01
__ZAP_OR_END_6:
	STA __MATH0
	LDX #$00
	STA _MAIN$R
; /home/dusan/src/ZAP-compiler/tests/pass/111-logical-or-rpn/111-logical-or-rpn.zap 10:     result = r
	STA _RESULT
	RTS


.segment "CODE"
; End of file