; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/111-logical-or-rpn//111-logical-or-rpn.zap -o tests/pass/111-logical-or-rpn//111-logical-or-rpn_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH_STACK = __LVSLOT_5
__MATH0 = __LVSLOT_6
__MATH1 = __LVSLOT_7
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 1
__LVSLOT_4:	.res 1
__LVSLOT_5:	.res 32
__LVSLOT_6:	.res 4
__LVSLOT_7:	.res 4
; Byte variables
; ZP usage: 44 of 256 bytes ($00-$2B), 212 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\111-logical-or-rpn\111-logical-or-rpn.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_A = __LVSLOT_1
_MAIN_B = __LVSLOT_2
_MAIN_C = __LVSLOT_3
_MAIN_D = __LVSLOT_4
_MAIN_R = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\111-logical-or-rpn\111-logical-or-rpn.zap 4:     byte a = 5
	LDA #$05
	STA _MAIN_A
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\111-logical-or-rpn\111-logical-or-rpn.zap 5:     byte b = 10
	LDA #$0A
	STA _MAIN_B
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\111-logical-or-rpn\111-logical-or-rpn.zap 6:     byte c = 3
	LDA #$03
	STA _MAIN_C
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\111-logical-or-rpn\111-logical-or-rpn.zap 7:     byte d = 5
	LDA #$05
	STA _MAIN_D
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\111-logical-or-rpn\111-logical-or-rpn.zap 9:     byte r = (a > b) || (c < d)
	LDA _MAIN_A
	CMP _MAIN_B
	BCC __ZAP_CMP_END_2
	BNE __ZAP_CMP_TRUE_1
	LDA #$00
	JMP __ZAP_CMP_END_2
__ZAP_CMP_TRUE_1:
	LDA #$01
__ZAP_CMP_END_2:
	STA __MATH0
	STA __MATH_STACK+0
	LDA _MAIN_C
	CMP _MAIN_D
	BCC __ZAP_CMP_TRUE_3
	LDA #$00
	JMP __ZAP_CMP_END_4
__ZAP_CMP_TRUE_3:
	LDA #$01
__ZAP_CMP_END_4:
	STA __MATH0
	LDA __MATH_STACK+0
	STA __MATH1
	LDA __MATH0
	BNE __ZAP_OR_ONE_5
	LDA __MATH1
	BNE __ZAP_OR_ONE_5
	LDA #$00
	JMP __ZAP_OR_END_6
__ZAP_OR_ONE_5:
	LDA #$01
__ZAP_OR_END_6:
	STA __MATH0
	LDX #$00
	STA _MAIN_R
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\111-logical-or-rpn\111-logical-or-rpn.zap 10:     result = r
	STA _RESULT
	RTS


.segment "CODE"
; End of file