; Generated by Zap Compiler 0.9.4
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/101-explicit-values/101-explicit-values.zap -o /home/dusan/src/ZAP-compiler/tests/pass/101-explicit-values/101-explicit-values_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_MAIN$X                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/101-explicit-values/101-explicit-values.zap 10: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/101-explicit-values/101-explicit-values.zap 11:     byte x @40000 = E.B
	LDA #$02
	STA _MAIN$X
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file