; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/203-word-compare-const/203-word-compare-const.zap -o tests/pass/203-word-compare-const/203-word-compare-const_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_2:	.res 2
__LVSLOT_3:	.res 2
; Word variables
; ZP usage: 6 of 256 bytes ($00-$05), 250 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 6: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$I                 = __LVSLOT_1
_MAIN$COUNT             = __LVSLOT_2
_MAIN$FOR_END_1         = __LVSLOT_3
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 10:     word count = 0
	STZ _MAIN$COUNT
	STZ _MAIN$COUNT+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 14:     i = 256
	STZ _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 15:     if i < 512
	LDX _MAIN$I+1
	CPX #$02
	BCS __ZAP_else_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 16:         result += 1     ; +1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 20:     i = 768
	STZ _MAIN$I
	LDA #$03
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 21:     if i < 767
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_then_7
	BNE __ZAP_else_5
	LDA _MAIN$I
	CMP #$FF
	BCS __ZAP_else_5
__ZAP_then_7:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 22:         result += 100   ; should NOT happen
	LDA _RESULT
	CLC
	ADC #$64
	STA _RESULT
__ZAP_else_5:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 26:     i = 512
	STZ _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 27:     if i < 512
	LDX _MAIN$I+1
	CPX #$02
	BCS __ZAP_else_9
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 28:         result += 100
	LDA _RESULT
	CLC
	ADC #$64
	STA _RESULT
__ZAP_else_9:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 32:     i = 511
	LDA #$FF
	STA _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 33:     if i < 512
	LDX _MAIN$I+1
	CPX #$02
	BCS __ZAP_else_13
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 34:         result += 1     ; +2
	INC _RESULT
__ZAP_else_13:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 39:     i = 512
	STZ _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 40:     if i <= 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_then_19
	BNE __ZAP_else_17
__ZAP_then_19:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 41:         result += 1     ; +3
	INC _RESULT
__ZAP_else_17:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 45:     i = 512
	STZ _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 46:     if i <= 511
	LDX _MAIN$I+1
	CPX #$01
	BCC __ZAP_then_22
	BNE __ZAP_else_20
	LDA _MAIN$I
	CMP #$FF
	BCC __ZAP_then_22
	BNE __ZAP_else_20
__ZAP_then_22:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 47:         result += 100
	LDA _RESULT
	CLC
	ADC #$64
	STA _RESULT
__ZAP_else_20:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 51:     i = 511
	LDA #$FF
	STA _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 52:     if i <= 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_then_26
	BNE __ZAP_else_24
__ZAP_then_26:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 53:         result += 1     ; +4
	INC _RESULT
__ZAP_else_24:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 58:     i = 768
	STZ _MAIN$I
	LDA #$03
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 59:     if i > 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_else_27
	BNE __ZAP_then_29
	LDA _MAIN$I
	BEQ __ZAP_else_27
__ZAP_then_29:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 60:         result += 1     ; +5
	INC _RESULT
__ZAP_else_27:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 64:     i = 256
	STZ _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 65:     if i > 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_else_31
	BNE __ZAP_then_33
	LDA _MAIN$I
	BEQ __ZAP_else_31
__ZAP_then_33:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 66:         result += 100
	LDA _RESULT
	CLC
	ADC #$64
	STA _RESULT
__ZAP_else_31:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 70:     i = 512
	STZ _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 71:     if i > 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_else_35
	BNE __ZAP_then_37
	LDA _MAIN$I
	BEQ __ZAP_else_35
__ZAP_then_37:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 72:         result += 100
	LDA _RESULT
	CLC
	ADC #$64
	STA _RESULT
__ZAP_else_35:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 76:     i = 513
	LDA #$01
	STA _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 77:     if i > 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_else_39
	BNE __ZAP_then_41
	LDA _MAIN$I
	BEQ __ZAP_else_39
__ZAP_then_41:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 78:         result += 1     ; +6
	INC _RESULT
__ZAP_else_39:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 83:     i = 512
	STZ _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 84:     if i >= 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_else_43
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 85:         result += 1     ; +7
	INC _RESULT
__ZAP_else_43:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 89:     i = 256
	STZ _MAIN$I
	LDA #$01
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 90:     if i >= 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_else_46
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 91:         result += 100
	LDA _RESULT
	CLC
	ADC #$64
	STA _RESULT
__ZAP_else_46:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 95:     i = 513
	LDA #$01
	STA _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 96:     if i >= 512
	LDX _MAIN$I+1
	CPX #$02
	BCC __ZAP_else_49
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 97:         result += 1     ; +8
	INC _RESULT
__ZAP_else_49:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 102:     i = 512
	STZ _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 103:     if i == 512
	LDA _MAIN$I
	BNE __ZAP_else_52
	LDX _MAIN$I+1
	CPX #$02
	BNE __ZAP_else_52
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 104:         result += 1     ; +9
	INC _RESULT
__ZAP_else_52:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 108:     i = 513
	LDA #$01
	STA _MAIN$I
	LDA #$02
	STA _MAIN$I+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 109:     if i != 512
	LDA _MAIN$I
	BNE __ZAP_then_58
	LDX _MAIN$I+1
	CPX #$02
	BEQ __ZAP_else_56
__ZAP_then_58:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 110:         result += 1     ; +10
	INC _RESULT
__ZAP_else_56:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 115:     count = 0
	STZ _MAIN$COUNT
	STZ _MAIN$COUNT+1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 116:     for i = 0 to 300
	STZ _MAIN$I
	STZ _MAIN$I+1
	LDA #$2C
	STA _MAIN$FOR_END_1
	LDA #$01
	STA _MAIN$FOR_END_1+1
__ZAP_while_59:
	LDX _MAIN$I+1
	CPX _MAIN$FOR_END_1+1
	BCC __ZAP_while_body_61
	BNE __ZAP_endwhile_60
	LDA _MAIN$I
	CMP _MAIN$FOR_END_1
	BCS __ZAP_endwhile_60
__ZAP_while_body_61:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 117:         count += 1
	INC _MAIN$COUNT
	BNE __ZAP_INC_WORD_63
	INC _MAIN$COUNT+1
__ZAP_INC_WORD_63:
	INC _MAIN$I
	BNE __ZAP_while_59
	INC _MAIN$I+1
	JMP __ZAP_while_59
__ZAP_endwhile_60:
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 119:     if count == 300
	LDA _MAIN$COUNT
	CMP #$2C
	BNE __ZAP_else_65
	LDX _MAIN$COUNT+1
	CPX #$01
	BNE __ZAP_else_65
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/203-word-compare-const/203-word-compare-const.zap 120:         result += 1     ; +11
	INC _RESULT
__ZAP_else_65:
	RTS


.segment "CODE"
; End of file