; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/017-subtraction//017-subtraction.zap -o tests/pass/017-subtraction//017-subtraction_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\017-subtraction\017-subtraction.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_X = __LVSLOT_1
_MAIN_Y = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\017-subtraction\017-subtraction.zap 4:     byte x = 100
	LDA #$64
	STA _MAIN_X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\017-subtraction\017-subtraction.zap 5:     byte y = 50
	LDA #$32
	STA _MAIN_Y
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\017-subtraction\017-subtraction.zap 7:     result = x - y
	LDA _MAIN_X
	SEC
	SBC _MAIN_Y
	STA _RESULT
	RTS


.segment "CODE"
; End of file