; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/062-constants/062-constants.zap -o tests/pass/062-constants/062-constants_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Constants
_MAX_VALUE              = $64
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/062-constants/062-constants.zap 2: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/062-constants/062-constants.zap 4: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/062-constants/062-constants.zap 5:     byte x = MAX_VALUE
	LDA #$64
	STA _MAIN$X
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/062-constants/062-constants.zap 6:     result = x
	LDA _MAIN$X
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file