; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -6502 -O1 tests/pass/032-equality/032-equality.zap -o tests/pass/032-equality/032-equality_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
; Byte variables
; Word variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
_MAIN$Y                 = __LVSLOT_2
_MAIN$X1                = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 4:     byte x = 50
	LDA #$32
	STA _MAIN$X
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 5:     byte y = 50
	STA _MAIN$Y
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 6:     word x1 = 50
	STA _MAIN$X1
	LDA #$00
	STA _MAIN$X1+1
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 8:     if x == y
	LDA _MAIN$X
	CMP _MAIN$Y
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 9:         result = result + 1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 12:     if x == x1
	LDX #$00
	CPX _MAIN$X1+1
	BNE __ZAP_else_4
	LDA _MAIN$X
	CMP _MAIN$X1
	BNE __ZAP_else_4
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 13:         result = result + 16    
	LDA _RESULT
	CLC
	ADC #$10
	STA _RESULT
__ZAP_else_4:
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 16:     if x1 == y
	LDX _MAIN$X1+1
	BNE __ZAP_else_8
	LDA _MAIN$X1
	CMP _MAIN$Y
	BNE __ZAP_else_8
; /home/dusan/src/ZAP-compiler/tests/pass/032-equality/032-equality.zap 17:         result = result + $20
	LDA _RESULT
	CLC
	ADC #$20
	STA _RESULT
__ZAP_else_8:
	RTS


.segment "CODE"
; End of file