; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/037-structs-pointers/037-structs-pointers.zap -o tests/pass/037-structs-pointers/037-structs-pointers_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__TMP1:	.res 2
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_2:	.res 2
; Pointer variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 2
; Struct variables (BSS)


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/037-structs-pointers/037-structs-pointers.zap 6: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$P                 = __LVSLOT_1
_MAIN$PP                = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/037-structs-pointers/037-structs-pointers.zap 12:     pp = @p
	LDA #<_MAIN$P
	LDX #>_MAIN$P
	STA _MAIN$PP
	STX _MAIN$PP+1
; /home/dusan/src/ZAP-compiler/tests/pass/037-structs-pointers/037-structs-pointers.zap 13:     pp^.x = 3
	LDA #$03
	STA (_MAIN$PP)
; /home/dusan/src/ZAP-compiler/tests/pass/037-structs-pointers/037-structs-pointers.zap 14:     pp^.y = 4
	LDA #$04
	LDY #$01
	STA (_MAIN$PP),Y
; /home/dusan/src/ZAP-compiler/tests/pass/037-structs-pointers/037-structs-pointers.zap 16:     result = p.x + p.y
	LDA _MAIN$P
	STA __TMP1
	LDA _MAIN$P+1
	CLC
	ADC __TMP1
	STA _RESULT
	RTS


.segment "CODE"
; End of file