; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap -o tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT_AND_LO          = $0200
_RESULT_AND_HI          = $0201
_RESULT_OR_LO           = $0202
_RESULT_OR_HI           = $0203
_RESULT_XOR_LO          = $0204
_RESULT_XOR_HI          = $0205
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
; Byte variables
; Word variables
; ZP usage: 4 of 256 bytes ($00-$03), 252 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 12: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$W                 = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 16:     a = $FF
	LDA #$FF
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 17:     b = $FF
	LDA #$FF
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 18:     w = a & b
	LDA _MAIN$A
	AND _MAIN$B
	LDX #$00
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 19:     result_and_lo = low(w)
	LDA _MAIN$W
	STA _RESULT_AND_LO
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 20:     result_and_hi = high(w)
	LDA _MAIN$W+1
	STA _RESULT_AND_HI
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 22:     w = a | b
	LDA _MAIN$A
	ORA _MAIN$B
	LDX #$00
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 23:     result_or_lo = low(w)
	LDA _MAIN$W
	STA _RESULT_OR_LO
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 24:     result_or_hi = high(w)
	LDA _MAIN$W+1
	STA _RESULT_OR_HI
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 26:     w = a ^ b
	LDA _MAIN$A
	EOR _MAIN$B
	LDX #$00
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 27:     result_xor_lo = low(w)
	LDA _MAIN$W
	STA _RESULT_XOR_LO
; /home/dusan/src/ZAP-compiler/tests/pass/216-word-target-byte-bitwise/216-word-target-byte-bitwise.zap 28:     result_xor_hi = high(w)
	LDA _MAIN$W+1
	STA _RESULT_XOR_HI
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file