; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/010-while-loop/010-while-loop.zap -o tests/pass/010-while-loop/010-while-loop_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 2 of 256 bytes ($00-$01), 254 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/010-while-loop/010-while-loop.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$COUNT             = __LVSLOT_1
_MAIN$SUM               = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/010-while-loop/010-while-loop.zap 4:     byte count = 0
	STZ _MAIN$COUNT
; /home/dusan/src/ZAP-compiler/tests/pass/010-while-loop/010-while-loop.zap 5:     byte sum = 0
	STZ _MAIN$SUM
; /home/dusan/src/ZAP-compiler/tests/pass/010-while-loop/010-while-loop.zap 7:     while count < 10
__ZAP_while_1:
	LDA _MAIN$COUNT
	CMP #$0A
	BCS __ZAP_endwhile_2
; /home/dusan/src/ZAP-compiler/tests/pass/010-while-loop/010-while-loop.zap 8:         sum = sum + 1
	INC _MAIN$SUM
; /home/dusan/src/ZAP-compiler/tests/pass/010-while-loop/010-while-loop.zap 9:         count = count + 1
	INC _MAIN$COUNT
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; /home/dusan/src/ZAP-compiler/tests/pass/010-while-loop/010-while-loop.zap 12:     result = sum    ; result = 10
	LDA _MAIN$SUM
	STA _RESULT
	RTS


.segment "CODE"
; End of file