; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py tests/pass/109-comparison-rpn/109-comparison-rpn.zap -o tests/pass/109-comparison-rpn/109-comparison-rpn_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH_STACK            = __LVSLOT_4
__MATH0                 = __LVSLOT_5
__MATH1                 = __LVSLOT_6
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 1
__LVSLOT_4:	.res 32
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 4
; Byte variables
; ZP usage: 43 of 256 bytes ($00-$2A), 213 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/109-comparison-rpn/109-comparison-rpn.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/109-comparison-rpn/109-comparison-rpn.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$C                 = __LVSLOT_3
_MAIN$R                 = __LVSLOT_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/109-comparison-rpn/109-comparison-rpn.zap 4:     byte a = 10
	LDA #$0A
	STA _MAIN$A
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/109-comparison-rpn/109-comparison-rpn.zap 5:     byte b = 20
	LDA #$14
	STA _MAIN$B
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/109-comparison-rpn/109-comparison-rpn.zap 6:     byte c = 10
	LDA #$0A
	STA _MAIN$C
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/109-comparison-rpn/109-comparison-rpn.zap 8:     byte r = (a < b) + (a == c) + (b > c) + (a >= c)
	LDA _MAIN$A
	CMP _MAIN$B
	BCC __ZAP_CMP_TRUE_1
	LDA #$00
	JMP __ZAP_CMP_END_2
__ZAP_CMP_TRUE_1:
	LDA #$01
__ZAP_CMP_END_2:
	STA __MATH0
	LDA __MATH0
	STA __MATH_STACK+0
	LDA _MAIN$A
	CMP _MAIN$C
	BEQ __ZAP_CMP_TRUE_3
	LDA #$00
	JMP __ZAP_CMP_END_4
__ZAP_CMP_TRUE_3:
	LDA #$01
__ZAP_CMP_END_4:
	STA __MATH0
	LDA __MATH_STACK+0
	STA __MATH1
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0
	STA __MATH_STACK+0
	LDA _MAIN$B
	CMP _MAIN$C
	BCC __ZAP_CMP_END_6
	BNE __ZAP_CMP_TRUE_5
	LDA #$00
	JMP __ZAP_CMP_END_6
__ZAP_CMP_TRUE_5:
	LDA #$01
__ZAP_CMP_END_6:
	STA __MATH0
	LDA __MATH_STACK+0
	STA __MATH1
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0
	STA __MATH_STACK+1
	LDA _MAIN$A
	CMP _MAIN$C
	BCS __ZAP_CMP_TRUE_7
	LDA #$00
	JMP __ZAP_CMP_END_8
__ZAP_CMP_TRUE_7:
	LDA #$01
__ZAP_CMP_END_8:
	STA __MATH0
	LDA __MATH_STACK+1
	STA __MATH1
	LDA __MATH0
	CLC
	ADC __MATH1
	STA __MATH0
	LDA __MATH0
	LDX #$00
	STA _MAIN$R
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/109-comparison-rpn/109-comparison-rpn.zap 9:     result = r
	LDA _MAIN$R
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file