; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/102-word-range/102-word-range.zap -o tests/pass/102-word-range/102-word-range_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_MAIN$X                 = $9C40
_MAIN$Y                 = $9C42
_MAIN$Z                 = $9C44
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/102-word-range/102-word-range.zap 13:     word x @40000 = Big.B
	LDA #$2D
	LDX #$01
	STA _MAIN$X
	STX _MAIN$X+1
; /home/dusan/src/ZAP-compiler/tests/pass/102-word-range/102-word-range.zap 14:     word y @40002 = Big.A
	LDA #$2C
	STA _MAIN$Y
	STX _MAIN$Y+1
; /home/dusan/src/ZAP-compiler/tests/pass/102-word-range/102-word-range.zap 15:     word z @40004 = Big.C
	LDA #$FF
	STA _MAIN$Z
	STA _MAIN$Z+1
	RTS


.segment "CODE"
; End of file