; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default_6502_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 2
__LVSLOT_4:	.res 4
; Byte variables
; Word variables
; Long variables
; ZP usage: 8 of 256 bytes ($00-$07), 248 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 21: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$BVAL              = __LVSLOT_1
_MAIN$HIT               = __LVSLOT_2
_MAIN$WVAL              = __LVSLOT_3
_MAIN$LVAL              = __LVSLOT_4
_MAIN$CNT               = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 31:     bval = 5
	LDA #$05
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 32:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 33:     switch bval
	LDA _MAIN$BVAL
	CMP #$05
	BNE __ZAP_endswitch_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 35:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 36:             break
__ZAP_endswitch_1:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 38:     if hit == 1
	LDA _MAIN$HIT
	CMP #$01
	BNE __ZAP_else_4
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 39:         result = result + 1     ; 1
	INC _RESULT
__ZAP_else_4:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 43:     bval = 7
	LDA #$07
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 44:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 45:     switch bval
	LDA _MAIN$BVAL
	CMP #$05
	BNE __ZAP_endswitch_7
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 47:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 48:             break
__ZAP_endswitch_7:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 50:     if hit == 0
	LDA _MAIN$HIT
	BNE __ZAP_else_10
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 51:         result = result + 1     ; 2
	INC _RESULT
__ZAP_else_10:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 55:     wval = 1000
	LDA #$E8
	STA _MAIN$WVAL
	LDA #$03
	STA _MAIN$WVAL+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 56:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 57:     switch wval
	LDA _MAIN$WVAL+1
	CMP #$03
	BNE __ZAP_endswitch_13
	LDA _MAIN$WVAL
	CMP #$E8
	BNE __ZAP_endswitch_13
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 59:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 60:             break
__ZAP_endswitch_13:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 62:     if hit == 1
	LDA _MAIN$HIT
	CMP #$01
	BNE __ZAP_else_16
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 63:         result = result + 1     ; 3
	INC _RESULT
__ZAP_else_16:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 67:     wval = 999
	LDA #$E7
	STA _MAIN$WVAL
	LDA #$03
	STA _MAIN$WVAL+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 68:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 69:     switch wval
	LDA _MAIN$WVAL+1
	CMP #$03
	BNE __ZAP_endswitch_19
	LDA _MAIN$WVAL
	CMP #$E8
	BNE __ZAP_endswitch_19
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 71:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 72:             break
__ZAP_endswitch_19:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 74:     if hit == 0
	LDA _MAIN$HIT
	BNE __ZAP_else_22
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 75:         result = result + 1     ; 4
	INC _RESULT
__ZAP_else_22:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 79:     lval = 131072
	LDA #$00
	STA _MAIN$LVAL
	STA _MAIN$LVAL+1
	STA _MAIN$LVAL+3
	LDA #$02
	STA _MAIN$LVAL+2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 80:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 81:     switch lval
	LDA _MAIN$LVAL+3
	BNE __ZAP_endswitch_25
	LDA _MAIN$LVAL+2
	CMP #$02
	BNE __ZAP_endswitch_25
	LDA _MAIN$LVAL+1
	BNE __ZAP_endswitch_25
	LDA _MAIN$LVAL
	BNE __ZAP_endswitch_25
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 83:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 84:             break
__ZAP_endswitch_25:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 86:     if hit == 1
	LDA _MAIN$HIT
	CMP #$01
	BNE __ZAP_else_28
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 87:         result = result + 1     ; 5
	INC _RESULT
__ZAP_else_28:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 91:     lval = 131071
	LDA #$FF
	STA _MAIN$LVAL
	STA _MAIN$LVAL+1
	LDA #$01
	STA _MAIN$LVAL+2
	LDA #$00
	STA _MAIN$LVAL+3
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 92:     hit = 0
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 93:     switch lval
	LDA _MAIN$LVAL+3
	BNE __ZAP_endswitch_31
	LDA _MAIN$LVAL+2
	CMP #$02
	BNE __ZAP_endswitch_31
	LDA _MAIN$LVAL+1
	BNE __ZAP_endswitch_31
	LDA _MAIN$LVAL
	BNE __ZAP_endswitch_31
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 95:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 96:             break
__ZAP_endswitch_31:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 98:     if hit == 0
	LDA _MAIN$HIT
	BNE __ZAP_else_34
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 99:         result = result + 1     ; 6
	INC _RESULT
__ZAP_else_34:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 103:     bval = 10
	LDA #$0A
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 104:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 105:     switch bval
	LDA _MAIN$BVAL
	CMP #$0A
	BEQ __ZAP_case_38
	LDA _MAIN$BVAL
	CMP #$14
	BNE __ZAP_endswitch_37
__ZAP_case_38:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 108:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 109:             break
__ZAP_endswitch_37:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 111:     if hit == 1
	LDA _MAIN$HIT
	CMP #$01
	BNE __ZAP_else_41
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 112:         result = result + 1     ; 7
	INC _RESULT
__ZAP_else_41:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 116:     bval = 20
	LDA #$14
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 117:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 118:     switch bval
	LDA _MAIN$BVAL
	CMP #$0A
	BEQ __ZAP_case_45
	LDA _MAIN$BVAL
	CMP #$14
	BNE __ZAP_endswitch_44
__ZAP_case_45:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 121:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 122:             break
__ZAP_endswitch_44:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 124:     if hit == 1
	LDA _MAIN$HIT
	CMP #$01
	BNE __ZAP_else_48
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 125:         result = result + 1     ; 8
	INC _RESULT
__ZAP_else_48:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 129:     bval = 30
	LDA #$1E
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 130:     hit = 0
	LDA #$00
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 131:     switch bval
	LDA _MAIN$BVAL
	CMP #$0A
	BEQ __ZAP_case_52
	LDA _MAIN$BVAL
	CMP #$14
	BNE __ZAP_endswitch_51
__ZAP_case_52:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 134:             hit = 1
	LDA #$01
	STA _MAIN$HIT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 135:             break
__ZAP_endswitch_51:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 137:     if hit == 0
	LDA _MAIN$HIT
	BNE __ZAP_else_55
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 138:         result = result + 1     ; 9
	INC _RESULT
__ZAP_else_55:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 142:     bval = 1
	LDA #$01
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 143:     cnt = 0
	LDA #$00
	STA _MAIN$CNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 144:     switch bval
	LDA _MAIN$BVAL
	CMP #$01
	BEQ __ZAP_case_59
	LDA _MAIN$BVAL
	CMP #$02
	BNE __ZAP_endswitch_58
	JMP __ZAP_case_60
__ZAP_case_59:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 146:             cnt = cnt + 1
	INC _MAIN$CNT
__ZAP_case_60:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 148:             cnt = cnt + 1
	INC _MAIN$CNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 149:             break
__ZAP_endswitch_58:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 151:     if cnt == 2
	LDA _MAIN$CNT
	CMP #$02
	BNE __ZAP_else_63
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 152:         result = result + 1     ; 10
	INC _RESULT
__ZAP_else_63:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 156:     bval = 2
	LDA #$02
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 157:     cnt = 0
	LDA #$00
	STA _MAIN$CNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 158:     switch bval
	LDA _MAIN$BVAL
	CMP #$01
	BEQ __ZAP_case_67
	LDA _MAIN$BVAL
	CMP #$02
	BNE __ZAP_endswitch_66
	JMP __ZAP_case_68
__ZAP_case_67:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 160:             cnt = cnt + 1
	INC _MAIN$CNT
__ZAP_case_68:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 162:             cnt = cnt + 1
	INC _MAIN$CNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 163:             break
__ZAP_endswitch_66:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 165:     if cnt == 1
	LDA _MAIN$CNT
	CMP #$01
	BNE __ZAP_else_71
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 166:         result = result + 1     ; 11
	INC _RESULT
__ZAP_else_71:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 170:     bval = 3
	LDA #$03
	STA _MAIN$BVAL
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 171:     cnt = 0
	LDA #$00
	STA _MAIN$CNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 172:     switch bval
	LDA _MAIN$BVAL
	CMP #$01
	BEQ __ZAP_case_75
	LDA _MAIN$BVAL
	CMP #$02
	BNE __ZAP_endswitch_74
	JMP __ZAP_case_76
__ZAP_case_75:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 174:             cnt = cnt + 1
	INC _MAIN$CNT
__ZAP_case_76:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 176:             cnt = cnt + 1
	INC _MAIN$CNT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 177:             break
__ZAP_endswitch_74:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 179:     if cnt == 0
	LDA _MAIN$CNT
	BNE __ZAP_else_79
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\150-switch-no-default\150-switch-no-default.zap 180:         result = result + 1     ; 12
	INC _RESULT
__ZAP_else_79:
	RTS


.segment "CODE"
; End of file