; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/053-control-flow-break//053-control-flow-break.zap -o tests/pass/053-control-flow-break//053-control-flow-break_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\053-control-flow-break\053-control-flow-break.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_I = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\053-control-flow-break\053-control-flow-break.zap 4:     byte i = 0
	STZ _MAIN_I
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\053-control-flow-break\053-control-flow-break.zap 6:     while i < 10
__ZAP_while_1:
	LDA _MAIN_I
	CMP #$0A
	BCS __ZAP_endwhile_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\053-control-flow-break\053-control-flow-break.zap 7:         if i == 5
	LDA _MAIN_I
	CMP #$05
	BEQ __ZAP_endwhile_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\053-control-flow-break\053-control-flow-break.zap 8:             break
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\053-control-flow-break\053-control-flow-break.zap 10:         i = i + 1
	INC _MAIN_I
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\053-control-flow-break\053-control-flow-break.zap 13:     result = i
	LDA _MAIN_I
	STA _RESULT
	RTS


.segment "CODE"
; End of file