; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -6502 -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef_6502_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap 4: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap 9:     result = result + 1
	INC _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap 14:     result = result + 1
	INC _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap 22:     result = result + 1     ; 3
	INC _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap 26:     result = result + 1     ; 4
	INC _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap 31:     result = result + 1     ; 5
	INC _RESULT
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\091-define-ifdef\091-define-ifdef.zap 36:     result = result + 1     ; 6
	INC _RESULT
	RTS


.segment "CODE"
; End of file