; Generated by Zap Compiler
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\009-arrays-inferred-size\009-arrays-inferred-size.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\009-arrays-inferred-size\009-arrays-inferred-size_default.s
; ==============================

.DEBUGINFO +  ; Enable debug information for symbol names

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2

; Fixed-address variables
_RESULT = $9C40

; Byte variables
_MAIN_SUM:	.res 1

.segment "BSS"
; Array variables (BSS)
_MAIN_ARR:	.res 5

.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\009-arrays-inferred-size\009-arrays-inferred-size.zap 1: word result @40000 = 0
	STZ _RESULT
	STZ _RESULT+1

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\009-arrays-inferred-size\009-arrays-inferred-size.zap 3: proc main()
; -- Procedure MAIN --
MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\009-arrays-inferred-size\009-arrays-inferred-size.zap 4:     byte arr[] = {10, 20, 30, 40, 50}
	; Copy array [10, 20, 30, 40, 50] (5 elements)
	LDX #0
ARR_COPY_1:
	LDA ARRAY_DATA_1,X
	STA _MAIN_ARR,X
	INX
	CPX #5
	BNE ARR_COPY_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\009-arrays-inferred-size\009-arrays-inferred-size.zap 8:     sum = arr[0] + arr[1] + arr[2] + arr[3] + arr[4]
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #0
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #1
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	CLC
	ADC TMP1
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #2
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	CLC
	ADC TMP1
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #3
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	CLC
	ADC TMP1
	STA TMP1
	STX TMP1+1
	LDA #<_MAIN_ARR
	LDX #>_MAIN_ARR
	STA TMP0
	STX TMP0+1
	LDA #4
	LDX #0
	CLC
	ADC TMP0
	STA TMP0
	TXA
	ADC TMP0+1
	STA TMP0+1
	LDY #0
	LDA (TMP0),Y
	LDX #0
	CLC
	ADC TMP1
	STA _MAIN_SUM
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\009-arrays-inferred-size\009-arrays-inferred-size.zap 11:     result = sum
	LDA _MAIN_SUM
	LDX #0
	LDX #0
	STA _RESULT
	STX _RESULT+1
	RTS

.segment "CODE"
; ------------------------------
; Constant Data
; ------------------------------
ARRAY_DATA_1:
	.byte $0A, $14, $1E, $28, $32

__END:
.export __END

; End of file