; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/019-arrays-inferred-size/019-arrays-inferred-size.zap -o tests/pass/019-arrays-inferred-size/019-arrays-inferred-size_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_2:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free
; ---------------------------------------------------------------------------


.segment "BSS"
; Shared slots (BSS)
__LVSLOT_1:	.res 5
; Arrays (BSS)


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/019-arrays-inferred-size/019-arrays-inferred-size.zap 1: word result @40000 = 0
	LDA #$00
	STA _RESULT
	STA _RESULT+1
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/019-arrays-inferred-size/019-arrays-inferred-size.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$ARR               = __LVSLOT_1
_MAIN$SUM               = __LVSLOT_2
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/019-arrays-inferred-size/019-arrays-inferred-size.zap 4:     byte arr[] = {10, 20, 30, 40, 50}
	; Copy array [10, 20, 30, 40, 50] (5 elements)
	LDX #$00
__ZAP_ARR_COPY_1:
	LDA __ARRAY_DATA_1,X
	STA _MAIN$ARR,X
	INX
	CPX #5
	BNE __ZAP_ARR_COPY_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/019-arrays-inferred-size/019-arrays-inferred-size.zap 8:     sum = arr[0] + arr[1] + arr[2] + arr[3] + arr[4]
	LDA _MAIN$ARR+0
	CLC
	ADC _MAIN$ARR+1
	CLC
	ADC _MAIN$ARR+2
	CLC
	ADC _MAIN$ARR+3
	CLC
	ADC _MAIN$ARR+4
	STA _MAIN$SUM
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/019-arrays-inferred-size/019-arrays-inferred-size.zap 11:     result = sum
	LDA _MAIN$SUM
	LDX #$00
	STA _RESULT
	STX _RESULT+1
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; ---------------------------------------------------------------------------
; Constant Data
__ARRAY_DATA_1:
	.byte $0A, $14, $1E, $28, $32
; End of file