; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/092-struct-field-pass//092-struct-field-pass.zap -o tests/pass/092-struct-field-pass//092-struct-field-pass_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_VIA1 = $9C40
; Byte variables
_X:	.res 1
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; ------------------------------
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\092-struct-field-pass\092-struct-field-pass.zap 12:     x = VIA1.ORB    ; read-only field: read allowed
	LDA _VIA1
	STA _X
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\092-struct-field-pass\092-struct-field-pass.zap 13:     VIA1.ORA = $02  ; write-only field: write allowed
	LDA #$02
	STA _VIA1+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\092-struct-field-pass\092-struct-field-pass.zap 14:     VIA1.DDRB = VIA1.DDRB & %01001111
	LDA _VIA1+2
	LDX #$00
	AND #$4F
	STA _VIA1+2
	RTS


.segment "CODE"
; End of file