; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap -o /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 1
__LVSLOT_3:	.res 1
; Byte variables
; ZP usage: 3 of 256 bytes ($00-$02), 253 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$SUM               = __LVSLOT_3
; /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap 4:     byte a = 100
	LDA #$64
	STA _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap 5:     byte b = 50
	LDA #$32
	STA _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap 6:     byte sum = 0
	STZ _MAIN$SUM
; /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap 8:     sum = a + b
	LDA _MAIN$A
	CLC
	ADC _MAIN$B
	STA _MAIN$SUM
; /home/dusan/src/ZAP-compiler/tests/pass/016-comparison-operators/016-comparison-operators.zap 9:     result = sum
	LDA _MAIN$SUM
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file