; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap -o /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Byte variables
_HELPER$A:	.res 1
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap 4: byte result @40000 = 0
	STZ _RESULT
	LDA #$01
	STA _HELPER$A
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Function HELPER --
_HELPER:
; /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap 9:     a = a + 1
	INC _HELPER$A
; /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap 10:     return a
	LDA _HELPER$A
	RTS


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap 14: proc main()
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap 15:     result = helper()
	JSR _HELPER
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap 16:     result = helper()
	JSR _HELPER
	STA _RESULT
; /home/dusan/src/ZAP-compiler/tests/pass/077-static/077-static.zap 17:     result = helper()    
	JSR _HELPER
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file