; Generated by Zap Compiler 0.9.4
; Command: C:\Users\dusan.holub\AppData\Local\Python\pythoncore-3.14-64\python.exe compiler.py -O1 C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\052-assignment-chain\052-assignment-chain.zap -o C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\052-assignment-chain\052-assignment-chain_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\052-assignment-chain\052-assignment-chain.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\052-assignment-chain\052-assignment-chain.zap 4:     byte a = 5
	LDA #$05
	STA _MAIN$A
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\052-assignment-chain\052-assignment-chain.zap 5:     byte b = a
	STA _MAIN$B
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\052-assignment-chain\052-assignment-chain.zap 6:     result = b
	STA _RESULT
	RTS


.segment "CODE"
; End of file