; Generated by Zap Compiler 0.9.4
; Command: /usr/bin/python3 compiler.py tests/pass/052-assignment-chain/052-assignment-chain.zap -o tests/pass/052-assignment-chain/052-assignment-chain_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
; Byte variables
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
; Globals initialization
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/052-assignment-chain/052-assignment-chain.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/052-assignment-chain/052-assignment-chain.zap 3: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_1
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/052-assignment-chain/052-assignment-chain.zap 4:     byte a = 5
	LDA #$05
	STA _MAIN$A
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/052-assignment-chain/052-assignment-chain.zap 5:     byte b = a
	LDA _MAIN$A
	STA _MAIN$B
; /home/dusan/src/Ex65C02SBC_G3/ZAP-compiler/tests/pass/052-assignment-chain/052-assignment-chain.zap 6:     result = b
	LDA _MAIN$B
	STA _RESULT
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file