; Generated by Zap Compiler 0.9.2
; Command: C:\Users\dusan.holub\src\ZAP-compiler\.venv\Scripts\python.exe compiler.py -O1 tests/pass/028-address-of-operator//028-address-of-operator.zap -o tests/pass/028-address-of-operator//028-address-of-operator_t.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 2
; Pointer variables
; Byte variables
; ZP usage: 3 of 256 bytes ($00-$02), 253 free


.segment "CODE"
; Globals initialization
; ------------------------------
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\028-address-of-operator\028-address-of-operator.zap 1: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
; ------------------------------
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN_DATA = __LVSLOT_1
_MAIN_P = __LVSLOT_2
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\028-address-of-operator\028-address-of-operator.zap 4:     byte data = 5
	LDA #$05
	STA _MAIN_DATA
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\028-address-of-operator\028-address-of-operator.zap 7:     p = @data
	LDA #<_MAIN_DATA
	LDX #>_MAIN_DATA
	STA _MAIN_P
	STX _MAIN_P+1
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\028-address-of-operator\028-address-of-operator.zap 8:     p^ = 12
	LDA #$0C
	STA (_MAIN_P)
; C:\Users\dusan.holub\src\ZAP-compiler\tests\pass\028-address-of-operator\028-address-of-operator.zap 9:     result = data
	LDA _MAIN_DATA
	STA _RESULT
	RTS


.segment "CODE"
; End of file