; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -6502 -O1 tests/pass/028-address-of-operator/028-address-of-operator.zap -o tests/pass/028-address-of-operator/028-address-of-operator_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 1
__LVSLOT_2:	.res 2
; Pointer variables
; Byte variables
; ZP usage: 3 of 256 bytes ($00-$02), 253 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/028-address-of-operator/028-address-of-operator.zap 1: byte result @40000 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$DATA              = __LVSLOT_1
_MAIN$P                 = __LVSLOT_2
; /home/dusan/src/ZAP-compiler/tests/pass/028-address-of-operator/028-address-of-operator.zap 4:     byte data = 5
	LDA #$05
	STA _MAIN$DATA
; /home/dusan/src/ZAP-compiler/tests/pass/028-address-of-operator/028-address-of-operator.zap 7:     p = @data
	LDA #<_MAIN$DATA
	LDX #>_MAIN$DATA
	STA _MAIN$P
	STX _MAIN$P+1
; /home/dusan/src/ZAP-compiler/tests/pass/028-address-of-operator/028-address-of-operator.zap 8:     p^ = 12
	LDA #$0C
	LDY #$00
	STA (_MAIN$P),Y
; /home/dusan/src/ZAP-compiler/tests/pass/028-address-of-operator/028-address-of-operator.zap 9:     result = data
	LDA _MAIN$DATA
	STA _RESULT
	RTS


.segment "CODE"
; End of file