; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/python_venv/bin/python3 compiler.py -6502 tests/pass/208-pure-asm-proc/208-pure-asm-proc.zap -o tests/pass/208-pure-asm-proc/208-pure-asm-proc_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; ZP usage: 0 of 256 bytes ($00-$00), 256 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/208-pure-asm-proc/208-pure-asm-proc.zap 5: proc NMI_HANDLER() #keep #asm #NOEXPORT
; -- Procedure NMI_HANDLER --
_NMI_HANDLER:
; ASM_BLOCK_BEGIN
	; NMI handler stub
	rti
; ASM_BLOCK_END
	.segment "CODE"


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/208-pure-asm-proc/208-pure-asm-proc.zap 10: proc IRQ_HANDLER() #keep #asm
; -- Procedure IRQ_HANDLER --
_IRQ_HANDLER:
; ASM_BLOCK_BEGIN
	rti
; ASM_BLOCK_END
	.segment "CODE"


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/208-pure-asm-proc/208-pure-asm-proc.zap 14: proc main()
; -- Procedure MAIN --
_MAIN:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file