; Generated by Zap Compiler
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/test_variables_optimiz.zap -o tests/pass/test_variables_optimiz-6502.s
; ------------------------------

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2

; Byte variables
_TEST1_P1:	.res 1
_TEST1_P2:	.res 1
_TEST1_T1:	.res 1
_MAIN_A1:	.res 1
; Word variables
_TEST2_B1:	.res 2
_TEST2_B2:	.res 2
_TEST2_T1:	.res 2
_TEST3_B1:	.res 2
_TEST3_B2:	.res 2
_TEST3_T1:	.res 2
_MAIN_B1:	.res 2

.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 7: proc test1(byte p1, byte p2)
; -- Procedure TEST1 --
TEST1:
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 9:     t1 = p1 + p2
	LDA _TEST1_P1
	LDX #0
	STA TMP0
	STX TMP1
	LDA _TEST1_P2
	LDX #0
	CLC
	ADC TMP0
	STA _TEST1_T1
	RTS
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 13: proc test2(word b1, word b2)
; -- Procedure TEST2 --
TEST2:
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 15:     t1 = b1 + b2
	LDA _TEST2_B1
	CLC
	ADC _TEST2_B2
	STA _TEST2_T1
	LDA _TEST2_B1+1
	ADC _TEST2_B2+1
	STA _TEST2_T1+1
	RTS
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 19: proc test3(word b1, word b2)
; -- Procedure TEST3 --
TEST3:
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 22:     t1 = b1 - b2
	LDA _TEST3_B1
	SEC
	SBC _TEST3_B2
	STA _TEST3_T1
	LDA _TEST3_B1+1
	SBC _TEST3_B2+1
	STA _TEST3_T1+1
	RTS
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 28: proc main()
; -- Procedure MAIN --
MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 32:     a1 = a4 + a5 + 2
	LDA #$66
	STA _MAIN_A1
	LDA _MAIN_A1
	LDX #0
	STA _TEST1_P1
	LDA #3
	STA _TEST1_P2
	JSR TEST1
	LDA _MAIN_A1
	LDX #0
	STA _TEST2_B1
	LDX #0
	STX _TEST2_B1+1
	LDA #4
	STA _TEST2_B2
	LDX #0
	STX _TEST2_B2+1
	JSR TEST2
; /home/dusan/src/ZAP-compiler/tests/pass/test_variables_optimiz.zap 38:     b1 = a4 + a5 + 5
	LDA #$69
	STA _MAIN_B1
	LDA #0
	STA _MAIN_B1+1
	LDA #10
	STA _TEST3_B1
	LDX #0
	STX _TEST3_B1+1
	LDA #6
	STA _TEST3_B2
	LDX #0
	STX _TEST3_B2+1
	JSR TEST3
	LDA #10
	STA _TEST3_B1
	LDX #0
	STX _TEST3_B1+1
	LDA #7
	STA _TEST3_B2
	LDX #0
	STX _TEST3_B2+1
	JSR TEST3
	LDA _MAIN_A1
	LDX #0
	STA _TEST3_B1
	LDX #0
	STX _TEST3_B1+1
	LDA #8
	STA _TEST3_B2
	LDX #0
	STX _TEST3_B2+1
	JSR TEST3
	LDA _MAIN_A1
	LDX #0
	STA _TEST2_B1
	LDX #0
	STX _TEST2_B1+1
	LDA #9
	STA _TEST2_B2
	LDX #0
	STX _TEST2_B2+1
	JSR TEST2
	LDA _MAIN_B1
	LDX _MAIN_B1+1
	STA _TEST1_P1
	LDA #210
	LDX #4
	STA _TEST1_P2
	JSR TEST1
	RTS

.segment "CODE"
__END:
.export __END

; End of file