; Generated by Zap Compiler
; Command: /usr/bin/python3 compiler.py -6502 tests/pass/test_math_1.zap -o tests/pass/test_math_1-6502.s
; ------------------------------

.segment "ZEROPAGE"
; System variables
TMP0:	.res 2
TMP1:	.res 2
TMP2:	.res 4
TMP3:	.res 2

; Byte variables
_MATH1_B1:	.res 1
_MATH1_B2:	.res 1
_MATH1_R:	.res 1
_MATH1_A:	.res 1
_MATH1_B:	.res 1
_MATH2_B1:	.res 1
_MATH2_B2:	.res 1
; Word variables
_MATH2_R:	.res 2
_MATH2_A:	.res 2
_MATH2_B:	.res 2

.segment "CODE"
; Globals initialization
; ------------------------------
__START:
.export __START

; Call MAIN
; ------------------------------
	JSR MAIN
	JMP *

; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 8: proc math1(byte b1, byte b2)
; -- Procedure MATH1 --
MATH1:
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 11:     r = b1 + 0
	LDA _MATH1_B1
	LDX #0
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 12:     r = b1 - 0
	LDA _MATH1_B1
	LDX #0
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 13:     r = b1 + 1
	LDA _MATH1_B1
	CLC
	ADC #1
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 14:     r = b1 - 1
	LDA _MATH1_B1
	SEC
	SBC #1
	STA _MATH1_R
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 15:     b = c1
	LDA #$03
	STA _MATH1_B
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 16:     a = r + 3 * b * (r + 1)
	LDA _MATH1_R
	LDX #0
	STA TMP0
	STX TMP1
	LDA #3
	STA TMP0
	STX TMP1
	LDA _MATH1_B
	LDX #0
	STA TMP2
	STX TMP3
	JSR MUL8
	STA TMP0
	STX TMP1
	LDA _MATH1_R
	LDX #0
	STA TMP0
	STX TMP1
	LDA #1
	CLC
	ADC TMP0
	STA TMP2
	STX TMP3
	JSR MUL8
	CLC
	ADC TMP0
	STA _MATH1_A
	RTS
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 20: proc math2(byte b1, byte b2)
; -- Procedure MATH2 --
MATH2:
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 23:     r = b1 + 0
	LDA _MATH2_B1
	LDX #0
	STA _MATH2_R
	STX _MATH2_R+1
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 24:     r = b1 - 0
	LDA _MATH2_B1
	LDX #0
	STA _MATH2_R
	STX _MATH2_R+1
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 25:     r = b1 + 1
	LDA _MATH2_B1
	LDX #0
	STA TMP0
	STX TMP1
	LDA #1
	CLC
	ADC TMP0
	STA _MATH2_R
	STX _MATH2_R+1
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 26:     r = b1 - 1
	LDA _MATH2_B1
	LDX #0
	STA TMP0
	STX TMP1
	LDA #1
	STA TMP2
	SEC
	LDA TMP0
	SBC TMP2
	STA _MATH2_R
	STX _MATH2_R+1
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 27:     b = c1
	LDA #$03
	STA _MATH2_B
	LDA #0
	STA _MATH2_B+1
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 28:     a = r + 3 * b * (r + 1)
	LDA _MATH2_R
	LDX _MATH2_R+1
	STA TMP0
	STX TMP1
	LDA #3
	STA TMP0
	STX TMP1
	LDA _MATH2_B
	LDX _MATH2_B+1
	STA TMP2
	STX TMP3
	LDA TMP2
	LDX TMP3
	STA TMP0
	STX TMP1
	JSR MUL16_8
	STA TMP0
	STX TMP1
	LDA _MATH2_R
	LDX _MATH2_R+1
	STA TMP0
	STX TMP1
	LDA #1
	CLC
	ADC TMP0
	TAY
	TXA
	ADC TMP1
	TAX
	TYA
	STA TMP2
	STX TMP3
	JSR MUL16
	CLC
	ADC TMP0
	TAY
	TXA
	ADC TMP1
	TAX
	TYA
	STA _MATH2_A
	STX _MATH2_A+1
	RTS
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 32: proc main()
; -- Procedure MAIN --
MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 33:     math1(1, 2)    
	LDA #1
	STA _MATH1_B1
	LDA #2
	STA _MATH1_B2
	JSR MATH1
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 34:     math1($ff01, $5502)
	LDA #1
	LDX #255
	STA _MATH1_B1
	LDA #2
	LDX #85
	STA _MATH1_B2
	JSR MATH1
; /home/dusan/src/ZAP-compiler/tests/pass/test_math_1.zap 35:     math2(1, 2)
	LDA #1
	STA _MATH2_B1
	LDA #2
	STA _MATH2_B2
	JSR MATH2
	RTS

.segment "CODE"
; ------------------------------
; Math Runtime Routines
; ------------------------------

; MUL8: 8x8=16 multiply
; Input: TMP0 (multiplicand), TMP2 (multiplier)
; Output: A=low, X=high
MUL8:
	LDA #0
	LDX #8
	CLC
MUL8_LOOP:
	ROR TMP2
	BCC MUL8_SKIP
	CLC
	ADC TMP0
MUL8_SKIP:
	ROR
	ROR TMP3
	DEX
	BNE MUL8_LOOP
	TAX
	LDA TMP3
	RTS

; MUL16_8: 16x8=16 multiply
; Input: TMP0,TMP1 (multiplicand), TMP2 (multiplier)
; Output: A=low, X=high
MUL16_8:
	LDA TMP0
	STA TMP3
	LDA TMP1
	PHA
	LDA TMP2
	STA TMP0
	LDA TMP3
	STA TMP2
	JSR MUL8
	STA TMP3
	STX TMP0
	PLA
	STA TMP2
	JSR MUL8
	CLC
	ADC TMP0
	TAX
	LDA TMP3
	RTS

; MUL16: 16x16=16 multiply
; Input: TMP0,TMP1 (multiplicand), TMP2,TMP3 (multiplier)
; Output: A=low, X=high
MUL16:
	LDA #0
	STA TMP2+2
	LDX #16
MUL16_LOOP:
	LSR TMP3
	ROR TMP2
	BCC MUL16_SKIP
	CLC
	LDA TMP2+2
	ADC TMP0
	STA TMP2+2
	LDA TMP2+3
	ADC TMP1
	STA TMP2+3
MUL16_SKIP:
	ROR TMP2+3
	ROR TMP2+2
	DEX
	BNE MUL16_LOOP
	LDA TMP2+2
	LDX TMP2+3
	RTS

; DIV8: 8/8=8 divide
; Input: TMP0 (dividend), TMP2 (divisor)
; Output: A=quotient, X=0
DIV8:
	LDA #0
	LDX #8
	CLC
DIV8_LOOP:
	ROL TMP0
	ROL
	CMP TMP2
	BCC DIV8_SKIP
	SBC TMP2
	INC TMP0
DIV8_SKIP:
	DEX
	BNE DIV8_LOOP
	LDA TMP0
	LDX #0
	RTS

; DIV16_8: 16/8=16 divide
; Input: TMP0,TMP1 (dividend), TMP2 (divisor)
; Output: A=low, X=high
DIV16_8:
	LDA #0
	STA TMP3
	LDX #16
DIV16_8_LOOP:
	ROL TMP0
	ROL TMP1
	ROL TMP3
	LDA TMP3
	CMP TMP2
	BCC DIV16_8_SKIP
	SBC TMP2
	STA TMP3
	INC TMP0
DIV16_8_SKIP:
	DEX
	BNE DIV16_8_LOOP
	LDA TMP0
	LDX TMP1
	RTS

; DIV8_16: 8/16=8 divide
; Input: TMP0 (dividend), TMP2,TMP3 (divisor)
; Output: A=quotient (0 or 1), X=0
DIV8_16:
	LDA TMP0
	CMP TMP2
	LDA #0
	SBC TMP3
	BCC DIV8_16_ZERO
	LDA #1
	LDX #0
	RTS
DIV8_16_ZERO:
	LDA #0
	LDX #0
	RTS

; DIV16: 16/16=16 divide
; Input: TMP0,TMP1 (dividend), TMP2,TMP3 (divisor)
; Output: A=low, X=high
DIV16:
	LDA #0
	STA TMP2+2
	LDA #0
	STA TMP2+3
	LDX #16
DIV16_LOOP:
	ROL TMP0
	ROL TMP1
	ROL TMP2+2
	ROL TMP2+3
	LDA TMP2+2
	CMP TMP2
	LDA TMP2+3
	SBC TMP3
	BCC DIV16_SKIP
	LDA TMP2+2
	SBC TMP2
	STA TMP2+2
	LDA TMP2+3
	SBC TMP3
	STA TMP2+3
	INC TMP0
DIV16_SKIP:
	DEX
	BNE DIV16_LOOP
	LDA TMP0
	LDX TMP1
	RTS

; MOD8: 8%8=8 modulo
; Input: TMP0 (dividend), TMP2 (divisor)
; Output: A=remainder, X=0
MOD8:
	LDA #0
	LDX #8
	CLC
MOD8_LOOP:
	ROL TMP0
	ROL
	CMP TMP2
	BCC MOD8_SKIP
	SBC TMP2
	INC TMP0
MOD8_SKIP:
	DEX
	BNE MOD8_LOOP
	LDX #0
	RTS

; MOD16_8: 16%8=8 modulo
; Input: TMP0,TMP1 (dividend), TMP2 (divisor)
; Output: A=remainder, X=0
MOD16_8:
	LDA #0
	STA TMP3
	LDX #16
MOD16_8_LOOP:
	ROL TMP0
	ROL TMP1
	ROL TMP3
	LDA TMP3
	CMP TMP2
	BCC MOD16_8_SKIP
	SBC TMP2
	STA TMP3
	INC TMP0
MOD16_8_SKIP:
	DEX
	BNE MOD16_8_LOOP
	LDA TMP3
	LDX #0
	RTS

; MOD8_16: 8%16=8 modulo
; Input: TMP0 (dividend), TMP2,TMP3 (divisor)
; Output: A=remainder, X=0
MOD8_16:
	LDA TMP0
	CMP TMP2
	LDA #0
	SBC TMP3
	BCC MOD8_16_RET
	LDA TMP0
	SBC TMP2
	LDX #0
	RTS
MOD8_16_RET:
	LDA TMP0
	LDX #0
	RTS

; MOD16: 16%16=16 modulo
; Input: TMP0,TMP1 (dividend), TMP2,TMP3 (divisor)
; Output: A=low, X=high
MOD16:
	LDA #0
	STA TMP2+2
	LDA #0
	STA TMP2+3
	LDX #16
MOD16_LOOP:
	ROL TMP0
	ROL TMP1
	ROL TMP2+2
	ROL TMP2+3
	LDA TMP2+2
	CMP TMP2
	LDA TMP2+3
	SBC TMP3
	BCC MOD16_SKIP
	LDA TMP2+2
	SBC TMP2
	STA TMP2+2
	LDA TMP2+3
	SBC TMP3
	STA TMP2+3
	INC TMP0
MOD16_SKIP:
	DEX
	BNE MOD16_LOOP
	LDA TMP2+2
	LDX TMP2+3
	RTS
__END:
.export __END

; End of file