; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python /home/dusan/src/ZAP-compiler/compiler.py /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap -o /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp_default.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_4
__MATH1                 = __LVSLOT_5
__TMP0                  = __LVSLOT_6
__TMP1:	.res 2
__TMP2                  = __LVSLOT_7
__TMP3                  = __LVSLOT_8
; Fixed-address variables
_RESULT                 = $9C40
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 4
__LVSLOT_2:	.res 4
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 4
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
; Long variables
; ZP usage: 24 of 256 bytes ($00-$17), 232 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 22: byte result @40000 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 24: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$X                 = __LVSLOT_1
_MAIN$Y                 = __LVSLOT_2
_MAIN$Z                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 30:     x = $12345678
	LDA #$78
	STA _MAIN$X
	LDA #$56
	STA _MAIN$X+1
	LDA #$34
	STA _MAIN$X+2
	LDA #$12
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 31:     y = $0F0F0F0F
	LDA #$0F
	STA _MAIN$Y
	STA _MAIN$Y+1
	STA _MAIN$Y+2
	STA _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 32:     z = x & y          ; $02040608
	LDA _MAIN$Y
	STA __MATH1
	LDA _MAIN$Y+1
	STA __MATH1+1
	LDA _MAIN$Y+2
	STA __MATH1+2
	LDA _MAIN$Y+3
	STA __MATH1+3
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	LDA __MATH0
	AND __MATH1
	STA __MATH0
	LDA __MATH0+1
	AND __MATH1+1
	STA __MATH0+1
	LDA __MATH0+2
	AND __MATH1+2
	STA __MATH0+2
	LDA __MATH0+3
	AND __MATH1+3
	STA __MATH0+3
	LDA __MATH0
	STA _MAIN$Z
	LDA __MATH0+1
	STA _MAIN$Z+1
	LDA __MATH0+2
	STA _MAIN$Z+2
	LDA __MATH0+3
	STA _MAIN$Z+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 33:     if z == $02040608
	LDA _MAIN$Z+3
	CMP #$02
	BNE __ZAP_REL_ELSE_TMP_4
	LDA _MAIN$Z+2
	CMP #$04
	BNE __ZAP_REL_ELSE_TMP_4
	LDA _MAIN$Z+1
	CMP #$06
	BNE __ZAP_REL_ELSE_TMP_4
	LDA _MAIN$Z
	CMP #$08
	BEQ __ZAP_then_3
__ZAP_REL_ELSE_TMP_4:
	JMP __ZAP_else_1
__ZAP_then_3:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 34:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_2
__ZAP_else_1:
__ZAP_endif_2:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 38:     x = $12345678
	LDA #$78
	STA _MAIN$X
	LDA #$56
	STA _MAIN$X+1
	LDA #$34
	STA _MAIN$X+2
	LDA #$12
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 39:     y = $0F0F0F0F
	LDA #$0F
	STA _MAIN$Y
	STA _MAIN$Y+1
	STA _MAIN$Y+2
	STA _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 40:     z = x | y          ; $1F3F5F7F
	LDA _MAIN$Y
	STA __MATH1
	LDA _MAIN$Y+1
	STA __MATH1+1
	LDA _MAIN$Y+2
	STA __MATH1+2
	LDA _MAIN$Y+3
	STA __MATH1+3
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH1
	STA __MATH0
	LDA __MATH0+1
	ORA __MATH1+1
	STA __MATH0+1
	LDA __MATH0+2
	ORA __MATH1+2
	STA __MATH0+2
	LDA __MATH0+3
	ORA __MATH1+3
	STA __MATH0+3
	LDA __MATH0
	STA _MAIN$Z
	LDA __MATH0+1
	STA _MAIN$Z+1
	LDA __MATH0+2
	STA _MAIN$Z+2
	LDA __MATH0+3
	STA _MAIN$Z+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 41:     if z == $1F3F5F7F
	LDA _MAIN$Z+3
	CMP #$1F
	BNE __ZAP_REL_ELSE_TMP_8
	LDA _MAIN$Z+2
	CMP #$3F
	BNE __ZAP_REL_ELSE_TMP_8
	LDA _MAIN$Z+1
	CMP #$5F
	BNE __ZAP_REL_ELSE_TMP_8
	LDA _MAIN$Z
	CMP #$7F
	BEQ __ZAP_then_7
__ZAP_REL_ELSE_TMP_8:
	JMP __ZAP_else_5
__ZAP_then_7:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 42:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_6
__ZAP_else_5:
__ZAP_endif_6:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 46:     x = $12345678
	LDA #$78
	STA _MAIN$X
	LDA #$56
	STA _MAIN$X+1
	LDA #$34
	STA _MAIN$X+2
	LDA #$12
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 47:     y = $0F0F0F0F
	LDA #$0F
	STA _MAIN$Y
	STA _MAIN$Y+1
	STA _MAIN$Y+2
	STA _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 48:     z = x ^ y          ; $1D3B5977
	LDA _MAIN$Y
	STA __MATH1
	LDA _MAIN$Y+1
	STA __MATH1+1
	LDA _MAIN$Y+2
	STA __MATH1+2
	LDA _MAIN$Y+3
	STA __MATH1+3
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	LDA __MATH0
	EOR __MATH1
	STA __MATH0
	LDA __MATH0+1
	EOR __MATH1+1
	STA __MATH0+1
	LDA __MATH0+2
	EOR __MATH1+2
	STA __MATH0+2
	LDA __MATH0+3
	EOR __MATH1+3
	STA __MATH0+3
	LDA __MATH0
	STA _MAIN$Z
	LDA __MATH0+1
	STA _MAIN$Z+1
	LDA __MATH0+2
	STA _MAIN$Z+2
	LDA __MATH0+3
	STA _MAIN$Z+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 49:     if z == $1D3B5977
	LDA _MAIN$Z+3
	CMP #$1D
	BNE __ZAP_REL_ELSE_TMP_12
	LDA _MAIN$Z+2
	CMP #$3B
	BNE __ZAP_REL_ELSE_TMP_12
	LDA _MAIN$Z+1
	CMP #$59
	BNE __ZAP_REL_ELSE_TMP_12
	LDA _MAIN$Z
	CMP #$77
	BEQ __ZAP_then_11
__ZAP_REL_ELSE_TMP_12:
	JMP __ZAP_else_9
__ZAP_then_11:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 50:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_10
__ZAP_else_9:
__ZAP_endif_10:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 54:     x = $12345678
	LDA #$78
	STA _MAIN$X
	LDA #$56
	STA _MAIN$X+1
	LDA #$34
	STA _MAIN$X+2
	LDA #$12
	STA _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 55:     z = ~x             ; $EDCBA987
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	LDA __MATH0
	EOR #$FF
	STA __MATH0
	LDA __MATH0+1
	EOR #$FF
	STA __MATH0+1
	LDA __MATH0+2
	EOR #$FF
	STA __MATH0+2
	LDA __MATH0+3
	EOR #$FF
	STA __MATH0+3
	LDA __MATH0
	STA _MAIN$Z
	LDA __MATH0+1
	STA _MAIN$Z+1
	LDA __MATH0+2
	STA _MAIN$Z+2
	LDA __MATH0+3
	STA _MAIN$Z+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 56:     if z == $EDCBA987
	LDA _MAIN$Z+3
	CMP #$ED
	BNE __ZAP_REL_ELSE_TMP_16
	LDA _MAIN$Z+2
	CMP #$CB
	BNE __ZAP_REL_ELSE_TMP_16
	LDA _MAIN$Z+1
	CMP #$A9
	BNE __ZAP_REL_ELSE_TMP_16
	LDA _MAIN$Z
	CMP #$87
	BEQ __ZAP_then_15
__ZAP_REL_ELSE_TMP_16:
	JMP __ZAP_else_13
__ZAP_then_15:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 57:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_14
__ZAP_else_13:
__ZAP_endif_14:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 61:     x = 100000
	LDA #$A0
	STA _MAIN$X
	LDA #$86
	STA _MAIN$X+1
	LDA #$01
	STA _MAIN$X+2
	STZ _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 62:     y = 30000
	LDA #$30
	STA _MAIN$Y
	LDA #$75
	STA _MAIN$Y+1
	STZ _MAIN$Y+2
	STZ _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 63:     z = x % y          ; 10000
	LDA _MAIN$Y
	STA __MATH1
	LDA _MAIN$Y+1
	STA __MATH1+1
	LDA _MAIN$Y+2
	STA __MATH1+2
	LDA _MAIN$Y+3
	STA __MATH1+3
	LDA _MAIN$X
	STA __MATH0
	LDA _MAIN$X+1
	STA __MATH0+1
	LDA _MAIN$X+2
	STA __MATH0+2
	LDA _MAIN$X+3
	STA __MATH0+3
	JSR MOD32
	LDA __MATH0
	STA _MAIN$Z
	LDA __MATH0+1
	STA _MAIN$Z+1
	LDA __MATH0+2
	STA _MAIN$Z+2
	LDA __MATH0+3
	STA _MAIN$Z+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 64:     if z == 10000
	LDA _MAIN$Z+3
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_20
	LDA _MAIN$Z+2
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_20
	LDA _MAIN$Z+1
	CMP #$27
	BNE __ZAP_REL_ELSE_TMP_20
	LDA _MAIN$Z
	CMP #$10
	BEQ __ZAP_then_19
__ZAP_REL_ELSE_TMP_20:
	JMP __ZAP_else_17
__ZAP_then_19:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 65:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_18
__ZAP_else_17:
__ZAP_endif_18:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 69:     x = 65536
	STZ _MAIN$X
	STZ _MAIN$X+1
	STZ _MAIN$X+3
	LDA #$01
	STA _MAIN$X+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 70:     y = 65536
	STZ _MAIN$Y
	STZ _MAIN$Y+1
	STZ _MAIN$Y+3
	LDA #$01
	STA _MAIN$Y+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 71:     if x == y
	LDA _MAIN$X+3
	CMP _MAIN$Y+3
	BNE __ZAP_REL_ELSE_TMP_24
	LDA _MAIN$X+2
	CMP _MAIN$Y+2
	BNE __ZAP_REL_ELSE_TMP_24
	LDA _MAIN$X+1
	CMP _MAIN$Y+1
	BNE __ZAP_REL_ELSE_TMP_24
	LDA _MAIN$X
	CMP _MAIN$Y
	BEQ __ZAP_then_23
__ZAP_REL_ELSE_TMP_24:
	JMP __ZAP_else_21
__ZAP_then_23:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 72:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_22
__ZAP_else_21:
__ZAP_endif_22:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 76:     x = 65536
	STZ _MAIN$X
	STZ _MAIN$X+1
	STZ _MAIN$X+3
	LDA #$01
	STA _MAIN$X+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 77:     y = 65537
	LDA #$01
	STA _MAIN$Y
	STA _MAIN$Y+2
	STZ _MAIN$Y+1
	STZ _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 78:     if x != y
	LDA _MAIN$X+3
	CMP _MAIN$Y+3
	BNE __ZAP_then_27
	LDA _MAIN$X+2
	CMP _MAIN$Y+2
	BNE __ZAP_then_27
	LDA _MAIN$X+1
	CMP _MAIN$Y+1
	BNE __ZAP_then_27
	LDA _MAIN$X
	CMP _MAIN$Y
	BEQ __ZAP_else_25
__ZAP_then_27:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 79:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_26
__ZAP_else_25:
__ZAP_endif_26:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 83:     x = 65536
	STZ _MAIN$X
	STZ _MAIN$X+1
	STZ _MAIN$X+3
	LDA #$01
	STA _MAIN$X+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 84:     y = 65537
	LDA #$01
	STA _MAIN$Y
	STA _MAIN$Y+2
	STZ _MAIN$Y+1
	STZ _MAIN$Y+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 85:     if x < y
	LDA _MAIN$X+3
	CMP _MAIN$Y+3
	BNE __ZAP_CMP32_DECIDE_31
	LDA _MAIN$X+2
	CMP _MAIN$Y+2
	BNE __ZAP_CMP32_DECIDE_31
	LDA _MAIN$X+1
	CMP _MAIN$Y+1
	BNE __ZAP_CMP32_DECIDE_31
	LDA _MAIN$X
	CMP _MAIN$Y
__ZAP_CMP32_DECIDE_31:
	BCS __ZAP_else_28
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 86:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_29
__ZAP_else_28:
__ZAP_endif_29:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 90:     x = 65536
	STZ _MAIN$X
	STZ _MAIN$X+1
	STZ _MAIN$X+3
	LDA #$01
	STA _MAIN$X+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 91:     y = 65536
	STZ _MAIN$Y
	STZ _MAIN$Y+1
	STZ _MAIN$Y+3
	LDA #$01
	STA _MAIN$Y+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 92:     if x <= y
	LDA _MAIN$X+3
	CMP _MAIN$Y+3
	BNE __ZAP_CMP32_DECIDE_35
	LDA _MAIN$X+2
	CMP _MAIN$Y+2
	BNE __ZAP_CMP32_DECIDE_35
	LDA _MAIN$X+1
	CMP _MAIN$Y+1
	BNE __ZAP_CMP32_DECIDE_35
	LDA _MAIN$X
	CMP _MAIN$Y
__ZAP_CMP32_DECIDE_35:
	BCC __ZAP_then_34
	BNE __ZAP_else_32
__ZAP_then_34:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 93:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_33
__ZAP_else_32:
__ZAP_endif_33:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 97:     x = 65537
	LDA #$01
	STA _MAIN$X
	STA _MAIN$X+2
	STZ _MAIN$X+1
	STZ _MAIN$X+3
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 98:     y = 65536
	STZ _MAIN$Y
	STZ _MAIN$Y+1
	STZ _MAIN$Y+3
	LDA #$01
	STA _MAIN$Y+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 99:     if x > y
	LDA _MAIN$X+3
	CMP _MAIN$Y+3
	BNE __ZAP_CMP32_DECIDE_39
	LDA _MAIN$X+2
	CMP _MAIN$Y+2
	BNE __ZAP_CMP32_DECIDE_39
	LDA _MAIN$X+1
	CMP _MAIN$Y+1
	BNE __ZAP_CMP32_DECIDE_39
	LDA _MAIN$X
	CMP _MAIN$Y
__ZAP_CMP32_DECIDE_39:
	BEQ __ZAP_REL_ELSE_TMP_40
	BCS __ZAP_then_38
__ZAP_REL_ELSE_TMP_40:
	JMP __ZAP_else_36
__ZAP_then_38:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 100:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_37
__ZAP_else_36:
__ZAP_endif_37:
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 104:     x = 65536
	STZ _MAIN$X
	STZ _MAIN$X+1
	STZ _MAIN$X+3
	LDA #$01
	STA _MAIN$X+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 105:     y = 65536
	STZ _MAIN$Y
	STZ _MAIN$Y+1
	STZ _MAIN$Y+3
	LDA #$01
	STA _MAIN$Y+2
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 106:     if x >= y
	LDA _MAIN$X+3
	CMP _MAIN$Y+3
	BNE __ZAP_CMP32_DECIDE_44
	LDA _MAIN$X+2
	CMP _MAIN$Y+2
	BNE __ZAP_CMP32_DECIDE_44
	LDA _MAIN$X+1
	CMP _MAIN$Y+1
	BNE __ZAP_CMP32_DECIDE_44
	LDA _MAIN$X
	CMP _MAIN$Y
__ZAP_CMP32_DECIDE_44:
	BCC __ZAP_else_41
; /home/dusan/src/ZAP-compiler/tests/pass/161-long-bitwise-cmp/161-long-bitwise-cmp.zap 107:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_42
__ZAP_else_41:
__ZAP_endif_42:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; MOD32: __MATH0 = __MATH0 % __MATH1 (Unsigned)
MOD32:
	STZ __TMP0
	STZ __TMP1
	STZ __TMP2
	STZ __TMP3
	LDX #32
MOD32_LOOP:
	ASL __MATH0
	ROL __MATH0+1
	ROL __MATH0+2
	ROL __MATH0+3
	ROL __TMP0
	ROL __TMP1
	ROL __TMP2
	ROL __TMP3
	SEC
	LDA __TMP0
	SBC __MATH1
	TAY
	LDA __TMP1
	SBC __MATH1+1
	PHA
	LDA __TMP2
	SBC __MATH1+2
	PHA
	LDA __TMP3
	SBC __MATH1+3
	BCC MOD32_SKIP
	STA __TMP3
	PLA
	STA __TMP2
	PLA
	STA __TMP1
	STY __TMP0
	INC __MATH0
	JMP MOD32_NEXT
MOD32_SKIP:
	PLA
	PLA
MOD32_NEXT:
	DEX
	BNE MOD32_LOOP
	LDA __TMP0
	STA __MATH0
	LDA __TMP1
	STA __MATH0+1
	LDA __TMP2
	STA __MATH0+2
	LDA __TMP3
	STA __MATH0+3
	RTS
; End of file