; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -6502 -O1 tests/pass/233-word-compound-full/233-word-compound-full.zap -o tests/pass/233-word-compound-full/233-word-compound-full_6502_-O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_3
__MATH1                 = __LVSLOT_4
__TMP0                  = __LVSLOT_5
__TMP1:	.res 2
__TMP2                  = __LVSLOT_6
__TMP3                  = __LVSLOT_7
__TMP4                  = __LVSLOT_8
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 2
__LVSLOT_3:	.res 4
__LVSLOT_4:	.res 4
__LVSLOT_5:	.res 2
__LVSLOT_6:	.res 2
__LVSLOT_7:	.res 2
__LVSLOT_8:	.res 2
; Word variables
; ZP usage: 20 of 256 bytes ($00-$13), 236 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 14: byte result @$0200 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
_MAIN$W                 = __LVSLOT_1
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 17:     word w = 100
	LDA #$64
	STA _MAIN$W
	LDA #$00
	STA _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 20:     w *= 3
	LDA _MAIN$W
	STA __MATH0
	LDA _MAIN$W+1
	STA __MATH0+1
	LDA #$03
	LDX #$00
	JSR __MUL16_AX
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 21:     if w == 300
	CMP #$2C
	BNE __ZAP_else_1
	CPX #$01
	BNE __ZAP_else_1
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 22:         result = result + 1
	INC _RESULT
__ZAP_else_1:
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 26:     w /= 5
	LDA _MAIN$W
	STA __MATH0
	LDA _MAIN$W+1
	STA __MATH0+1
	LDA #$05
	LDX #$00
	JSR __DIV16_AX
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 27:     if w == 60
	CMP #$3C
	BNE __ZAP_else_5
	CPX #$00
	BNE __ZAP_else_5
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 28:         result = result + 1
	INC _RESULT
__ZAP_else_5:
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 32:     w %= 17
	LDA _MAIN$W
	STA __MATH0
	LDA _MAIN$W+1
	STA __MATH0+1
	LDA #$11
	LDX #$00
	JSR __MOD16_AX
	STA _MAIN$W
	STX _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 33:     if w == 9
	CMP #$09
	BNE __ZAP_else_9
	CPX #$00
	BNE __ZAP_else_9
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 34:         result = result + 1
	INC _RESULT
__ZAP_else_9:
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 38:     w &= $0F
	LDA _MAIN$W
	AND #$0F
	STA _MAIN$W
	LDA #$00
	STA _MAIN$W+1
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 39:     if w == 9
	LDA _MAIN$W
	CMP #$09
	BNE __ZAP_else_13
	LDX _MAIN$W+1
	BNE __ZAP_else_13
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 40:         result = result + 1
	INC _RESULT
__ZAP_else_13:
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 44:     w |= $F0
	LDA _MAIN$W
	ORA #$F0
	STA _MAIN$W
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 45:     if w == $F9
	CMP #$F9
	BNE __ZAP_else_17
	LDX _MAIN$W+1
	BNE __ZAP_else_17
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 46:         result = result + 1
	INC _RESULT
__ZAP_else_17:
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 50:     w ^= $FF
	LDA _MAIN$W
	EOR #$FF
	STA _MAIN$W
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 51:     if w == 6
	CMP #$06
	BNE __ZAP_else_21
	LDX _MAIN$W+1
	BNE __ZAP_else_21
; /home/dusan/src/ZAP-compiler/tests/pass/233-word-compound-full/233-word-compound-full.zap 52:         result = result + 1
	INC _RESULT
__ZAP_else_21:
	RTS


.segment "CODE"
; ---------------------------------------------------------------------------
; Math Runtime Routines
; __MUL16_AX: right operand (word) in A/X
__MUL16_AX:
	STA __MATH1
	STX __MATH1+1
; __MUL16: 16x16=32 multiply (shift-add implementation)
; Input: __MATH0 low word (multiplicand), __MATH1 low word (multiplier)
; Output: __MATH0=product (32-bit)
__MUL16:
	LDA __MATH0
	STA __TMP0
	LDA __MATH0+1
	STA __TMP1
	LDA #$00
	STA __TMP2
	STA __TMP3
	LDA __MATH1
	STA __TMP4
	LDA __MATH1+1
	STA __TMP4+1
	LDA #$00
	STA __MATH0
	STA __MATH0+1
	STA __MATH0+2
	STA __MATH0+3
	LDX #$10
MUL16_LOOP:
	LSR __TMP4+1
	ROR __TMP4
	BCC MUL16_SKIP
	LDA __MATH0
	CLC
	ADC __TMP0
	STA __MATH0
	LDA __MATH0+1
	ADC __TMP1
	STA __MATH0+1
	LDA __MATH0+2
	ADC __TMP2
	STA __MATH0+2
	LDA __MATH0+3
	ADC __TMP3
	STA __MATH0+3
MUL16_SKIP:
	ASL __TMP0
	ROL __TMP1
	ROL __TMP2
	ROL __TMP3
	DEX
	BNE MUL16_LOOP
	LDA __MATH0
	LDX __MATH0+1
	RTS
__DIV16_AX:
	STA __MATH1
	STX __MATH1+1
; __DIV16: 16/16=16 divide
; Input: __MATH0 low word (dividend), __MATH1 low word (divisor)
; Output: __MATH0=quotient (low word)
__DIV16:
	LDA #$00
	STA __MATH0+2
	STA __MATH0+3
	LDX #16
	CLC
DIV16_LOOP:
	ROL __MATH0
	ROL __MATH0+1
	ROL __MATH0+2
	ROL __MATH0+3
	LDA __MATH0+2
	CMP __MATH1
	LDA __MATH0+3
	SBC __MATH1+1
	BCC DIV16_SKIP
	LDA __MATH0+2
	SBC __MATH1
	STA __MATH0+2
	LDA __MATH0+3
	SBC __MATH1+1
	STA __MATH0+3
DIV16_SKIP:
	DEX
	BNE DIV16_LOOP
	ROL __MATH0
	ROL __MATH0+1
	LDA #$00
	STA __MATH0+2
	STA __MATH0+3
	LDA __MATH0
	LDX __MATH0+1
	RTS
__MOD16_AX:
	STA __MATH1
	STX __MATH1+1
; __MOD16: 16%16=16 modulo
; Input: __MATH0 low word (dividend), __MATH1 low word (divisor)
; Output: __MATH0=remainder (low word)
__MOD16:
	LDA #$00
	STA __MATH0+2
	STA __MATH0+3
	LDX #16
	CLC
MOD16_LOOP:
	ROL __MATH0
	ROL __MATH0+1
	ROL __MATH0+2
	ROL __MATH0+3
	LDA __MATH0+2
	CMP __MATH1
	LDA __MATH0+3
	SBC __MATH1+1
	BCC MOD16_SKIP
	LDA __MATH0+2
	SBC __MATH1
	STA __MATH0+2
	LDA __MATH0+3
	SBC __MATH1+1
	STA __MATH0+3
MOD16_SKIP:
	DEX
	BNE MOD16_LOOP
	LDA __MATH0+2
	STA __MATH0
	LDA __MATH0+3
	STA __MATH0+1
	LDA #$00
	STA __MATH0+2
	STA __MATH0+3
	LDA __MATH0
	LDX __MATH0+1
	RTS