; Generated by Zap Compiler 0.9.5
; Command: /home/dusan/src/ZAP-compiler/.venv/bin/python3 compiler.py -6502 tests/pass/238-long-logical-cond/238-long-logical-cond.zap -o tests/pass/238-long-logical-cond/238-long-logical-cond_6502.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
__MATH0                 = __LVSLOT_6
__MATH1                 = __LVSLOT_7
; Fixed-address variables
_RESULT                 = $0200
; Shared slots (for aliased locals)
__LVSLOT_1:	.res 4
__LVSLOT_2:	.res 4
__LVSLOT_3:	.res 4
__LVSLOT_4:	.res 1
__LVSLOT_6:	.res 4
__LVSLOT_7:	.res 4
; Byte variables
; Long variables
; ZP usage: 21 of 256 bytes ($00-$14), 235 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 12: byte result @$0200 = 0
	LDA #$00
	STA _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 14: proc main()
; -- Procedure MAIN --
_MAIN:
_MAIN$A                 = __LVSLOT_1
_MAIN$B                 = __LVSLOT_2
_MAIN$C                 = __LVSLOT_3
_MAIN$COUNT             = __LVSLOT_4
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 21:     a = 3
	LDA #$03
	STA _MAIN$A
	LDA #$00
	STA _MAIN$A+1
	STA _MAIN$A+2
	STA _MAIN$A+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 22:     b = 2
	LDA #$02
	STA _MAIN$B
	LDA #$00
	STA _MAIN$B+1
	STA _MAIN$B+2
	STA _MAIN$B+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 23:     count = 0
	LDA #$00
	STA _MAIN$COUNT
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 24:     while a && b
__ZAP_while_1:
	LDA _MAIN$B
	STA __MATH1
	LDA _MAIN$B+1
	STA __MATH1+1
	LDA _MAIN$B+2
	STA __MATH1+2
	LDA _MAIN$B+3
	STA __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	LDA _MAIN$A+1
	STA __MATH0+1
	LDA _MAIN$A+2
	STA __MATH0+2
	LDA _MAIN$A+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND32_BRANCH_4
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BEQ __ZAP_LAND32_BRANCH_4
	LDA #$01
	JMP __ZAP_LAND32_END_5
__ZAP_LAND32_BRANCH_4:
	LDA #$00
__ZAP_LAND32_END_5:
	STA __MATH0
	LDA __MATH0
	BEQ __ZAP_endwhile_2
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 25:         a = a - 1
	LDA _MAIN$A
	BNE __ZAP_SKIP_DEC32_6
	LDA _MAIN$A+1
	BNE __ZAP_SKIP_DEC32_6
	LDA _MAIN$A+2
	BNE __ZAP_SKIP_DEC32_6
	DEC _MAIN$A+3
__ZAP_SKIP_DEC32_6:
	LDA _MAIN$A
	BNE __ZAP_SKIP_DEC32_2_7
	LDA _MAIN$A+1
	BNE __ZAP_SKIP_DEC32_2_7
	DEC _MAIN$A+2
__ZAP_SKIP_DEC32_2_7:
	LDA _MAIN$A
	BNE __ZAP_SKIP_DEC32_3_8
	DEC _MAIN$A+1
__ZAP_SKIP_DEC32_3_8:
	DEC _MAIN$A
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 26:         b = b - 1
	LDA _MAIN$B
	BNE __ZAP_SKIP_DEC32_9
	LDA _MAIN$B+1
	BNE __ZAP_SKIP_DEC32_9
	LDA _MAIN$B+2
	BNE __ZAP_SKIP_DEC32_9
	DEC _MAIN$B+3
__ZAP_SKIP_DEC32_9:
	LDA _MAIN$B
	BNE __ZAP_SKIP_DEC32_2_10
	LDA _MAIN$B+1
	BNE __ZAP_SKIP_DEC32_2_10
	DEC _MAIN$B+2
__ZAP_SKIP_DEC32_2_10:
	LDA _MAIN$B
	BNE __ZAP_SKIP_DEC32_3_11
	DEC _MAIN$B+1
__ZAP_SKIP_DEC32_3_11:
	DEC _MAIN$B
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 27:         count = count + 1
	INC _MAIN$COUNT
	JMP __ZAP_while_1
__ZAP_endwhile_2:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 30:     if count == 2
	LDA _MAIN$COUNT
	CMP #$02
	BNE __ZAP_else_12
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 31:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_13
__ZAP_else_12:
__ZAP_endif_13:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 35:     a = 0
	LDA #$00
	STA _MAIN$A
	STA _MAIN$A+1
	STA _MAIN$A+2
	STA _MAIN$A+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 36:     b = 0
	LDA #$00
	STA _MAIN$B
	STA _MAIN$B+1
	STA _MAIN$B+2
	STA _MAIN$B+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 37:     count = 0
	LDA #$00
	STA _MAIN$COUNT
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 38:     repeat
__ZAP_repeat_15:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 39:         count = count + 1
	INC _MAIN$COUNT
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 40:         if count == 3
	LDA _MAIN$COUNT
	CMP #$03
	BNE __ZAP_else_18
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 41:             b = 1
	LDA #$01
	STA _MAIN$B
	LDA #$00
	STA _MAIN$B+1
	STA _MAIN$B+2
	STA _MAIN$B+3
	JMP __ZAP_endif_19
__ZAP_else_18:
__ZAP_endif_19:
	LDA _MAIN$B
	STA __MATH1
	LDA _MAIN$B+1
	STA __MATH1+1
	LDA _MAIN$B+2
	STA __MATH1+2
	LDA _MAIN$B+3
	STA __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	LDA _MAIN$A+1
	STA __MATH0+1
	LDA _MAIN$A+2
	STA __MATH0+2
	LDA _MAIN$A+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BNE __ZAP_LOR32_BRANCH_21
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BNE __ZAP_LOR32_BRANCH_21
	LDA #$00
	JMP __ZAP_LOR32_END_22
__ZAP_LOR32_BRANCH_21:
	LDA #$01
__ZAP_LOR32_END_22:
	STA __MATH0
	LDA __MATH0
	BEQ __ZAP_repeat_15
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 44:     if count == 3
	LDA _MAIN$COUNT
	CMP #$03
	BNE __ZAP_else_23
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 45:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_24
__ZAP_else_23:
__ZAP_endif_24:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 49:     a = $10000
	LDA #$00
	STA _MAIN$A
	STA _MAIN$A+1
	STA _MAIN$A+3
	LDA #$01
	STA _MAIN$A+2
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 50:     c = 0
	LDA #$00
	STA _MAIN$C
	STA _MAIN$C+1
	STA _MAIN$C+2
	STA _MAIN$C+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 51:     b = 0
	LDA #$00
	STA _MAIN$B
	STA _MAIN$B+1
	STA _MAIN$B+2
	STA _MAIN$B+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 52:     while b < 3
__ZAP_while_26:
	LDA _MAIN$B+3
	CMP #$00
	BNE __ZAP_CMP32_DECIDE_29
	LDA _MAIN$B+2
	CMP #$00
	BNE __ZAP_CMP32_DECIDE_29
	LDA _MAIN$B+1
	CMP #$00
	BNE __ZAP_CMP32_DECIDE_29
	LDA _MAIN$B
	CMP #$03
__ZAP_CMP32_DECIDE_29:
	BCC __ZAP_while_body_28
	JMP __ZAP_endwhile_27
__ZAP_while_body_28:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 53:         if a && a
	LDA _MAIN$A
	STA __MATH1
	LDA _MAIN$A+1
	STA __MATH1+1
	LDA _MAIN$A+2
	STA __MATH1+2
	LDA _MAIN$A+3
	STA __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	LDA _MAIN$A+1
	STA __MATH0+1
	LDA _MAIN$A+2
	STA __MATH0+2
	LDA _MAIN$A+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND32_BRANCH_33
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BEQ __ZAP_LAND32_BRANCH_33
	LDA #$01
	JMP __ZAP_LAND32_END_34
__ZAP_LAND32_BRANCH_33:
	LDA #$00
__ZAP_LAND32_END_34:
	STA __MATH0
	LDA __MATH0
	BEQ __ZAP_else_30
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 54:             c = c + 1
	INC _MAIN$C
	BNE __ZAP_SKIP_INC32_35
	INC _MAIN$C+1
	BNE __ZAP_SKIP_INC32_35
	INC _MAIN$C+2
	BNE __ZAP_SKIP_INC32_35
	INC _MAIN$C+3
__ZAP_SKIP_INC32_35:
	JMP __ZAP_endif_31
__ZAP_else_30:
__ZAP_endif_31:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 56:         b = b + 1
	INC _MAIN$B
	BNE __ZAP_SKIP_INC32_36
	INC _MAIN$B+1
	BNE __ZAP_SKIP_INC32_36
	INC _MAIN$B+2
	BNE __ZAP_SKIP_INC32_36
	INC _MAIN$B+3
__ZAP_SKIP_INC32_36:
	JMP __ZAP_while_26
__ZAP_endwhile_27:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 58:     if c == 3
	LDA _MAIN$C+3
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_40
	LDA _MAIN$C+2
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_40
	LDA _MAIN$C+1
	CMP #$00
	BNE __ZAP_REL_ELSE_TMP_40
	LDA _MAIN$C
	CMP #$03
	BEQ __ZAP_then_39
__ZAP_REL_ELSE_TMP_40:
	JMP __ZAP_else_37
__ZAP_then_39:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 59:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_38
__ZAP_else_37:
__ZAP_endif_38:
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 63:     a = 1
	LDA #$01
	STA _MAIN$A
	LDA #$00
	STA _MAIN$A+1
	STA _MAIN$A+2
	STA _MAIN$A+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 64:     b = $FFFF0000
	LDA #$00
	STA _MAIN$B
	STA _MAIN$B+1
	LDA #$FF
	STA _MAIN$B+2
	STA _MAIN$B+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 65:     c = $12345678
	LDA #$78
	STA _MAIN$C
	LDA #$56
	STA _MAIN$C+1
	LDA #$34
	STA _MAIN$C+2
	LDA #$12
	STA _MAIN$C+3
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 66:     if (a && b) && c
	LDA _MAIN$B
	STA __MATH1
	LDA _MAIN$B+1
	STA __MATH1+1
	LDA _MAIN$B+2
	STA __MATH1+2
	LDA _MAIN$B+3
	STA __MATH1+3
	LDA _MAIN$A
	STA __MATH0
	LDA _MAIN$A+1
	STA __MATH0+1
	LDA _MAIN$A+2
	STA __MATH0+2
	LDA _MAIN$A+3
	STA __MATH0+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND32_BRANCH_44
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BEQ __ZAP_LAND32_BRANCH_44
	LDA #$01
	JMP __ZAP_LAND32_END_45
__ZAP_LAND32_BRANCH_44:
	LDA #$00
__ZAP_LAND32_END_45:
	STA __MATH0
	LDA #$00
	STA __MATH0+1
	LDA #$00
	STA __MATH0+2
	LDA #$00
	STA __MATH0+3
	LDA _MAIN$C
	STA __MATH1
	LDA _MAIN$C+1
	STA __MATH1+1
	LDA _MAIN$C+2
	STA __MATH1+2
	LDA _MAIN$C+3
	STA __MATH1+3
	LDA __MATH0
	ORA __MATH0+1
	ORA __MATH0+2
	ORA __MATH0+3
	BEQ __ZAP_LAND32_BRANCH_46
	LDA __MATH1
	ORA __MATH1+1
	ORA __MATH1+2
	ORA __MATH1+3
	BEQ __ZAP_LAND32_BRANCH_46
	LDA #$01
	JMP __ZAP_LAND32_END_47
__ZAP_LAND32_BRANCH_46:
	LDA #$00
__ZAP_LAND32_END_47:
	STA __MATH0
	LDA __MATH0
	BEQ __ZAP_else_41
; /home/dusan/src/ZAP-compiler/tests/pass/238-long-logical-cond/238-long-logical-cond.zap 67:         result = result + 1
	INC _RESULT
	JMP __ZAP_endif_42
__ZAP_else_41:
__ZAP_endif_42:
	RTS
; ---------------------------------------------------------------------------


.segment "CODE"
; End of file