; Generated by Zap Compiler 0.9.5
; Command: /usr/bin/python3 compiler.py -O1 tests/pass/242-debug-bss-read/242-debug-bss-read.zap -o tests/pass/242-debug-bss-read/242-debug-bss-read_O1.s
; ==============================
.DEBUGINFO +  ; Enable debug information for symbol names
; ---------------------------------------------------------------------------
.FEATURE	dollar_in_identifiers
; ---------------------------------------------------------------------------
; ---------------------------------------------------------------------------


.segment "ZEROPAGE"
; System variables
; Fixed-address variables
_RESULT                 = $0200
; Byte variables
_BSSVAR:	.res 1
; ZP usage: 1 of 256 bytes ($00-$00), 255 free


.segment "CODE"
GLOBAL_START:
; Globals initialization
; /home/dusan/src/ZAP-compiler/tests/pass/242-debug-bss-read/242-debug-bss-read.zap 2: byte result @$0200 = 0
	STZ _RESULT
; Call MAIN
	JSR _MAIN
	JMP *


; ---------------------------------------------------------------------------
; -- Procedure MAIN --
_MAIN:
; /home/dusan/src/ZAP-compiler/tests/pass/242-debug-bss-read/242-debug-bss-read.zap 6:     bssvar = 7
	LDA #$07
	STA _BSSVAR
; /home/dusan/src/ZAP-compiler/tests/pass/242-debug-bss-read/242-debug-bss-read.zap 7:     result = bssvar
	STA _RESULT
	RTS


.segment "CODE"
; End of file